### ISSUE TITLE
Senior Database Developer

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#107]
Senior Database Developer

 

Company Overview:

Cepeda Systems and Software Analysis, Inc. (CSSA) provides software engineering, systems engineering, and process improvement services for our customers. CSSA has achieved a rating of Capability Maturity Model Integration (CMMI) Level 2 for Services and CMMI Level 3 for Development. We have a 100% customer satisfaction rating and have won numerous awards at the local and national level. We treat one another with respect, foster collaboration while maintaining individual accountability, value multiple perspectives and diverse expertise, and encourage new ideas that surface throughout the organization. CSSA offers a comprehensive and competitive benefits package.

 

Key Responsibilities:

Design and develop schemas, tables, views, stored procedures, functions, and packages needed to support front-end data visualization development utilizing PL/SQL
Design and develop ETL processes and procedures for multiple file formats such as flat text, csv, dat, and Excel
Work closely with front-end developers to determine data requirements
Perform functional database testing, performance tuning, and optimization
Develop database documentation
Perform manual data pull and data loads as needed
Perform database monitoring and troubleshooting
Perform database backups and restores
 

Education Requirements:

B.S. Degree in Computer Science, Computer Information Systems, or related area from an accredited college or university
 

Experience:

Minimum 8 years relevant experience in:

Oracle 11g or newer development and architecure
PL/SQL development
 

Knowledge/Skills:

Strong time management and communication skills
Candidate should be self-motivated and able to multi-task
Ability to adapt to changing situations and requirements
Experience with Web Services development is preferred
 

Licences/Certifications:

CompTIA Security+ CE is required
Oracle Certified Associate (OCA) is preferred
 

U.S. Citizenship is required

Interim Clearance can be granted, so candidate must be able to obtain or have an Active Secret Security Clearance.

 

CSSA is an Equal Employment Opportunity Employer. We do not discriminate in the employment of individuals on the basis of race, color, sex (or pregnancy), religion, age, national origin, disability, veteran status, sexual orientation, gender identity, genetic information, or any other protected category. CSSA hires and promotes individuals solely on the basis of their qualifications for the job to be filled. If you require assistance with the application process, please contact us at careers@cepedasystems.com. We appreciate your interest in our organization.

CSSA participates in the E-Verify program.

Criminal background checks are conducted on all applicants before hire. 

CSSA is a Drug Free Workplace.

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/656514-194689

**Comment by blmeadows** [comment]
@CSSA-HR is this still relevant?
