### ISSUE TITLE
Django developer -- entry level

### ISSUE THREAD

**Issue by drewbrew** [tech256/jobs#108]
# Hiring!

#### Who is OutdoorLink?
OutdoorLink, Inc. is the leading provider of remote lighting management tools to the Out-of-Home advertising industry. The company started in 2007 with 2 employees and since has grown to more than 50 employees and independent contractors. With OutdoorLink entering into new markets, it is a great time to be involved in new product development and growth for the future.
#### Why work for OutdoorLink?
* Small, family-oriented company
* 401(k) with profit sharing
* Health and Dental Insurance
* Limitless growth opportunity
* Direct involvement with new product development that will shape the Out-of-Home advertising industry as well as help OutdoorLink enter new industries
* Work side-by-side with a small team of experienced engineers
#### What will you be doing?
* Build features for next-generation website using the React framework
* Create new versions of mobile applications for Android and iOS using react-native
* Make Django REST Framework API updates as needed to support the above apps
* Coordinate with contractors to delegate development tasks
* Maintain and update existing Python back-end scripts
* Optimize and improve asynchronous tasks using the Celery project
* Maintain and modify database schema via Django migrations
* Keep track of Ubuntu Linux security updates and deploy as needed
* Maintain C code for existing embedded hardware devices
* Provide engineering assistance to technical support personnel as needed
#### What will your development environment be?
* Our software stack is comprised of a Django REST Framework API powered by Django 1.11 running on Python 3.5 and a PostgreSQL 9.5 database serving API calls for a React web app as well as iOS and Android mobile applications.
* We use a self-hosted Gitlab instance using Gitlab CI for continuous integration testing.
* Your development machine will be either a MacBook Pro or a Linux desktop. You’ll have your choice of editors provided you can make your code comply with established standards (e.g. PEP8 compliance for Python code).
#### What is the ideal candidate?
* Someone with 0-3 years of experience in related fields
* Someone with a bachelor’s degree in computer science, software engineering, or a similar field
* Someone with at least a basic knowledge of Python, JavaScript, Java/Kotlin, and/or C
* Someone capable of using a Linux command line
* Someone with a willingness to learn
* Someone comfortable working in small teams and juggling many different tasks
#### What does it pay?
* Starting salary is $63,000 to $67,000 with opportunities to grow.

### Contact
- Tech256: drew
- Location: Huntsville, AL (near the corner of Drake and South Memorial Pkwy)

**Comment by badcoder28** [comment]
Does this entry is still available?

**Comment by drewbrew** [comment]
Oops, sorry, I forgot to close it. The guy we hired started at the first of the year.

My bad!
