### ISSUE TITLE
Archer Sparrow

### ISSUE THREAD

**Issue by iamvery** [tech256/jobs#11]
# Hiring!

## Archer Sparrow
Always looking for good designers and developers to work on web projects

### Contact
- Tech256: @chrisbeaman
- http://www.archersparrow.com
- Huntsville, AL

**Comment by iamvery** [comment]
ping @chrisbeaman (want to keep it? reply "pong")

**Comment by chrisbeaman** [comment]
No, I'm actually phasing out Archer Sparrow while I focus on The Foundry. You can remove this post. Thanks

**Comment by iamvery** [comment]
👍
