### ISSUE TITLE
Database Developer

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#110]
Key Responsibilities:

Design and develop schemas, tables, views, stored procedures, and functions needed to support front-end data visualization development
Work closely with front-end developers to determine data requirements
Perform functional database testing, performance tuning, and optimization
Develop database documentation
Perform weekly and monthly manual data pull and data loads
Perform basic database monitoring and troubleshooting
Perform database backups and restores
Qualifications:

Education:

B.S. Degree in Computer Science, Computer Information Systems, or related field
Experience:

Minimum 4 years relevant experience with Oracle and SQL Server development
Knowledge/Skills:

Experience with SQL Server 2012 and Oracle 11g or newer development and architecture
Experience with T-SQL and PL/SQL
Strong time management skills
Candidate should be self-motivated and able to multi-task
Ability to adapt to changing situations and requirements
The following experience is a plus: .NET Framework, C#, Web Services development
  Licences/Certifications

Microsoft SQL Server 2012
CompTIA Security+ CE
Oracle Certified Associate (OCA) preferred
U.S. Citizenship required.

Secret Security Clearance will be required, but can be obtained on the job.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/630357-194689

**Comment by blmeadows** [comment]
@CSSA-HR is this still relevant?
