### ISSUE TITLE
Full Stack Web Developer (Mid-Level; Full-Time)

### ISSUE THREAD

**Issue by ethar-tone** [tech256/jobs#1114]
# Hiring!

### About Position
Ethar is a growing team of award-winning, globally-recognized immersive technology specialists working on leading-edge commercial projects in the AR/VR field. We are building a first class platform to deliver Augmented Reality and Virtual Reality experiences and are currently seeking a skilled full-stack web developer to help us enable the next-generation communication medium.

As our newest Full Stack Developer, you will be comfortable with both front-end and back-end coding languages, development frameworks and third-party libraries. You will be a team player with a knack for visual design and utility. Our ideal candidate is an insightful and driven developer with extensive technical expertise who can work as part of an integrated team in the creation, maintenance, and updates of websites both for clients and for our core platform offering. Proficiency in JavaScript, HTML, CSS, and other web services and program applications is essential for success in this role. Additionally, you should have experience with front-end web frameworks (especially React), and back-end technologies such as .NET APIs, and/or NodeJS/Express.

Ethar is a startup and our team members take on many roles working across different departments and accountabilities. You will be in a key position of responsibility providing an immediate impact on our brand and that of our clients’, as well as ongoing contributions to solidify our platform’s core functionality. This position requires a candidate who is agile, with excellent communication skills, a proactive attitude, an ability to rapidly master new technologies, and strong good team ethic to help unify and realize our common vision.

To build a great tech startup company in an early-phase market - especially outside Silicon Valley - you need extraordinary talent that dreams big and combines energies towards mutual success. If you see the vision, you’re at the right time and right place. As an Ethar team member, you’ll be presented with a large number of daily challenges, wide latitude in how you accomplish your job, a requirement to constantly learn new things, and the opportunity to make a difference on a global scale. Creating something from nothing isn’t a skill everyone possesses nor has the fortitude to undertake. Candidates must be calm, confident and persistent moving through the unknowns, while bringing a positive & professional attitude to the team. Integrity is essential. A strong work ethic, curiosity, and self-motivation over time will win the day.

### Daily and Monthly Responsibilities

- Work with development teams and product managers to ideate software solutions
- Design client-side and server-side architecture
- Build the front-end of applications through appealing visual design
- Develop and manage well-functioning databases and applications
- Write effective APIs
- Test software to ensure responsiveness and efficiency
- Troubleshoot, debug and upgrade software
- Create security and data protection settings
- Build features and applications with a mobile responsive design
- Write technical documentation
- Work with data scientists and analysts to improve software

### Skills and Qualifications

- Strong knowledge of HTML, CSS, Javascript.
- Knowledge of React and common tools used in the wider React ecosystem, such as Node.js and npm.
- An understanding of common programming paradigms and fundamental React principles, such as React components, hooks, and the React lifecycle.
- Familiarity with common programming tools such as IDEs, RESTful APIs, Git repositories, TypeScript, version control software, and remote deployment tools
- Knowledge of of C# and .NET APIs (.NET 6 in particular)
- Proven experience as a Full Stack Developer or similar role
- Experience developing desktop and mobile applications
- Familiarity with common stacks (LAMP, MERN, etc.)
- Knowledge of multiple back-end languages (e.g. C#, Java, Python) and JavaScript frameworks (e.g. Angular, React, Node.js)
- Familiarity with databases (e.g. MySQL, MongoDB, CosmosDB), web servers (e.g.  NodeJS, Apache, Nginx) and UI/UX design

### Preferred Qualifications

- Bachelor’s degree in computer science, software development, engineering, or a related technical field
- Experience with Microsoft Azure

### Benefits

- Hybrid position: mostly in-office collaboration in Huntsville, AL, with occasional remote work / work-from-home opportunities and little to no travel
- Competitive salaries commensurate with education and experience
- Awesome, highly-flexible, work schedule and paid personal leave 
- Blue Cross Blue Shield health, dental, and vision options may be available

### NOTE TO RECRUITERS AND AGENCIES
While we greatly  respect the business models of third-party recruiters / agencies / consultancies, please respect our own model and do not waste time responding to this post. Our needs do not currently include referral or outsourcing arrangements nor are we interested in learning about new providers in this space. Such correspondence will be flagged as spam and blocked from future communication. Thank you.

### Contact
- Tony Hodgson:  thodgson(at)ethar.com
- Location: Huntsville, AL

**Comment by SimonBaey** [comment]
Wow it's me

**Comment by SimonBaey** [comment]
sure!!! no problem

**Comment by SimonBaey** [comment]
so when are you available?
