### ISSUE TITLE
Software Developer - JavaScript Programmer

### ISSUE THREAD

**Issue by cstoltz1** [tech256/jobs#113]
We are seeking a software developer for the development of software applications for Army Aviation flight performance planning. The developer will have direct communication with customers, stakeholders, and team members to help define software subcomponent requirements and will be responsible for successful on-schedule implementation of these requirements. The employee will perform development, testing, and integration of their efforts into the released system. 

Requirements:

BS or MS in Software Engineering, Computer Science, or related field
3+ years' JavaScript development experience
Experience with JavaScript Unit Testing frameworks
Knowledge with Agile Development process
Some experience/familiarity with object-oriented software development
Experience with current mission-planning software or Army Aviation is a plus
U.S. Citizenship required and must be able to obtain a DoD security clearance
Benefits

Nobletech Solutions offers competitve salaries and excellent employee benefits, including a company matching 401(k) safe harbor plan. We also offer an insurance package that includes medical, dental, and vision insurance. The company offers company paid life insurance and accidental death and dismemberment coverage to all full-time employees. Nobletech Solutions strives to being committed to the success of its employees and conducts two annual performance reviews, with both leading to a bonus and/or raise based upon performance and company goals.

About the Company

Nobletech Solutions Inc. is a Service-Disabled Veteran Owned Small Business (SDVOSB) and was founded with the vision to provide a unique synthesis of innovation, technical, and programmatic solutions in an ethical, professional, and cost effective manner. The company promises to remain focused on the customers' needs, requirements, and goals with an emphasis on responsiveness. The company provides a variety of services and solutions in Aviation and Software Engineering industries.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/667021-207062

**Comment by blmeadows** [comment]
@cstoltz1 is this still relevant?

**Comment by cstoltz1** [comment]
This position is no longer active.
