### ISSUE TITLE
Information Assurance Analyst

### ISSUE THREAD

**Issue by cstoltz1** [tech256/jobs#117]
Nobletech Solutions is seeking an Information Assurance Analyst to join our team of qualified diverse individuals to support our transition from DoD Information Assurance Certification and Accreditation Process (DIACAP) to Risk Management Framework (RMF). This position will be located in Huntsville, AL. The qualified applicant will have experience with tools such as Klockwork(c), Fortify, and Coverity(c) while supporting a team of professionals who are actively supporting Army programs.

As an Information Assurance Analyst, you will be responsible for the configuration, operation, and integration of hardware. Additionally, you will need to be familiar with and apply .Net STIGs, the Application and Development STIGs, Database STIGs in support of the Software Engineering Directorate (SED) in Huntsville, AL. The IA Analyst will adhere to Information Assurance and Risk Management Framework procedures to ensure government information systems (software applications) are compliant and protected against vulnerabilities.

Additionally, the IA Analyst will perform assessments of systems and networks and identify where those systems and networks deviate from acceptable configurations, achieved through passive evaluations such as compliance audits and active evaluations such as vulnerability assessments. You will interface with technical leads, software engineers, software testers, and other information security professionals needed to ensure a secure product is developed and delivered. You will develop and maintain documentation related to assessing and the authorization of the RAM Warn system.

Basic Qualifications

BS + 5 years' experience or MS + 3 years' experience (Degree in Information Systems, Computer Engineering, Computer Science, Cyber Security, or related field)
Working knowledge of DISA Security Technical Implementation Guides
Working knowledge of NIST 800-52 Risk Management Framework (RMF) security requirements
Working knowledge of computer and network security implementations and security test tools
Strong writing skills
Good interpersonal and communication skills
Certified Secure Software Lifecycle Professional (CSSLP), Certified Information Systems Security Professional (CISSP), or Security+ certifications (desired)
Strong understanding of DoD RMF and familiarity with DoD security compliance documents and Windows environments is highly desirable
Experience with VMware, ESXi, and/or OneSaf is desired
U.S. Citizenship required with ability to obtain DoD Security Clearance 
Benefits

Nobletech Solutions offers competitve salaries and excellent employee benefits, including a company matching 401(k) safe harbor plan. We also offer an insurance package that includes medical, dental, and vision insurance. The company offers company paid life insurance and accidental death and dismemberment coverage to all full-time employees. We have a flexible and optional 9/80 work schedule that allows employees to work a nine-hour day Monday through Thursday to take every other Friday off. Nobletech Solutions strives to being committed to the success of its employees and conducts two annual performance reviews, with both leading to a bonus and/or raise based upon performance and company goals.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/668095-207062

**Comment by blmeadows** [comment]
@cstoltz1 is this still relevant?

**Comment by cstoltz1** [comment]
This position is no longer active.
