### ISSUE TITLE
Aviation Subject Matter Expert (SME)

### ISSUE THREAD

**Issue by cstoltz1** [tech256/jobs#119]
Nobletech Solutions is seeking an Aviation Subject Matter Expert (SME) to be the resident expert on all aspects of flight performance and weight & balance mission planning with an in-depth knowledge in the use of the Performance Planning Card (PPC) and Form F weight and balance. The SME will support flight performance software development and test across multiple aircraft platforms on PC [MS Windows] and iPad [iOS]. 

Duties include:

    Making recommendations to the software's user interface, reviewing software design, and documentation.
    Performing demonstration of software for program/project management, new users, and customers.
    Researching authorized aircraft configurations and procedures, verifying the impact to performance (weight and drag), and software compliance within the Operators Manual (-10), Aircrew Training Manuals, and aircraft system SMEs.
    Ensuring product requirements are being tested from a user perspective with regards to accuracy in calculations, configuration and overall functionality.
    Writing and reviewing Quick Reference Guides and Readme documents to support delivery of the software product.
    Member of a mission planning and flight performance software team with the ability to work and coordinate with the program office, software developers, aero-engineers, and software test engineers.

Requirements:

    BS + 10 years' experience. Additional experience may be used as a substitute for BS degree.
    Army aviation and pilot experience on one or more of the Army's primary aircraft (UH-60, UH-72, CH47, AH-64, or C-12/RC12).  An TacOps, IP, or MTP identifier is a plus.
    Experience with Army Mission Planning System (AMPS) including IPAC, IPACX, PFPS, CFPS, FalconView and XPlan is highly desired. Understanding of Software Process is a plus, but not required.
    Candidate must be a US citizen and able to obtain a DoD security clearance.

Benefits

Nobletech Solutions offers competitve salaries and excellent employee benefits, including a company matching 401(k) safe harbor plan. We offer an insurance package that includes medical, dental, and vision insurance. The company offers company paid life and accidental death and dismemberment coverage to all full-time employees. We have a flexible and optional 9/80 work schedule that allows employees to take every other Friday off. Nobletech Solutions strives to being committed to the success of its employees and conducts two annual performance reviews, with both leading to a bonus and/or raise based upon performance and company goals.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/671019-207062

**Comment by blmeadows** [comment]
@cstoltz1 is this still relevant?

**Comment by cstoltz1** [comment]
This position is no longer active.
