### ISSUE TITLE
Web Developer / Designer

### ISSUE THREAD

**Issue by cstoltz1** [tech256/jobs#122]
Nobletech Solutions, Inc. is a based Service Disabled Veteran Owned Small Business based in Huntsville, AL. We are seeking a Web Developer / Designer to support new web and software development projects as well as applications management and support. The candidate must have a strong technical foundation as well as an understanding of coding standards, full life cycle systems development, and Agile methodology. The individual must be able to work effectively with other in-house developers, have strong communication skills, and should be able to present technical information to a wide range of audience.

Duties and Responsibilities:

Demonstrates a strong sense of ownership of applications and technical environments
Take on tasks and delivers in a timely fashion to meet schedule / milestone(s)
Guide development of tools, infrastructure, and processes within the structure
Provide expertise in determining the strategic technical direction and system architecture for projects
Provide support and/or mentoring to other developers and team members
Perform system and integration testing
Review current code, systems, and practices, and iteratively improve their quality and efficiency
Requirements:

BS degree in Computer Science or related field and 3 years' experience in web development
Proficiency in:
PHP experience
PHP best practices
Experience with PHP frameworks (Symfony in particular)
Full stack development experience
HTML, CSS, and JavaScript
Bootstrap
Model-View-Controller architecture understanding
MySQL experience
NetBeans development experience
Familiarity with Git
Experience with analysis, configuration, development, and delivery of customizations and solutions
Must be able to multi-task, manage details, and keep sight of overall objectives
Must be able to understand the complete deployment life cycle from design, build, test, and deployment
Experience with Agile development methodology is a plus
Preferred Qualifications:

Microsoft Azure deployment experience
Visual Code experience
Familiar with common web design patterns
REST or SOAP API development
Microsoft Team Services
Benefits

Nobletech Solutions offers competitive salaries and excellent employee benefits, including a company matching 401(k) safe harbor plan. We also offer an insurance package that includes medical, dental, and vision insurance. The company offers company paid life insurance and accidental death and dismemberment coverage to all full-time employees. We have a flexible and optional 9/80 work schedule that allows employees to work a nine-hour day Monday through Thursday to take every other Friday off. Nobletech Solutions strives to being committed to the success of its employees and conducts two annual performance reviews, with both leading to a bonus and/or raise based upon performance and company goals.

 

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/685244-207062

**Comment by blmeadows** [comment]
@cstoltz1 is this still relevant?

**Comment by cstoltz1** [comment]
This position is no longer active.
