### ISSUE TITLE
UX Designer

### ISSUE THREAD

**Issue by cstoltz1** [tech256/jobs#124]
Nobletech Solutions is seeking an experienced User Experience (UX) designer to support aviation mission flight planning. This role will identify business and user needs and translate them into relevant, elegant, and powerful experiences that cultivate engagement and adoption. They will conduct user research and communicate research insights and recommendations to stakeholders in a clear, compelling way. The UX Designer will also support the delivery of UX work within government and commercial sectors across product, service, and organizational levels.

Basic Requirements

    BA or BS in Computer Science or related field plus 3+ years of experience as a UX experience designer, interaction designer, information architect, or equivalent UX role
    Experience with creating and documenting information design concepts and solutions using various techniques, including wireframes, high fidelity prototypes, user journeys, and task flow diagrams
    Experience with the process for researching and creating the following UX artifacts: heuristic site review or usability evaluation, user and stakeholder interviews, personas and journey maps, process and task flows, sitemaps and navigation schemes, interactive prototypes, and client engagement / presentations
    Knowledge of best practices for information architecture and interaction disgn, user-centered design processes, and UX principles and techniques
    Knowledge of design principles, application and web-based technologies, C#, .net, HTML, CSS, Bootstrap, and Responsive Design
    Knowledge of prototyping software, including Axure and Sketch
    Knowledge of Section 508 Compliance and accessibility best practices
    Ability to comprehend clients' strategic objectives and provide effective consultative solutions
    US Citizenship and ability to obtain a security clearance

Additional Qualifications

    Experience in working effectively across a team of designers, developers, and data analysts
    Experience with conducting user research, usability evaluations, and testing
    Ability to display a successful track record with a variety of software development processes, including Agile, Waterfall, and Lean
    Ability to multi-task on multiple projects at a time
    Ability to work independently and define project objectives and milestones
    Excellent oral and written communication skills
    Excellent interpersonal and analytical skills
    Excellent technical problem-solving skills

Benefits

Nobletech Solutions offers competitive salaries and excellent employee benefits, including a company matching 401(k) plan. We offer an insurance package that includes medical, dental, life, and vision coverages. The company also has a flexible and optional 9/80 work schedule that allows employees to take every other Friday off.

 

Nobletech Solutions is an Equal Opportunity Employer. Employment decisions are made without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, disability, veteran status or other characteristics protected by law.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/687763-207062

**Comment by blmeadows** [comment]
@cstoltz1 is this still relevant?

**Comment by cstoltz1** [comment]
This position is no longer active.
