### ISSUE TITLE
Seeking Software Developers with Java, JavaScript, and HTML. 2+ years experience in Huntsville, AL

### ISSUE THREAD

**Issue by michaejohnson** [tech256/jobs#127]
# Hiring!

### About Position
Seeking software developers with 2+ years of Java, JavaScript, and HTML. Any experience with FOSS or commercial JavaScript frameworks would be a plus. Any experience with PHP or Software Testing would also be a plus. Candidates with an active security clearance will be given preference. Must be able to obtain security clearance.

### Contact
- michaejohnson@aerotek.com
- 256-890-2722

**Comment by blmeadows** [comment]
@michaejohnson is this still relevant?
