### ISSUE TITLE
Geospatial/Robotics Software Engineer - NuSpatial

### ISSUE THREAD

**Issue by iamvery** [tech256/jobs#13]
# Hiring!

## Geospatial/Robotics Software Engineer - NuSpatial

We are looking for a talented software engineer with extensive hands-on experience with sensor hardware and a background in geospatial mapping and perception.

This person will be responsible for the development and refinement of perception and navigation capabilities on our hardware.  They will work closely with operations engineers to integrate their solutions into the fielded systems.

Skills Required

* BS or MS in robotics or related discipline (Engineering, Physics, Computer Science, Mathematics)
* 5+ years of software engineering experience with C++. Python is a plus.
* Experience in sensing, mapping, and navigation systems based on laser, 3D time-of-flight, cameras, or inertial sensors

Nice to Haves

* Experience with algorithm development from academic papers
* Experience with the Robot Operating System (ROS)
* Experience with GPGPU/Parallel programming
* Experience with real time systems

Special Requirements

* Eligible for U.S. Security Clearance

All candidates must be legally authorized to work in the United States.  We do not sponsor visas.

NuSpatial does not use recruiters or pay recruiter fees.
### Contact
- Tech256: @mjcarroll
- http://nuspatial.com/careers
- Huntsville, AL

**Comment by iamvery** [comment]
ping @mjcarroll (want to keep it? reply "pong")

**Comment by mjcarroll** [comment]
pong

**Comment by iamvery** [comment]
@mjcarroll ping
