### ISSUE TITLE
DevOps / AWS Engineer

### ISSUE THREAD

**Issue by chris-sanders** [tech256/jobs#132]
# Hiring!

### About Position
DevOps Engineer/Amazon Web Services

Command Alkon brings innovative technologies and systems to the concrete, asphalt and building materials industry globally. Our technology helps our customers improve the efficiency and quality of the foundation of where we live, work and play.  What we do best is combining next-gen technologies with over 40 years of industry expertise.  We are not a “here today; gone tomorrow” software company, we will be here for a long time and a good foundation for your career…. like concrete.

The Role

The DevOps role is a MULTIFACETED role which works to develop highly available, highly automated, AWS Native Systems using the cloud’s latest best practices. You are a Luke Skywalker / Obi-Wan Kenobi and THRIVE in the latest technologies by utilizing AWS native PaaS offerings to power a new RESTful Microservice API foundation, as well as, numerous Single Page Applications running latest JavaScript frameworks. The team is composed of specialized and motivated engineers that are focused on creating the “Next Generation” platform for the company, from scratch.

What you’ll do

The Force is with you as you develop automated approaches for CI/CD pipeline and other systematic processes, document and maintain installation, provisioning, security and configuration procedures.
Assist development teams in code deployment and provisioning strategies and automation. Responsible for investigating and troubleshooting hardware, software and networking issues and failures.
Develop, document and maintain installation, provisioning, security and configuration procedures.
Investigating, troubleshooting hardware software, and networking issues and failures are your forte!
Develop, document, maintain, and instill machine and network security standards.
 
Who you are

You have a Bachelor’s or Masters in CS or related field with over 8 years of experience in DevOps Amazon Web services.
You are available in the future to provide “On Call” assistance as well as Tier III support.
You have a strong understanding of AWS services and tools and how they can be utilized
You have exposure to Terraform IaC Language and 2 to 4 years’ experience in bash or Ansible scripting.
You are familiar with Groovy and the following CI/CD tools:
Jenkins
Maven
Artifactory
SonarQube
Gitlab
You are an AMAZING communicator, focused on team collaboration, strong networking, security, agile background with a mission to minimize tech debt.

Perks

Cross-Functional Agile Scrum Teams with communities for practices for specialized skill sets
An opportunity to build the “Next Generation” platform from scratch
Learn the latest technologies from other specialized team members
 

More about Command Alkon

Command Alkon develops, markets, sales, implements and supports software and hardware products for heavy building contractors, haulers, and producers of aggregate, ready-mixed concrete, asphalt, cement and block. Whether 1 site or 1000 sites, our broad range of products allow our customers to manage all aspects of their business with one, fully integrated solution or as separate, individual pieces designed for specific business needs. Command Alkon products will help optimize business processes and provide the information that provides the quickest value, allows measuring results, and makes life easier.

Command Alkon strives to be an employer of choice, offering a comprehensive benefit package that includes:

Employee Recognition Programs
Casual dress code
Free soft drinks and hot beverages
Generous family medical and dental insurance plans
Company-paid life insurance, short term disability and long term disability insurance
Tuition Reimbursement Program

### Contact
- Tracy Todd Reid: treid@commandalkon.com
- Location: Birmingham, open to discussing Huntsville

**Comment by mjcarroll** [comment]
@chris-sanders is this still relevant?

**Comment by chris-sanders** [comment]
I'm not sure, but it's old enough at this point I think it should be closed so I'll do that.
