### ISSUE TITLE
Mid-Senior Level Software Development position [C++, HTML, SQL, Javascript, AngularJS]

### ISSUE THREAD

**Issue by AconiteDream** [tech256/jobs#136]
# Hiring!

### About Position
https://www.linkedin.com/jobs/cap/view/575219410/?pathWildcard=575219410&trk=mcm
Book System desires to fill a vacant software development position. Depending on the candidates, the position could be filled with a single senior level applicant or multiple less experienced ones. All the way down to a plethora of brand new coders. Well, not brand new. The requirement of the position is that you know how to code, either through your own projects at home and school, or through decades of development at various employers. The only requirement is that you know how to code. And hopefully well.

The position will be part of a team maintaining, enhancing, and (at times) rewriting software to support libraries and schools. You cannot ask for better customers than librarians and teachers. The main program is a C++ server with a HTML front and a SQL back. Several other programs as well, designed to enhance the main, like various apps for android and iOS.

We are a casual department, respecting time away from the company, and with an affinity for keeping their employees long term. On the flip side, the manager is also a software developer so knows about how long something Should take and wishes to be able support the thousands of customers using our software across all fifty states, and thirty countries beyond.

If it sounds interesting please contact us in the link provided. Have great day.

**Comment by mjcarroll** [comment]
@AconiteDream is this still relevant?

**Comment by AconiteDream** [comment]
Sorry, the position has been filled. Apologies, i think I should have made
sure to update on there the position had been filled several weeks ago.
