### ISSUE TITLE
Software Engineer-NASA MSFC

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#137]
Software Engineer

 

Cepeda Systems and Software Analysis, Inc. (CSSA) provides software engineering, systems engineering, and process improvement services for our customers. CSSA has achieved a rating of Capability Maturity Model Integration (CMMI) Level 2 for Services and CMMI Level 3 for Development. We have a 100% customer satisfaction rating and have won numerous awards at the local and national level. We treat one another with respect, foster collaboration while maintaining individual accountability, value multiple perspectives and diverse expertise, and encourage new ideas that surface throughout the organization. CSSA offers a comprehensive and competitive benefits package

 

Key Responsibilities:

Provide engineering analysis and support for the development and review of the Operational Maintenance Requirements Specification (OMRS) and Launch Commit Criteria (LCC) requirements.
Participate in development and verification of the Parametric Control File (PCF) and database maintenance.
Participate in technical meetings to provide status and support on-going activities
Ensure expected standards and requirements are appropriately implemented
Develop required engineering documentation and brief Engineering Boards
Participate in peer reviews
 

Qualifications:

Education:

B.S. in Computer Science, Computer Engineering, Software/Systems Engineering or related area from an accredited college or university
Experience:

One (1) to (5) years' experience as a software engineer/data analyst with software programming experience to support development, verification, and database maintenance of the Parametric Control File
Minimum of (5) years' experience in space flight operations and integration (such as pre-launch, launch countdown, flight operations, ground processing, space station, flight hardware test) to support development and review of Launch Commit Criteria and Operational Maintenance and Requirements
Ability to adapt quickly to obstacles and changing demands
Understanding of verification/validation terms and practices is preferred
Knowledge of Government standards and requirements is preferred
Understanding of the software development lifecycle activities is preferred
Knowledge/Skills:

Must have working knowledge of Operational Maintenance and Requirements for space flight systems
Must have working knowledge of Launch Commit Criteria for space flight systems
Ability to evaluate status and make recommendations for improvements
Interface with customers to understand needs and communicate requirements
Self-motivated and work well independently
Customer-focused, service-based approach to daily responsibilities
Knowledge of engineering technical terms
Must be a self-starter who knows how/where to go find answers
Ability to organize and gather technical information and summarize into the appropriate technical documentation
Success-oriented, resourceful, confident individual who effectively applies lessons learned
Team skills to facilitate software engineering activities and quickly resolve issues
Knowledge of engineering best practices and ability to analyze data to solve problems is preferred
Team player with understanding of team dynamics and ability to thrive in a fast-paced environment is preferred
 

U.S. Citizenship Required

 

CSSA is an Equal Employment Opportunity Employer. We do not discriminate in the employment of individuals on the basis of race, color, sex (or pregnancy), religion, age, national origin, disability, veteran status, sexual orientation, gender identity, genetic information, or any other protected category. CSSA hires and promotes individuals solely on the basis of their qualifications for the job to be filled. If you require assistance with the application process, please contact us at careers@cepedasystems.com. We appreciate your interest in our organization.

 

CSSA participates in the E-Verify program.

Criminal background checks are conducted on all applicants before hire. 

CSSA is a Drug Free Workplace.

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/716446-194689

**Comment by mjcarroll** [comment]
@CSSA-HR is this still relevant?
