### ISSUE TITLE
Mid to Senior-Level Software Tester

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#138]
Software Tester

 

Cepeda Systems and Software Analysis, Inc. (CSSA) provides software engineering, systems engineering, and process improvement services for our customers. CSSA has achieved a rating of Capability Maturity Model Integration (CMMI) Level 2 for Services and CMMI Level 3 for Development. We have a 100% customer satisfaction rating and have won numerous awards at the local and national level. We treat one another with respect, foster collaboration while maintaining individual accountability, value multiple perspectives and diverse expertise, and encourage new ideas that surface throughout the organization. CSSA offers a comprehensive and competitive benefits package.

 

Key Responsibilities:

Perform as a Software Tester in a team responsible for testing and evaluating simulations to ensure the software performs correctly for its intended use. The responsibilities include but are not limited to:

Reviewing software requirements
Preparing/reviewing test cases
Preparing/reviewing test procedures
Conducting software test and data analysis
Evaluating test results reporting software defects, and generating test reports
 

Qualifications:

Education:

BS Degree in Engineering or Computer Science
Experience:

A minimum of 10 years of software test experience at the unit, integration, and system test levels
Comprehensive experience performing analysis, design, and test
Experience developing Test Plans, Test Procedures, and Test Reports
Linux/Unix experience is preferred
Experience with software development (JAVA, C, and C++) is preferred
Knowledge/Skills:

Candidate should be a fast learner who can quickly ascertain the expected software functionality and utilize this knowledge to develop a comprehensive testing approach
Requires excellent troubleshooting and critical thinking skills with an ability to independently analyze configurations and system behaviors via output data and/or review of applicable software source code
Candidate should possess the ability to multi-task in a fast-paced testing environment, while working collaboratively with internal and external stakeholders
Requires strong verbal and written communication skills with the ability to clearly describe issues to both the software development team and technical leadership
Candidate should possess the ability to complete tasks on time and in compliance with AS9100 and CMMI level processes/procedures
Familiarity with the application standardized message sets used in the BMDS community is desirable, but not required
 

U.S. Citizenship Required

Candidate must have an active Secret security clearance

 

CSSA is an Equal Employment Opportunity Employer. We do not discriminate in the employment of individuals on the basis of race, color, sex (or pregnancy), religion, age, national origin, disability, veteran status, sexual orientation, gender identity, genetic information, or any other protected category. CSSA hires and promotes individuals solely on the basis of their qualifications for the job to be filled. If you require assistance with the application process, please contact us at careers@cepedasystems.com. We appreciate your interest in our organization.

 

CSSA participates in the E-Verify program.

Criminal background checks are conducted on all applicants before hire. 

CSSA is a Drug Free Workplace.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/718105-194689

**Comment by mjcarroll** [comment]
@CSSA-HR is this still relevant?
