### ISSUE TITLE
JavaScript Software Developer

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#140]
JavaScript Software Developer

 

Cepeda Systems and Software Analysis, Inc. (CSSA) provides software engineering, systems engineering, and process improvement services for our customers. CSSA has achieved a rating of Capability Maturity Model Integration (CMMI) Level 2 for Services and CMMI Level 3 for Development. We have a 100% customer satisfaction rating and have won numerous awards at the local and national level. We treat one another with respect, foster collaboration while maintaining individual accountability, value multiple perspectives and diverse expertise, and encourage new ideas that surface throughout the organization. CSSA offers a comprehensive and competitive benefits package.

 

Key Responsibilities:

Perform software development in Java and Javascript (Angular)
Work independently and as part of a team developing, testing, and debugging new and existing Angular JavaScript applications
Follow established processes and procedures
 

Qualifications:

Education:

B.S. in Computer Science, Computer Engineering, Software Engineering, MIS, or related discipline
Experience:

A minimum of 1 year of JavaScript coding including ability to use Angular frameworks
2 to 8 years of software development with 1 year using Java
Proficient at trouble-shooting and debugging is a plus
Experience with Oracle or SQL is a plus
Knowledge/Skills:

Candidate should possess the ability to multi-task in a fast-paced testing environment, while working collaboratively with internal and external stakeholders
Requires strong verbal and written communication skills
Candidate must be organized and detail oriented
Candidate must possess problem solving and analytical skills
Candidate must have the ability to work in team environments as well as individually
Ability to adapt to changing situations and requirements
Being comfortable with different language syntaxes is a plus
U.S. Citizenship is required

Candidate must hold active Secret security clearance

 

CSSA is an Equal Employment Opportunity Employer. We do not discriminate in the employment of individuals on the basis of race, color, sex (or pregnancy), religion, age, national origin, disability, veteran status, sexual orientation, gender identity, genetic information, or any other protected category. CSSA hires and promotes individuals solely on the basis of their qualifications for the job to be filled. If you require assistance with the application process, please contact us at careers@cepedasystems.com. We appreciate your interest in our organization.

 

CSSA participates in the E-Verify program.

Criminal background checks are conducted on all applicants before hire. 

CSSA is a Drug Free Workplace.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/718219-194689

**Comment by mjcarroll** [comment]
@CSSA-HR Is this still relevant?
