### ISSUE TITLE
Senior Software Engineer (#824218)

### ISSUE THREAD

**Issue by CkingPT2018** [tech256/jobs#158]
# Hiring!
PeopleTec is currently seeking a Senior Software Engineer to support our Boulder, CO location.

Candidate will design, develop, and test software solutions in support of Space Based Infrared System (SBIRS) ground system software, supporting multiple baselines in defect resolution as well as enhancements, special projects, new business initiatives, and modernization efforts. The candidate will work in a team environment, potentially supporting multiple projects. In this role the candidate will design, code, integrate and resolve problems in software. The ideal candidate should have software development education and experience in C++, development using the Qt framework (GUI design & development), pub/sub messaging, SQL, Java, Object Oriented Design and how it applies in a distributed system, and familiarity with the full software development cycle. Knowledge of HW-SW interfaces, including SNMP is ideal. The candidate should be familiar working in Linux/unix environments in the command line interface, and associated IDEs. Candidate should be a self-starter and have demonstrated communication skills. This position is expected to work with diverse disciplines in a team environment to reach a common goal.

 

Required Skills/Experience:

Significant software development experience in C++
Must speak to recent experience (on day 1) with Test Automation (Chef is a plus)
Experience developing in Linux/Unix environments in a command line interface Significant experience with Object Oriented Design and how it applies in a distributed system
Experience with SQL and understanding of relational databases
Significant experience in software development methodology, lifecycle and process (waterfall is a must, agile is a plus)
Experience with ClearCase/ClearQuest or other version control systems (GIT is a plus)
Proven written and verbal communication skills 
Travel: 5%
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A completed Bachelor's Degree in Computer Science, Math, Engineering, or related discipline with 12+ years of experience, OR a completed Master's Degree in Computer Science, Math, Engineering, or related discipline with 10+ years of experience.

 

Desired Skills:

Experience in Space ground systems Experience in SBIRS SW
Experience with Java Familiarity with JavaScript and C# Familiarity with Qt Framework for GUI design & development
Familiarity with pub/sub messaging (function & process)
Knowledge of HW-SW interfaces, including SNMP
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/824218-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
