### ISSUE TITLE
Senior Systems IAMD Subject Matter Expert (#605296)

### ISSUE THREAD

**Issue by CkingPT2018** [tech256/jobs#160]
PeopleTec is currently seeking a Senior Systems IAMD Subject Matter Expert to support our Huntsville, AL location.

The Senior System IAMD Subject Matter Expert will work as a member of the Army Program Executive Office Missiles and Space (PEO M&S) Integrated Air and Missile Defense (IAMD) Project Office team to develop, decompose, and analyze system requirements in support of the IAMD mission.

 The ideal candidate will:

    Perform evaluation and optimization of existing requirements and algorithms in the tactical, net-centric AMD environment.
    Prototype subject matter expertise to lead performance assessment; provide guidance to developers; and support verification and validation of design.
    Engage in system-level engineering, sub-system element integration, schedule reviews, interoperability analyses, engineering reviews, engineering document development, engineering analyses and assessments and technology readiness assessments.
    Provide guidance to system-level engineering analysis and assessment of missile defense system architectures, designs, and performance.
    Technical briefings to leadership on recommended courses of action, trade studies, system design, performance and impacts to the mission.

 

Required Skills/Experience:

    Must be familiar with AMD concepts with specific system engineering knowledge and experience with one (1) or more of the following systems: IBCS, PATRIOT, THAAD, C2BMC, or AEGIS.
    Must have experience in requirements analysis, performance analysis, and verification of two (2) or more of the following AMD areas: track management, threat evaluation, engagement processing, IFF, CCDTI, counter ARM, jammers and jam strobe processing, Non-Cooperative Target Recognition, geodetic registration, automatic emplacement, defense plan evaluation and optimization, sensor coverage evaluation and optimization, and tactical distributed systems.
    Must be experienced analyzing and decomposing requirements, be fluent in the Microsoft Office toolset, be proficient navigating and extracting data from requirements databases and modeling tools, and be proficient with at least one scripting or programming tool to assist in requirements, architecture development and performance analysis tasks.
    Experience with MagicDraw, Rhapsody and/or other UML modeling tools is desired.
    Experience with DOORS is desired.
    Must be a U.S. Citizen.
    A Secret clearance is required to perform this work.  Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this clearance level during their employment.

 

Education Requirements:

A completed Bachelor's Degree in Engineering with a minimum of 10 years combined Government/DoD experience in performing the essential duties listed.

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/605296-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
