### ISSUE TITLE
Cognitive Performance Coach (CPC) (#830775)

### ISSUE THREAD

**Issue by CkingPT2018** [tech256/jobs#162]
PeopleTec is currently seeking a Cognitive Performance Coach (CPC) to support our Huntsville, AL (other U.S locations are TBD) location.

PeopleTec is seeking a Cognitive Performance Coach (CPC) to support the Cognitive Enhancement Performance Program (CEPP) at multiple locations. CPCs teach performance enhancement techniques to service members and civilians. Teaching is conducted in group and individual settings and includes general education in human performance. The teaching specifically focuses on personalized training about how to acquire and apply specific mental skills and techniques that cultivate the mental and emotional strength necessary to thrive in an era of overwhelming demands and persistent conflict. Using these principles, CPCs help service members to become high performing "tactical athletes" and help foster high performing "unit teams" in preparation for, during, and following combat operations. Specifically, CPCs teach performance psychology to further promote excellence and efficiency during physical, technical, and tactical training, as well as during the challenges of combat operations.

 

Tasks, responsibilities, and additional duties:

    Attend training exercises and field operations as requested by individual units to serve as a performance enhancement consultant and to coach service Members and leaders on the acquisition of performance psychology techniques and their application to individual military tasks and unit operations
    Provide tailored educational programs and workshops to help civilians living and working in demanding environments
    achieve success and accomplish personal, professional, and family goals
    Recommend improvements to all aspects of CEPP operations.
    Perform routine CEPP operational duties
    Conduct assessment, assist in program evaluation, and support research projects being conducted locally
    Assist or provide CEPP program overview briefings to VIPs and high-ranking leaders when required
    Develop and maintain professional development relating to all aspects of performance enhancement, academic proficiency, and military- related knowledge
    Perform additional duties as required

Required Skills/Experience:

    Experience working with adult clients developing performance enhancement skills, education, and training for physical or motor performance
    Excellent oral and written communication skills
    Experience teaching large, small, and individual audiences; ability to work well within a team environment
    1-6 years' experience with Performance Enhancement Skills Training
    Experience with human performance, collective training, training development, and training education
    Travel: 10%
    Must be a U.S. Citizen
    Candidates are required to be able to obtain a Secret clearance upon hire, and the ability to maintain this level of clearance during their employment

 

Education Requirements:

A completed masters or doctoral degree from an accredited college or university in the field of psychology, counseling, or kinesiology with a specialized emphasis in sport and/or performance psychology.

 

Desired Skills:

Familiarity with biofeedback techniques, military environment, and resilience training.

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/830775-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
