### ISSUE TITLE
Forensic Accountant (FBI Counterintelligence Division)(#833228*)

### ISSUE THREAD

**Issue by CkingPT2018** [tech256/jobs#163]
PeopleTec is currently seeking a Forensic Accountant (FBI Counterintelligence Division) to support our Washington, DC location.

The Candidate shall conduct thorough forensic financial analysis of business and personal records and develop financial profiles of individuals or groups identified as participating in suspicious or illegal activity. The Candidate shall assist investigators in preparing documents for use as evidence in investigations. The Candidate shall identify and trace funding sources and interrelated transactions. The Candidate shall compile findings and conclusions into financial investigative reports. The Candidate shall meet and participate on teams with Special Agents and Intelligence Analysts. The Candidate shall provide assistance with operational initiatives with a financial nexus.  Candidate tasks shall include, but not limited to, the following:

Provide accounting expertise to litigation and investigative support.
Perform forensic research to trace funds and identify assets.
Prepare forensic accounting reports from financial findings.
Prepare analytic data for litigation.
Analyze financial information to investigate possible financial crimes.
Identify and detect destroyed or tampered information within financial data.
Identify fiscal behavior traits of those who commit crime.
Identify, examine, and analyze financial data associated with domestic/international CI jurisdictional violations to individuals and organizations through which an enterprise operates.
Analyze investigative findings to extract information of financial relevance to a case and/or initiative.
Work with other USIC agencies, if applicable, on parallel investigations.
Provide Special Agents and Intelligence Analysts with a basis and language to subpoena financial records.
Recognize the need for National Security Letters, its proper use during investigations, and provide Special Agents and Intelligence Analysts with the appropriate language to meet legal standards.
Provide authoritative expertise with regard to accounting and financial practices, world-wide securities, banking laws and systems, conventional and non-conventional financial institutions, national and international profit and non-profit businesses.
Define and identify the nature of allegations analyzed.
Assesses the value of various types of financial evidence and recommends sources and methods for obtaining evidence.
Identify unusual financial pathways and associations and conducts traces of highly-complex, sophisticated, convoluted, and obscure transactions and interrelationships.
Interpret implications on a vast number and variety of financial transactions, and other corporate, business, and financial processes, associations, and record-keeping systems.
Reconstruct business -records to identify funding sources and circuitous series of interrelated transactions.
Unravel highly sophisticated techniques for moving funds, shielding illegal activity, and disguising identities of individuals or groups involved.
Analyze mechanisms and indicators and deduces their contribution to planning, fund-raising, and operations. This includes financial matters directly connected to CI, criminal and/or terrorist acts or conspiracies conducted by individuals and groups involved in business corporations, securities, banking and/or charitable fundraising, as well as those of legitimate business associates who may be unwitting contributors.
Provide financial profile of individuals and/or groups identified in the participation of suspicious/illegal financial activity.
Identify new forensic accounting techniques which are applicable to various financial investigations ranging from domestic/international white collar crime, counterterrorism, CI, cyber crime, and/or other FBI jurisdictional violations.
Utilize standardized forensic accounting workpapers for use in investigations and prepare financial reports based on investigative findings.
Develop workpapers using computer applications, to include but not limited to, Microsoft Excel, Microsoft Access, document management software, and/or other forensic accounting tools.
Convert/utilize data from forensic accounting analysis to prepare investigative reports.
Use a variety of analytical tools such as statistical/analytical computer software and database management systems for a more in-depth examination of entities involved with identified financial transactions.
Compile extremely complex financial findings and conclusions to prepare in-depth forensic accounting reports and communications.
Develop detailed technical forensic accounting oral presentations and briefings for varied audiences.
Prepare charts and documentation for use in trials and/or criminal proceedings, as needed.
Provide guidance regarding techniques/methods used to conduct analysis of financial evidence/data.
Develop methods and techniques for gaining access to and examination of financial records, information, and transactions.
Utilize commercial and USIC resources to keep abreast of the latest methods and techniques for conducting sophisticated financial investigations.
Maintain contacts and exchange ideas with experts in private industry and other government agencies.
 

Required Skills/Experience:

The Candidate shall conduct thorough forensic financial analysis of business and personal records and develop financial profiles of individuals or groups identified as participating in suspicious or illegal activity.  The Candidate shall assist investigators in preparing documents for use as evidence in investigations.  The Candidate shall identify and trace funding sources and interrelated transactions.  The Candidate shall compile findings and conclusions into financial investigative reports.  The Candidate shall meet and participate on teams with Special Agents and Intelligence Analysts.  The Candidate shall provide assistance with operational initiatives with a financial nexus.

A minimum of 6+ years of applicable experience working within the defense, intelligence, or law enforcement communities leading or coordinating complex programs and/or multiple projects.
Knowledge, skills, and abilities related to white collar crime; money laundering; insurance claims; generally-accepted accounting principle violations; telemarketing fraud; check kiting; contract and procurement fraud; asset misappropriation; securities fraud; financial statement fraud; bankruptcy fraud; credit card fraud; embezzlement; evidence integrity analysis; damage assessment; tracing illicit funds; locating hidden assets; forensic intelligence gathering; and/or regression analysis.
Mastery of accounting and financial analytical theories, innovations, practices and principles to include an in-depth understanding of funding mechanisms, processes, and legal titles associated with domestic and international banking, monetary transfers, corporate and charitable finances, securities, and money markets.
Expert knowledge of business and government organizational and managerial structures and practices, and their financial documentation practices, as well as various sophisticated finance and accounting systems, methods, and techniques.
Advanced ability to conduct quantitative and qualitative analyses, to apply various statistical methods and formulas, to discern and unravel complex interrelationships, to recognize concealed or obscure associations, and to draw logical inferences and conclusions significant for evidentiary purposes.
Broad practical knowledge of criminal statutes, regulations, procedures, violations, and jurisdictions with respect to national and international financial investigations, as well as processes and practices for subpoenas, National Security Letters, affidavits, execution of search warrants, rules of evidence, chain of custody, and other judicial/legal proceedings.
Ability to use computer hardware and software as tools for gathering and analyzing financial information, conducting analyses, managing investigative cases, and facilitating office operations, to include data base management systems, statistical analytical software, Internet research techniques and information resources, office automation (spreadsheets, desktop publishing, BankScan etc.), and electronic mail systems.
Written and oral communications skills, including ability to translate complex and interrelated information into articulate presentations, compose substantive analytical reports, interact effectively as a member of a multijurisdictional investigative team, elicit information, and develop cooperative relationships with international and/or domestic banking, financial and law enforcement officials.
Travel: 
Must be a U.S. Citizen
An active DoD Top Secret clearance is required to perform this work. Candidates are required to have an active Top Secret clearance upon hire, and the ability to maintain this level of clearance during their employment. (Current CI polygraph preferred)
Must be able to pass CI polygraph
 

 Education Requirements:

A Bachelor's in forensic accounting, accounting, finance, or a related field for forensic accountants (Master's Degree preferred).

 

Desired Skills:

Certified Fraud Examiner
Certified Public Accountant
Certified Internal Auditor
Chartered Accountant
 

  ***This opportunity is contingent upon a contract award to PeopleTec*** 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/833228-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
