### ISSUE TITLE
Systems Engineer (Avionics)(#756637)

### ISSUE THREAD

**Issue by CkingPT2018** [tech256/jobs#165]
PeopleTec is currently seeking a Systems Engineer support our Huntsville, AL location.

Candidate will provide system engineering expertise focused in avionics and vision based sensor systems in support of an Army Aviation S&T activity. The candidate will support traditional system engineering tasks including system requirements and architectural analysis. The candidate will work as part of a team developing model based system engineering (MBSE) products including systems models in SysML.

 

Required Skills/Experience:

Candidate should have 10+ years' engineering experience in avionics, sensor based systems, and other software intensive complex system and a minimum of 5 years in systems engineering experience.
Experience with customer requirements elicitation, capture and documentation.
Understanding of system requirements decomposition and the creation of mechanical, electrical, and software performance and reliability specifications.
Experience generating and tracing requirements in a requirements management tool. Working knowledge of DOORS preferred. Experience with model based systems engineering (MBSE) with SysML.
Working knowledge of MBSE tools such as MagicDraw, Rhapsody, or Enterprise Architect. Understanding of avionics systems with experience developing, testing and/or troubleshooting hardware and software.
Possesses in-depth practical and theoretical technical engineering knowledge.
Capable of working independently, as a team member, or leading tasks to solve engineering and scientific problems within a research and development environment.
Proven ability to effectively communicate by verbal and written methods to include face-to-face, phone, briefs, emails, information papers, white papers, executive summaries, agendas, minutes, plans, and reports
Travel: 10%
Must be a U.S. Citizen
A Secret clearance is required to perform this work.  Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A completed Bachelor's Degree in Engineering, Computer Science, or Mathematics is required. 

 

Desired Skills:

Experience developing avionics for military rotorcraft.
Experience with the Army and/or civil airworthiness processes for rotorcraft avionics.
Knowledge of vision based sensor systems, sensor fusion and/or display fusion.
Experience in systems engineering simulation.
Experience designing and developing software.
Understanding of open systems architecture concepts.
Demonstrated abilities in complex electronics troubleshooting including a working knowledge of common electrical and data interfaces applicable in aviation
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/756637-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
