### ISSUE TITLE
EIT Threat Generation Engineer (#838199)

### ISSUE THREAD

**Issue by CkingPT2018** [tech256/jobs#166]
PeopleTec is currently seeking an EIT Threat Generation Engineer to support our Huntsville, AL location.

Candidate will provide Systems Engineering expertise; conduct engineering reviews and develop detailed target requirements for the Missile Defense Agency Director of Threat Systems Engineering (MDA/EIT). This position will support MDA/EIT Targets in requirements definition and compliance assessments. Target requirements include aspects of target performance such as exercising trajectory or signature, to include RF and IR, parameter space identified to be of interest by either elements under test or representative of agency needs. Assessment against requirements will be performed relative to intermediate and finalized target solutions. The candidate must possess technical and communication skills needed to effectively execute the mission and be able to respond to customer needs in a timely manner.

Support MDA/DE/I/EIT Team General Duties:

Perform support of intelligence based threat system performance.
Prepare technical presentations for the engineering team and EIT Director.
Lead and support technical meetings, provide input and meeting synopsis.
Analyze reference data to aid in requirements definition and compliance assessment.
Develop tools to aid in data analysis and presentation .
Develop briefings suitable for explaining design decisions and calculations to external teams and elements.
Develop and maintain software to perform duties.
Develop Preliminary and Critical Target Requirement Review (PTRR and CTRR) documentation per the MDA Instruction 5000.06-INS Process.
Coordinate the required objective evidence and ascertain the entry and exit criteria have been met for the review. Develop the Target Trajectory Memorandum (TTM) as a product of the review process.
After delivery of flight test target trajectories, develop Target Assessment and Certification Reports (TACRs) in support of Flight Test documentation for approval by the Director of Engineering (DE).
Support the weekly Target Requirements Working Group, providing meeting support and technical recommendations to EIT Leadership.
 

Required Skills/Experience:

Capability to perform analysis of performance of complex systems Experience with Microsoft Office suite of applications.
Strong communications skills.
Experience in RF signature generation & assessment to include processing XPATCH output files.
Experience in IR signature generation & assessment to include executing and processing Optical Signatures Code (OSC).
Experience in trajectory analysis to include working in different coordinate frames, endo- and exo-atmospheric behavior, and identifying key trajectory parameters.
Experience in MATLAB; other scripting languages such as Python are preferred as well.
Capable of generating and delivering briefings to external teams and management effectively.
The candidate must be able to work within a collaborative environment composed of Government, Prime Contractor and other employees.
Travel: 5-10%
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A completed Bachelor's Degree in Engineering, Mathematics, Computer Science, Physics or related field and 7+ years of experience.  (Master's Degree with 10+ years of experience preferred)

 

Desired Skills:

Experience coordinating, briefing, and writing target flight performance, Radar Cross Section (RCS), and Infrared signature requirements used for the build, modification, and mission preparation of targets for flight test execution.
Understanding of kinematics, radar cross section and infrared data and software that supports the production of this data.
Understanding of plume stitching software Understanding of C/C++, CSS, Fortran, HTML, Java, Visual Basic, XML programming.
Familiarity with Missile Defense Agency and Ballistic Missile Defense System. MDA or military experience is a plus.
Understanding of the MDA Engineering practices and processes.
Familiarity with the BMDS system level documentation, such as the BMD System Description Document and BMD System Specification Applied System Engineering certification and Model and Simulation certification.
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/838199-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
