### ISSUE TITLE
Information Assurance Officer / System Administrator (#844408)

### ISSUE THREAD

**Issue by CkingPT2018** [tech256/jobs#169]
# Hiring!

## [Acme, Inc.](hPeopleTec is currently seeking an Information Assurance Officer / System Administrator to support our Huntsville, AL location.

Primary responsibilities would include information assurance, network administration and system configuration and monitoring. Coordination with development engineers, network users and command system administration, and senior and junior information assurance team members is required. This program requires excellent technical domain knowledge.

 

Required Skills/Experience:

Minimum of 5+ years of related work experience 
Candidate must display and demonstrate knowledge of the Department of Defense Risk Management Framework (RMF) policies and procedures
Candidate must display and demonstrate knowledge of network configuration, setup and monitoring
Network +, Security + and A+ certifications are required
Significant experience as a Linux system / network administrator is desired
Advanced certifications such as Certified Ethical Hacker are desired
Travel: 0%
Must be a U.S. Citizen
An active DoD Top Secret/SCI clearance is required to perform this work. Candidates are required to have an active Top Secret/SCI clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A completed Bachelor's Degree in a related field and a minimum of 5 years of related experience is required (Armed Forces active duty experience accepted).

 

Physical Requirements:

Requires ability to lift up to 20 lbs. 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/844408-305157	
ttps://en.wikipedia.org/wiki/Acme_Corporation)

### About Position
Seeking comically large firework tester. Experience with flightless birds a plus.

### Contact
- Tech256: (at)acmebob
- Twitter: (at)acme
- Location: Anywhere
- etc...

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
