### ISSUE TITLE
Seeking Java Developers - Patel Technologies 

### ISSUE THREAD

**Issue by patels** [tech256/jobs#18]
# Seeking Java Developers - all levels of experience, multiple positions

### About Position
Patel Technologies is seeking qualified Java developers with basic, intermediate, and advanced experience.   We are seeking candidates to support capable of developing in the Android Computing Environment in support of the Army’s Joint Battle Command-Platform (JBC-P) and serves to provide situational awareness to Soldiers.

Full listing and more details here:
http://pateltechnologies.com/careers/

### Contact
- sandy.patel@pateltechnologies.com
- Location: Huntsville, AL

**Comment by iamvery** [comment]
ping @patels (want to keep this? reply "pong" if so)

**Comment by iamvery** [comment]
Pinging @patels on 256 for status. Will close :soon: if I receive no response. Happy to reopen if it's still a thing 😄

**Comment by patels** [comment]
thanks @iamvery. I'll close it. I'll reopen if needed.
