### ISSUE TITLE
Unnamed Company - Web Developer

### ISSUE THREAD

**Issue by mjcarroll** [tech256/jobs#19]
# Hiring!

### About Position

We're finally getting a better understanding of the type of person that we need.  If you can help us find someone, that would be awesome!

At this point, the position is for part time work, but could develop into more later.  We also need this person to be self-motivated and self-directed.

o Experience working and developing on Ubuntu (linux) operating system and environment
o Experience installing, configuring, and developing with Tomcat Apache HTTP server
o Experience developing with Javascript
o Experience installing, configuring, operating, and developing with a SQL Database (e.g. MySQL)
o Experience developing with Java Server Pages
o Experience developing with and using Java SQL queries
o Experience working with XSLT and XML
o Experience developing test software for JSP and java HTTP based apps.
o Experience using Ansible provisioning tools
o Experience with AWS
o Able to write and interpret UML diagrams used for documentation purposes
o Self motivated and self directed.
o Willing to work Part Time 

### Contact
- Tech256: @mjcarroll
- E-mail: michael@nuspatial.com
- Location: Huntsville, AL

**Comment by iamvery** [comment]
ping @mjcarroll

**Comment by mjcarroll** [comment]
I think we're covered for now! Closing!
