### ISSUE TITLE
Neutron Developer (#886253)

### ISSUE THREAD

**Issue by CkingPT2018** [tech256/jobs#192]
PeopleTec is currently seeking a Neutron Developer to support our Fort Gordon, GA location.  Candidate also has the ability to work from a remote location. 

This requirement is to provide the U.S. Army Cyber School with (1) qualified Neutron Developer to include but not limited to support in the following disciplines: Systems Development, OpenStack, Network Security, System Administration, and Network Administration to design, build, and support the Virtual Training Area (VTA). The Neutron Developer will be tasked with extending the functionality of and fixing bugs in the OpenStack Neutron project. All completed work will be committed back upstream.

 

Required Skills/Experience:

    At contract start date possess a Single Scope Background Investigation (SSBI) and TS with SCI eligibility and maintain the required security clearance throughout the life of the contract.
    Must have at least 5 years of python software development experience.
    Must have 3 years of experience contributing to an OpenStack project, or another large open-source project with a diverse community of contributors.
    Must have the ability to collaborate with others when contributing to the neutron project.
    Must be comfortable with the concept of software defined networking, particularly as related to functionalities within neutron.
    Must be proficient in python to the extent required to debug issues inside of neutron, develop patches, and contribute the fixes upstream.
    Must be willing and able to extend the functionality of neutron IAW the direction of the PTL.
    Must be willing to contribute 100% of written code back upstream. Must be willing to travel to and participate in OpenStack Summits worldwide.
    Must be familiar with DevOps business practices.
    Must be familiar with the git version control system.
    Must speak English.
    Must participate in meetings, mailing lists, and other collaborative environments that are relevant to the neutron project.
    Must be able to conduct code reviews, draft design documents, lead and participate in design discussions, and assist the Cyber School operations team with resolving any issues that arise in the usage of neutron.
    Travel: 20%
    Must be a U.S. Citizen
    An active DoD Top Secret/SCI (or Top Secret with SCI eligibility) clearance is required to perform this work. Candidates are required to have an active Top Secret/SCI (or Top Secret with SCI eligibility) clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A completed Bachelor's Degree in a related field is preferred, experience may be substituted in lieu of degree.

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/886253-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
