### ISSUE TITLE
Software Engineer (Army Systems) (#888696)

### ISSUE THREAD

**Issue by CkingPT2018** [tech256/jobs#197]
PeopleTec is currently seeking a Software Engineer to support our Huntsville, AL location.

The candidate will provide software engineering expertise to a research and development group investigating human systems interfaces for Army aviation, ground vehicles and weapon systems. The candidate will work with research scientists, graduate students and other engineers in a collaborative research environment. The primary responsibility of the candidate will be software development of graphics applications which enable evaluation of alternative visual interfaces for human operators.

 

Required Skills/Experience:

    8+ years software engineering experience
    Experience developing software with OpenGL, C++, and C, C#, and Java in Visual Studio
    2D and 3D graphics software design and development
    Experience interfacing with 6 DOF simulation applications desirable
    Development with 3D game engines such as Unity and VBS desirable
    Experience developing software for Virtual Reality (VR) applications desirable
    Familiarity with avionics display graphics design and rotorcraft systems desirable
    Knowledge of agile development processes is desirable
    Creating software requirements, design, interface and test documentation desirable
    Working in a research and development laboratory environment desirable
    Demonstrated self-starter with strong interpersonal communications skills and ability to work across geographically diverse groups
    Ability to successfully complete tasks with minimal direction both working as a individual contributor as well as a team member
    Travel: 15%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A completed Bachelor's Degree in Computer Science, Engineering or Mathematics is required.

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/888696-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
