### ISSUE TITLE
Software Engineer (#889567)

### ISSUE THREAD

**Issue by CkingPT2018** [tech256/jobs#198]
PeopleTec, a 100% employee owned company, is currently seeking a Software Engineer to support our Boulder, CO operations.

Candidate will design, develop, and test software solutions in support of Space Based Infrared System (SBIRS) ground system software, supporting multiple baselines in defect resolution as well as enhancements, special projects, new business initiatives, and modernization efforts. The candidate will work in a team environment, potentially supporting multiple projects. In this role the candidate will design, code, integrate and resolve problems in software. The ideal candidate should have software development education and experience in C++, Object Oriented Design, and familiarity with the full software development cycle. The candidate should be familiar working in Linux/Unix environments and associated IDEs. The Software Engineer should be a self-starter and have demonstrated communication skills. This position is expected to work with diverse disciplines in a team environment to reach a common goal.n.

 

Required Skills/Experience:

Significant software development experience in C++.
Experience developing in Linux environments and/or Windows environments.
Significant experience in SW development methodology, lifecycle and process (waterfall is a must, agile is a plus).
Proven written and verbal communication skills.
Travel: 5%
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A completed Bachelor's Degree in Computer Science, Math, Engineering, or related discipline with 5+ years of experience, OR a completed Master's Degree in Computer Science, Math, Engineering, or related discipline with 3+ years of experience.

 

Desired Skills:

Top Secret or Top Secret/SCI Clearance
Agile Software Development 
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/889567-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
