### ISSUE TITLE
Intermediate Analyst (International Engineering)(#16)(#893865)

### ISSUE THREAD

**Issue by CkingPT2018** [tech256/jobs#199]
PeopleTec is currently seeking an Intermediate Analyst to support our Huntsville, AL location.

Incumbent will support all active international engineering efforts, including the development of International Agreements (Memorandums of Understanding (MOUs), Memorandums of Agreement (MOAs), AOAs, Project Agreements (PAs), Foreign Military Sales Agreements (FMSAs), etc.) to address technical aspects of technology transfer, export control policy and agreement obligations. Ensure international BMDS engineering products are technically sound and programmatically useful. Coordinate the incoming and outgoing of EWI generated e-tasker workflow, ensuring timely and efficient completion of assigned intra- and inter-agency tasks. EWI's contract support originates all EWI developed e-taskers to confirm proper security, to confirm DE and agency procedures are followed, and to guarantee distribution to all necessary personnel providing timely response to DE e-tasker deadlines. Coordinate the foreign disclosure process for all briefings, data sharing and information exchanges between the MDA and partnering nations and organizations. EWI coordinates with International Security (DIS), other DE three-letters and outside support (including combatant commands, military branches and contracting firms) to guarantee proper procedures are followed, items are correctly labeled to conform to security standards, and secured delivery is achieved. labeled to conform to security standards, and secured delivery is achieved. Participate in and provide technical assistance during Video Teleconferences (VTCs). Support special tasks or studies that are identified and that could benefit from expertise or assistance and executed within programmatic constraints, as required. Support Warfighter analysis, technical work, modeling/war gaming, and defense planning as required.

 

Required Skills/Experience:

    Ability to obtain a passport
    Possess an ability to plan, coordinate, and support product development in a fast-paced, rapidly changing environment
    Excellent people, organizational, management and leadership skills
    Capable of providing expertise to relevant program analytical principles and practices for developmental and operational programs
    Capable of utilizing, adapting and developing analytic tools, techniques, and processes for technical and/or administrative support activities
    Capability to use the Microsoft Office package to include Outlook, Word, PowerPoint, Project, and Excel Experience
    Travel: 10% to 20% of the time to various locations to include US and Allied installations OCONUS
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A completed Bachelor's Degree in Engineering, Mathematics, Physics, or Computer Science with 5 years of experience; OR 10+ years of relevant experience is required in lieu of degree.

 

Desired Skills:

    A completed Bachelor's Degree in Engineering, Mathematics, Physics, or Computer Science
    Experience with interacting and supporting high level government customers to include generating briefing and written products and presenting information at the executive level

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/893865-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
