### ISSUE TITLE
Revit Modeler - NuSpatial

### ISSUE THREAD

**Issue by mjcarroll** [tech256/jobs#22]
# Hiring!

### About Position
Modelers will have a willinigness to travel and have a passion for understanding progressive technology in the world of 3D scanning. Modelers will use our laser scanner technology, monitored by a tablet, that captures existing interior space in real time. Modelers work in teams of two while they plan the project, collect data on-site, verify collected measurements, and generate as-built drawing sets. Modelers must produce AIA Standards-compliant drawing sets in a timely manner and validate accuracy using video, images, and field measurements.

Skills Required

* 2+ years experience with Revit Architecture or AutoCAD
* Physically fit; able to carry a 20 pound backpack for 3-4 hours a day while walking.
* Strong team-working skills

Nice to Haves

* Design skills such as space planning, furniture layout, and finishes
* Experience creating as-built drawings
* Previous survey experience

Special Requirements

* Travel to customer sites will be required
* Eligible for U.S. Security Clearance

All candidates must be legally authorized to work in the United States.  We do not sponsor visas.

NuSpatial does not use recruiters or pay recruiter fees.

### Contact
- Tech256: @mjcarroll
- http://nuspatial.com/careers
- Kennesaw, GA

**Comment by iamvery** [comment]
ping @mjcarroll

**Comment by mjcarroll** [comment]
pong

**Comment by iamvery** [comment]
@mjcarroll ping
