### ISSUE TITLE
Software Engineer - i3

### ISSUE THREAD

**Issue by skylenewman** [tech256/jobs#23]
# Hiring!

### About Position

i3 is seeking a software engineer. The selected candidate will join our team at the Joint Technology Center Systems Integration Lab (JSIL) at Redstone Arsenal.

Software developer will design, code, and test simulation software. The developer for this position must have experience in C#. The developer must be able to work in a team environment.

> The team out there is awesome. They are top-notch developers/engineers that are excited about what they do and willing to teach / help others.

**Required Skills**

- Bachelor's Degree in Computer Science or related field required. 
- 2 to 5 years of software engineering experience required.
- Thorough knowledge of C# programming and .NET experience required.
- Must demonstrate ability to work effectively on project teams, with a variety of functional areas and management levels.
- Excellent verbal and written communication skills required.
- Must be able to obtain and maintain a DoD Secret Clearance.
- WPF experience preferred.

### Official Contact
- Twitter: @i3corps
- Lizzy Ash, 256-562-1134
- `Email lizzy = String.Join("",["elizabeth",".","ash","@","i3-corps.com"]);`

**Comment by iamvery** [comment]
ping @skylenewman (want to keep this open? reply "pong")

**Comment by skylenewman** [comment]
Pong

**Comment by iamvery** [comment]
@skylenewman ping
