### ISSUE TITLE
Object-Oriented Software Engineer - RMCI

### ISSUE THREAD

**Issue by Hilts66** [tech256/jobs#24]
# Hiring!

Description

ROLE AND RESPONSIBILITIES:
RMCI, Inc. is a multi-discipline engineering company with a core competency in machinery diagnostics and dynamic component health monitoring. RMCI is looking for motivated individuals to be part of creating cutting-edge applied Condition ­Based Maintenance (CBM) solutions. The employee will support product development of technology solutions for commercial industry and will work primarily on enterprise data visualization and processing tools. Strong candidates will have exceptional growth opportunities.

QUALIFICATIONS AND EDUCATION

REQUIREMENTS:
Candidates must have the following qualifications:
• B.S. or M.S. in Computer Science, Software Engineering, or a similar field of study
• Minimum of 3 years of experience with the software development life cycle
• Ability to design, develop, document, debug, and test software.
• Ability to follow disciplined coding standards and practices  
• Strong background in object-oriented programming
• Proven experience with Java Desktop GUI development, especially with Java Swing or JavaFX
• Ability to quickly and accurately read other programming languages (especially MATLAB)
• Knowledge of Windows and Linux operating systems
• Desire to learn and self-­improve

PREFERRED SKILLS:
Additional consideration will be given to candidates with the following qualifications:
• Familiarity with relational database systems and SQL
• Knowledge of multi­threading concepts
• Experience with C/C++
• Familiarity with JSON
• Experience with test driven development and unit testing
• Familiarity with version control systems such as Git and Subversion
• Knowledge of dependency management tools such as Maven and Nexus
• Experience with the Eclipse IDE
• Experience with enterprise applications
• Experience with web development, web markup languages, and JavaScript
• Experience with Android development

ADDITIONAL NOTES:
Employee may occasionally be required to support existing Department of Defense contracts. Therefore, candidates must be able to obtain a security clearance.

To apply, email resume to hr@rmci-inc.com

**Comment by iamvery** [comment]
ping @Hilts66 (want to keep this open? reply "pong")

**Comment by Hilts66** [comment]
pong

**Comment by iamvery** [comment]
@Hilts66 ping

**Comment by Hilts66** [comment]
pong

**Comment by iamvery** [comment]
@Hilts66 still relevant?

**Comment by Hilts66** [comment]
Yes, thank you

**Comment by iamvery** [comment]
@Hilts66 still relevant?

**Comment by Hilts66** [comment]
Yes

**Comment by mjcarroll** [comment]
@Hilts66 ping

**Comment by Hilts66** [comment]
pong

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
