### ISSUE TITLE
Software Test Engineer

### ISSUE THREAD

**Issue by mjcarroll** [tech256/jobs#25]
# Hiring!

### About Position

Looking for 2-10 years of experience testing software.  Task includes writing scripts to test requirements from a software requirements specification.

* Good understanding of software development process
* C++ development experience
* Experience deriving test cases from a requirements document
* Secret clearance or the ability to obtain one
* Understanding of communication protocols a plus 

This is a full-time position.

### Contact
- Tech256: @mjcarroll
- E-mail: michael@nuspatial.com
- Location: Huntsville, AL

**Comment by iamvery** [comment]
@mjcarroll ping
