### ISSUE TITLE
Senior Software Engineer - Linux Developer

### ISSUE THREAD

**Issue by dannagle** [tech256/jobs#27]
# Hiring!

### About Position
SVSI by Harman ( http://svsiav.com/ ) is looking for a senior software engineer to develop embedded Debian-based Linux running on our custom boards with ARM processors. If you are skilled at compiling drivers, slinging SSH prompts, enjoy A/V, and navigating network code, send me your resume! 

### Contact
- Tech256: @dannagle
- GitHub: @dannagle
- Twitter: https://twitter.com/NagleCode
- Location: Huntsville

**Comment by iamvery** [comment]
@dannagle ping (want to keep this open? reply "pong")
