### ISSUE TITLE
UAH Computer Science Lecturer Position Available

### ISSUE THREAD

**Issue by joescii** [tech256/jobs#28]
# Lecturer in Computer Science

The University of Alabama in Huntsville, classified as a Very High Research Activity institution, offers academic and research programs in the Colleges of Arts, Humanities and Social Sciences, Business Administration, Education, Engineering, Nursing, and Science. Huntsville maintains one of the highest per capita incomes and standards of living in the Southeast. It is a national center of aerospace and high technology research and is home to NASA's Marshall Space Flight Center. Huntsville and surrounding communities present many opportunities for healthcare research and professional practice.

The Department of Computer Science at The University of Alabama in Huntsville invites applicants for a non-tenure track faculty position with the rank of Lecturer beginning August 2016.  Applicants must possess a Ph.D. degree in computer science or related field. Evidence of effective teaching experience, excellent communication skills and strong interest in keeping abreast with the changing computer technology and curriculum is expected. The successful candidate will teach four computer science courses per semester during fall and spring at the undergraduate and graduate level.  The ability to teach courses in computer networks, computer architectures, or software engineering areas is preferred. The successful candidate will also serve as an academic advisor to undergraduate students like others members of the computer science faculty.

Send letter of application, vita, official transcripts and contact information for three references by email to [info@cs.uah.edu](mailto:info@cs.uah.edu) Review of applicants will begin immediately and continue until position is filled. UAH is committed to equal opportunity and affirmative action.

*The University of Alabama in Huntsville is an Affirmative Action/Equal Opportunity Employer of Minorities, Females, Veterans, and Individuals With Disabilities.*

**Please refer to log number 16/17-504**

[Original job posting](http://www.cs.uah.edu/intranet/positions/16-17-504.docx)

**Comment by iamvery** [comment]
@joescii ping

**Comment by joescii** [comment]
I contacted the CS department, and this position has indeed been closed. Thanks for the ping!
