### ISSUE TITLE
Junior Software Developer

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#287]
Junior Software Developer

Looking for a great opportunity at a CMMI award-winning organization? We have a 100% customer satisfaction rating and offer competitive benefits.

 

Cepeda Systems and Software Analysis, Inc. (CSSA) provides software engineering, systems engineering, and process improvement services for our customers. We have a 100% customer satisfaction rating and have won numerous awards at the local and national level. We treat one another with respect, foster collaboration while maintaining individual accountability, value multiple perspectives and diverse expertise, and encourage new ideas that surface throughout the organization. CSSA offers a comprehensive and competitive benefits package.

 

 Key Responsibilities:

    Perform software development in HTML and JavaScript.
    Work independently and as part of a team developing, testing, and debugging new and existing applications
    Follow established processes and procedures

 

Qualifications:

Education:

    B.S. in Computer Science, Computer Engineering, Software Engineering, MIS, or related discipline

Experience:

    2 to 5 years of software development in HTML and JavaScript
    Proficient at trouble-shooting and debugging is a plus
    Experience with SQL is a plus

Knowledge/Skills:

    Candidate should possess the ability to multi-task in a fast-paced development environment, while working collaboratively with internal and external stakeholders
    Requires strong verbal and written communication skills
    Candidate must be organized and detail oriented
    Candidate must possess problem solving and analytical skills
    Candidate must have the ability to work in team environments as well as individually
    Ability to adapt to changing situations and requirements
    Being comfortable with different programming language syntaxes is a plus

U.S. Citizenship is required

Candidate must hold active Secret Security Clearance

CSSA is an Equal Opportunity Employer

 

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/994461-194689

**Comment by tylerbhughes** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
