### ISSUE TITLE
Web Services Developer

### ISSUE THREAD

**Issue by mjcarroll** [tech256/jobs#29]
# Hiring!

### About Position
This position involves maintenance and enhancement of a system that utilizes a web service architecture based on Tomcat Apache and a number of other web server related tools and technologies. This job will involve working for a small company and require some travel from time to time to perform installations and demonstrations. The developer will need to be able to work efficiently and effectively on their own until the team grows, however technical leadership will be provided. A test framework is needed and will have to be developed for regression testing and throughput analysis. The system needs to be enhanced to be more portable, to other operating systems and versions, and support other SQL database implementations.

- Development on Ubuntu (linux) operating system and environment
- Installation, configuration, and development with Tomcat Apache
- Software design and development of web service
- Javascript
- Installation, configuration, working and developing with SQL Database (e.g. MySQL)
- Java Server Pages
- Java SQL queries
- Working with XSLT and XML
- Development of test software for JSP and java servlet based apps
- Ansible provisioning tools
- Experience with AWS
- Able to write and interpret UML diagrams used for documentation purpose
- Good work ethic and trustworthy 

Depending on skills and availability may transition from Part-time to full-time

### Contact
- Tech256: @mjcarroll
- Twitter: @carromj
- Location: Huntsville, AL
- Type: Part Time

**Comment by iamvery** [comment]
@mjcarroll ping
