### ISSUE TITLE
Senior Software Engineer

### ISSUE THREAD

**Issue by jimscala1** [tech256/jobs#292]
Nobletech Solutions is seeking a Senior Software Engineer in support of the Systems, Simulation, Software, and Integration (S3I) Directorate at Redstone Arsenal.

The candidate will work with Software developers and System Admin personnel to configure and maintain a real-time execution environment for the software applications. The candidate will have the ability to configure Linux OS systems for real-time applications that are performing HWIL testing of tactical Fire Control and Radar components.

The candidate will be performing an assessment of systems (periodically and at deployment) for suitability of the OS, hardware and software configuration to execute as expected. The candidate must be able to work independently to build and benchmark new OS configurations to determine their suitability to execute the applications. He/She will also be responsible for developing, validating and maintaining Configuration Management documentation. The desired candidate is a self-starter, able to operate with minimal supervision.

Duties and Responsibilities:

Work with the Software Development group to ensure that all application software is properly built to execute on the hardware for which it is targeted, including the following: -
Make sure the proper compile options are used to obtain the best application performance
Remain knowledgeable with the application software designs (including making recommendations) to ensure the best performance can be obtained from the HW
Configure the HW BIOS so that it will run the application code as efficiently as possible
Configure the Linux OS to make sure it is operating as efficiently as possible and does not stall the application or cause data to be dropped
Assist System Admin personnel to ensure all hardware and software is configured such that the test environment will meet/exceed required performance goals
 

Required Skills:

BS in Computer Science or related field and 10 years' experience
Secret Security Clearance
Ability to work independently with minimal supervision
Strong interpersonal skills and reporting practices
Ability to configure and build Linux kernels, to include applying RT patches; and experience testing the kernels (benchmarking) for suitability to run the applications
Experience managing and updating Linux OS builds, scripts and procedures using internal Configuration Management systems
Experience incorporating and updating vendor-supplied drivers into the Linux kernel
Ability to write scripts (Bash, Python, etc.) that assist developers and System Admin personnel in performing their duties
 

Desired Skills:

Experience with Internet Protocol (IP) networks and networking equipment including the use of multicast networking
Familiar with Red Hat Linux and its RPM packaging
Familiar with the Kickstart process that installs systems
Understanding of multiprocessor platforms and NUMA memory architectures for running real-time multi-process applications
Understanding of current industry tools supporting software development in order to make recommendations for future updates
Ability to obtain an Elevated Privileges classification (by obtaining Security+, Linux OS or Cisco certification)
This position requires a U.S. Person

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

[](https://www.applicantpro.com/j/1003368-207062)

**Comment by tylerbhughes** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
