### ISSUE TITLE
CS and IT Assistant Professor Position at Athens State University

### ISSUE THREAD

**Issue by adamwadelewis** [tech256/jobs#30]
# Hiring!
## [Athens State University](http://www.athens.edu)

College of Arts and Sciences
Department of Mathematical, Computer, and Natural Sciences
### About Position

Athens State University is seeking candidates for the position of Assistant Professor of Computer Science in our Computer Science and Information Technology programs for Spring 2017 or Fall 2017.    Our primary need is someone with a background in data sciences and database technology but we will consider outstanding candidates from any area of Computer Science.     The position involves teaching upper-division Computer Science and Information Technology courses in traditional and distance learning formats in day and evening sessions.

The required qualifications are:
- An earned Ph.D. or ABD in Computer Science, Computer Information Systems, Information Technology, or related area.
- A willingness to teach and advise students during the summer semester.
- Experience teaching at the undergraduate level or higher.   Graduate teaching experience will be considered.
## About Athens State University

Athens State University, with a student population of approximately 3500, is located near the northern border of Alabama. It is a short driving distance to Huntsville (pop. 183,000), a high growth, and urban center. It is also within a 90-minute drive via Interstate 65 to either Nashville or Birmingham. Two full service state parks adjacent to the Tennessee River are less than one hour from campus.
Athens State is the oldest institution of higher learning in Alabama with origins as a private institution dating from the 1820s. Since 1975, it has been part of the state system of higher education. Athens is conveniently located 100 miles north of Birmingham and 100 miles south of Nashville on the Alabama/Tennessee border, a mere 250 miles from Atlanta, and within 25 miles of the Huntsville International Airport.

NONDISCRIMINATION Athens State University, as an equal opportunity/affirmative action institution, complies with all applicable federal and state laws regarding discrimination and affirmative action. Athens State University does not discriminate on the basis of race, color, national origin, age, marital status, sex, sexual orientation, disability, religion, genetic information, or veteran status of employment, or admissions to or participation in educational programs or activities. Inquiries or concerns may be addressed to the Office of the Vice President of Enrollment and Student Support Services, 300 N. Beaty Street, Athens, AL 35611, 2562338175.

In accordance with Athens State University Policy and guidelines, the applicant chosen for employment will be required to sign a consent form for a criminal background check. Employment will be contingent upon the receipt of a clearance notification from that criminal background check.   

Apply at [https://jobs.athens.edu](https://jobs.athens.edu)
### Contact

Dr. Adam Wade Lewis
Athens State University
300 N. Beaty Street
Athens, AL 35611
- Voice: (256)233-6505
- E-Mail: Adam.Lewis@athens.edu
- Tech256: @awadelewis
- Twitter: @awadelewis

**Comment by iamvery** [comment]
@adamwadelewis ping (want to keep this open? reply "pong")

**Comment by adamwadelewis** [comment]
pong.


-------- Original Message --------
Subject: Re: [tech256/jobs] CS and IT Assistant Professor Position at
Athens State University (#30)
