### ISSUE TITLE
Tyler Hughes

### ISSUE THREAD

**Issue by RandomlyKnighted** [tech256/jobs#31]
# Hire me?
### Resume

http://stackoverflow.com/cv/thughes01
### Contact
- Tech256: @tylerhughes
- Twitter: @thughesIT

**Comment by iamvery** [comment]
@RandomlyKnighted ping (want to keep this open? reply "pong")

**Comment by RandomlyKnighted** [comment]
pong

**Comment by mjcarroll** [comment]
:champagne:
