### ISSUE TITLE
C# / NodeJS Developer Position

### ISSUE THREAD

**Issue by metekamil** [tech256/jobs#32]
# Hiring C# / NodeJS Developer

### About Position
Seeking Developer for a contract to hire position. Developer will be working on our Spring Product (Real Estate software) an an agile environment.

Good understanding of software development process
C# development experience
NodeJS development experience 

### Contact
- Please send resume to mkamil@solidearth.com
- Location: 228 Holmes Ave NE, 12th Floor Huntsville, AL 3580

**Comment by larrymason** [comment]
I am interested in knowing more about this position... check me out a issue #10

**Comment by iamvery** [comment]
@metekamil ping (want to keep this open? reply "pong")

**Comment by larrymason** [comment]
Ya... never have gotten any replies to it... but one can always hope!
Thanks, Larry



 Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=glmason.lm@gmail.com&idSignature=22>

**Comment by iamvery** [comment]
@larrymason did you try contacting them at their email above? If I don't hear back in a few days, I'll close this out.

**Comment by larrymason** [comment]
Yes, I had an interview with Matt Fowler at Solid Earth, he said he was interested but never got back so I guess he wasn't... I guess this issue should be closed now.
