### ISSUE TITLE
Junior Hardware-in-the-Loop (HWIL) Tester

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#322]
Junior Hardware-in-the-Loop (HWIL) Tester

Looking for an excellent opportunity at a CMMI award-winning organization? We have a 100% customer satisfaction rating, a great work environment, and offer competitive benefits.

Cepeda Systems and Software Analysis, Inc. (CSSA) provides software engineering, systems engineering, and process improvement services for our customers. CSSA has achieved a rating of Capability Maturity Model Integration (CMMI) Level 2 for Services and CMMI Level 3 for Development. We have a 100% customer satisfaction rating and have won numerous awards at the local and national level. We treat one another with respect, foster collaboration while maintaining individual accountability, value multiple perspectives and diverse expertise, and encourage new ideas that surface throughout the organization. CSSA offers a comprehensive and competitive benefits package.

 Key Responsibilities:

Develops test procedures and other test documentation (test plans, test reports, etc.)
Performs and confirms analysis of HWIL test data
Acts as test conductor for simulated ground and flight tests at the IAMD Government-System Integration Laboratory (G-SIL) during flight test activities
Performs general labor activities such as build/run cabling
Performs routine organization of lab facilities
Provides support to inventory efforts
Education and Experience:

Bachelor of Science degree from an accredited institution, or equivalent education with 0 to 5 years of relevant experience.
Experience Preferred:

Experience with Air and Missile Systems
Experience with Networking
Knowledge/Skills:

A basic understanding of the following technologies:
Cisco routers/switches
Internal and external routing protocols
Layer 2 protocols
Multicast
IPv4 and IPv6 addressing
Wireshark
Network Timing Systems
Strong communication skills (oral/written) with all levels of the organization
Excellent teamwork skills, including working with internal and external departments and organizations
Travel Required:

Applicant must be willing to travel approximately 25% of the time to provide field support. Typical locations would include areas such as White Sands Missile Range and Ft. Bliss, Texas.
 

U.S. Citizenship is required

Candidate must be able to obtain and maintain a Secret Security Clearance

CSSA is an Equal Opportunity Employer

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1010118-194689

**Comment by tylerbhughes** [comment]
Thanks for contributing to this issue. As it has been 90 days since the issue was originally opened, we are automatically closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
