### ISSUE TITLE
Associate Buyer (#1011413)

### ISSUE THREAD

**Issue by CkingPT2018** [tech256/jobs#326]
PeopleTec is currently seeking an Associate Buyer to support our Huntsville, AL location. The ideal candidate will procure goods, including software and hardware and administer purchase orders of moderate dollar value, risk, and complexity and will report to the Purchasing Manager.  In addition, primary job duties include:

Responsibilities include the development and negotiation of favorable prices, terms, schedules and other provisions of purchase orders and acquisition contracts, ensuring consistency with client requirements and procurement policies/procedures
Purchase order administration/file maintenance
Closeout for all procurement related activities and supplier customer management, including negotiating price/cost and price/cost-related terms and other subcontract provisions
Confers with suppliers and analyzes suppliers' operations to determine factors that affect prices and determines lowest cost consistent with quality, reliability, and ability to meet required schedules
Recommends suppliers based on gathered information and may also recommend improvements to procurement processes and procedures
Assume other responsibilities as requested in support of departmental goals and objectives
Required Skills/Experience:

Excellent time management skills
Solid communications skills, both written and oral. Ability to communicate across several levels of staff and customers/vendors
Strong team player
Experience with Microsoft Office Suite, especially Word, Excel and Outlook
Knowledge of government procurement and Federal Acquisition Regulations
Ability to work independently with minimal supervision
Exhibit critical thinking and analytical skills
Travel: None
Must be a U.S. Citizen
 

Education Requirements:

A completed Bachelor's Degree and 1+ year of experience, OR a completed Master's Degree and zero years of experience.

 

Desired Skills:

Previous team leadership experience
Previous purchasing experience in a manufacturing environment or information technology
 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1011413-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
