### ISSUE TITLE
Senior Contract Administrator (#1011419)

### ISSUE THREAD

**Issue by CkingPT2018** [tech256/jobs#327]
PeopleTec is now hiring Senior Contract Administrator to support our Huntsville, AL location.

The ideal candidate will be responsible for the following job duties:

Negotiates contracts to include large services and engineering projects.
Researches, understands, monitors and administers the business provisions of assigned contracts to ensure compliance with contractual terms and conditions.
Advises the Contracts Manager regarding scope, financial, and risk issues of applicable contracts.
Generates and maintains documentation for negotiations including change orders.
Supports new business proposals including ECPs.
Collaborates with Procurement personnel on project subcontract and purchasing matters.
Monitors project expenditures versus contract cost limitations.
As the main interface with their counterpart on all contractual issues, prepares letters to clients notifying them of contract cost limitations and requirements for additional funds as well as all other communications.
Collaborates with Program Control and PM to furnish business and financial information and direction requested by the client, as delegated by the Project Manager.
Identifies contractual problems and takes appropriate action to ensure a satisfactory resolution.
Follows up on challenges demanding management attention to ensure a timely response to the client.
Works independently and prioritize work to meet deadlines.
Provides contractual guidance to internal customers.
Performs other responsibilities associated with this position as may be appropriate. Develops and promotes strong customer intimacy and possess excellent customer service attitude displaying dignity and respect to all stakeholders.
Promotes business growth through relationships with both internal and external customers.
Proactive in development of negotiation and business strategies and function as a trusted business adviser to the Program Manager.
 

Required Skills/Experience:

Minimum 5+ years contract administration experience with FAR, TINA, CAS and DFARS requirements is required to include negotiating complex contractual requirements.
Demonstrated proficiency with FAR, DFARS and its supplements, industry business best practices, and the negotiation of contracts is required.
Experience with tangible deliverable items required.
Experience with leading project team utilizing industry best business practices on contracts required.
Experience working effectively in a team environment required.
Strong written and oral communication skills, excellent interpersonal skills required.
Working knowledge of PC software packages typically associated with contract administration.
Travel: None
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A completed Bachelor's Degree in Business Administration, Finance or related field is required. Master's Degree desired.

Desired Skills:

NCMA Certification preferred
Master's Degree
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1011419-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
