### ISSUE TITLE
Web Developer at Redstone Federal Credit Union

### ISSUE THREAD

**Issue by joescii** [tech256/jobs#33]
# Web Developer at Redstone Federal Credit Union
## Job Description

We’re looking for a web developer who loves a challenge and can deliver effective web development based on analytics insights and UX best practices to achieve corporate goals and strategies. This position will manage the development of Redstone’s corporate website and landing pages including creation, production, search engine optimization, consistent branding, analytics maintenance, and execution.   
## Required Skills

The ideal candidate will have the following skills:
- Expert skill with CSS, HTML, and Javascript/JQuery required.
- Familiar with current ‘web standards’ and best practices within the web development and production field.
- Experience with content management system (CMS) themes and layouts; Percussion CM1 experience is a plus.
- .NET and PHP experience is a plus.
- Experience with cross-browser/cross-platform development.
- Experience with responsive web design frameworks (Foundation/Bootstrap).
- Superior knowledge of current web-design, trends and techniques, and user-centered design.
- Experience with design optimization tools such as Optimizely, Crazy Egg, or similar.
- Experience with advanced implementation and maintenance of analytics platforms for tracking;  Google Analytics experience is a plus.
- Familiar with Apache and IIS servers.
- Working knowledge of search engine optimization (SEO) best practices.
- Great eye for design and attention to detail, especially with regard to consistency across an entire website.
- A strong online portfolio showcasing work.
## Required Experience

Bachelor’s degree in Web Design, Technology, Computer Science, MIS, Graphic Design, Marketing or closely related field or commensurate experience.
Four years experience in web development.
## Equal Opportunity Employer

Redstone Federal Credit Union is an equal opportunity employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, protected veteran status or status as an individual with disability. All qualified applicants will not be discriminated against on the basis of disability. We are proud to be a Drug-Free and Tobacco Free Workplace.
## Job Location

Huntsville, Alabama, United States
## Position Type

Full-Time/Regular
## Tracking Code

384-968

**Comment by iamvery** [comment]
@joescii still relevant?

**Comment by joescii** [comment]
Seems like it's filled according to their website. Thanks!
