### ISSUE TITLE
Jonathan Brock For Hire

### ISSUE THREAD

**Issue by jbrock1981** [tech256/jobs#363]
# Hire me?

## Jonathan Brock
Full Stack Web Dev, Support Engineer II
React, Node, Express, PostgreSQL, sqlite, knex, Preact, and much more!
Active Directory, O365, Network Admin and Security, and much more! 

### Resume
jbrock.dev

### Contact
- (256) 694-5267
- jbrock@jbrock.dev

**Comment by GeneralPallas** [comment]
@jbrock1981 are you still looking for a position?
