### ISSUE TITLE
PeopleTec18!

### ISSUE THREAD

**Issue by CkingPT2018** [tech256/jobs#364]
PeopleTec is currently seeking a Signatures Analysis Lead to support our Huntsville, AL location.

 

PeopleTec is seeking an experienced analyst to lead signatures analyses within an integrated team of modelers, software developers and systems engineers. The  candidate will have demonstrated experience assessing and analyzing infra red (IR), radio frequency (RF) and electro-optical (EO) signatures reflected by man-made objects such as missiles and aircraft. The candidate will also  be knowledgeable of industry-standard techniques and tools for signatures assessment. The candidate will perform signatures assessments within scenarios developed by the broader team. The candidate will supervise and mentor junior team members. 

 

Required Skills/Experience:

    Software development in structured languages
    Demonstrated knowledge of and experience with industry-standard methods and tools
    Demonstrated personnel supervision / mentoring skills
    Excellent written and oral communications skills
    Travel: 10%
    Must be a U.S. Citizen
    An active DoD Top Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's of Science Degree in Engineering or Physics is required.

Desired Skills:

    Master's Degree
    Linux and Windows based computing
    C/C++/C#
    Fortran
    Python OSC 
    OPTISIG Xpatch

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1042804-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
