### ISSUE TITLE
Senior Java Software Developer

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#367]
CSSA logo

Senior Java Software Developer

Looking for a great opportunity at a CMMI award-winning organization? We have a 100% customer satisfaction rating and offer competitive benefits.

Cepeda Systems and Software Analysis, Inc. (CSSA) provides software engineering, systems engineering, and process improvement services for our customers. CSSA has achieved a rating of Capability Maturity Model Integration (CMMI) Level 2 for Services and CMMI Level 3 for Development. We have a 100% customer satisfaction rating and have won numerous awards at the local and national level. We treat one another with respect, foster collaboration while maintaining individual accountability, value multiple perspectives and diverse expertise, and encourage new ideas that surface throughout the organization. CSSA offers a comprehensive and competitive benefits package.

 Key Responsibilities:

    Understands a wide application of technical principles, theories, and concepts in SW development, and a general knowledge of other related disciplines
    Provides direction to junior level team members according to established policies and management guidance
    Performs work under only general direction while independently determining and developing approaches to assigned problems
    Demonstrates the ability to work in a medium to large size team, agile environment, to design, implement and test SW components through the entire SW lifecycle
    Demonstrates the ability to break up larger SW modules into smaller, incrementally delivered components on tasks that have been assigned to them
    Provides workbook (Integrated Master Schedule) estimates on the time required to design and implement SW components that have been assigned to them
    Creates and presents design documentation, as well as participate in design reviews for SW modules assigned to their team
    Coordinates and participates in peer reviews of other teammates SW implementation and design (e.g. code reviews)
    Develops unit test strategies on components they have been assigned
    Performs test that are to be developed SW in a lab environment with actual fielded hardware
    Demonstrates the ability to function at a SW lead level working in coordination with Systems and Test Engineers

Qualifications:

Education and Experience:

    B.S. in Computer Science, Computer Engineering, Software Engineering, MIS, or related discipline
    10 years of related experience

Experience Required:

    Java/Java FX SW Development
    Javadoc SW documentation constructs

Knowledge/Skills Required:

    RESTful Application Programming Interface (API)
    JSON API Application Programing Interface (API)
    Network Analysis Tools (Wireshark, TCPDUMP analysis)
    Scripting languages such as Python
    Ability to work on large defense related projects
    Good communication skills are a must

 

U.S. Citizenship is required

Active Secret Security Clearance is required. Candidate must eligible for a Top Secret Security Clearance.

CSSA is an Equal Opportunity Employer

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1045073-194689

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
