### ISSUE TITLE
Systems Administrator

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#369]
Systems Administrator

 Looking for an excellent opportunity at a CMMI award-winning organization? We have a 100% customer satisfaction rating, a great work environment, and offer competitive benefits.

Cepeda Systems and Software Analysis, Inc. (CSSA) provides software engineering, systems engineering, and process improvement services for our customers. CSSA has achieved a rating of Capability Maturity Model Integration (CMMI) Level 2 for Services and CMMI Level 3 for Development. We have a 100% customer satisfaction rating and have won numerous awards at the local and national level. We treat one another with respect, foster collaboration while maintaining individual accountability, value multiple perspectives and diverse expertise, and encourage new ideas that surface throughout the organization. CSSA offers a comprehensive and competitive benefits package.

Key Responsibilities: 

    Develops and maintains an automated environment including reporting, event notifications and actions, software updates, service packs, and patching. (ex. SCCM, WSUS, Scripting, etc.)
    Assists in managing and operating an IT infrastructure to include VMware, Servers, SAN and NAS devices, SQL Server Databases, Windows Server 2016, IIS, and SQL Server 2016
    Answers questions about and assists with systems-related user issues
    Monitors databases and application server's utilization including data storage management, performance metrics, and service levels
    Ensures reliable backup and recovery of databases and maintains an awareness of trends within the technology industry

Education & Experience Requirements:

    Experience with STIG Compliance, RMF, eMASS
    Experience with vulnerability scanning tools (ex. ACAS, Retina, SCAP, QTIP, etc.)

AND EITHER

    Bachelor's degree from an accredited college or university in a related field with five (5) or more years of experience

OR

    Master's degree from an accredited college or university in a related field with three (3) or more years of experience

Knowledge/Skills Required: 

    Familiar with systems cryptography and security certificates to include TLS, SSO, SSL, tokens, and ECAs.

License/Certification: 

    CompTIA Security+

 

U.S. Citizenship is required 

Active Secret Security Clearance is required. Candidate must eligible for a Top Secret Security Clearance.

CSSA is an Equal Opportunity Employer

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1045421-194689

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
