### ISSUE TITLE
Sr. Database Application Developer

### ISSUE THREAD

**Issue by jimscala1** [tech256/jobs#371]
Nobletech Solutions is seeking a Senior Database Application Developer. The successful candidate will support the current and evolving Strategic Systems Engineering Services (SSES) efforts for the Systems, Simulation, Software, and Integration (S3I) Directorate customer. S3I, within the US Army Aviation and Missile Research, Development and Engineering Center (AMRDEC) has development and support responsibilities for many weapon systems, related support systems, and associated enhancements. The Strategic Systems domain includes activities for Combatant Commanders (COCOMs), Agencies, and Foreign Military Sales (FMS) efforts. The candidate will conduct daily duties at the S3I Directorate, Redstone Arsenal, AL.

The candidate analyzes, designs, programs, debugs, and modifies database applications that contribute to integrated software solutions used in local, networked, or internet-related application suites. The candidate is responsible for designing databases and ensuring their stability, reliability, and performance. Alongside other application developers and actively applying collaborative development tools, the candidate optimizes in-application SQL statements as necessary, and establishes best practices. The candidate is responsible for integrating data from multiple source systems, displaying data appropriately, identifying areas of process improvement, and implementing solutions through data integration and automation.

The candidate works with complex data models and object relational database structures. Writes database SQL packages, procedures and triggers according to technical requirements. Works with a development team in the design, development, testing, tuning and implementation of database applications. Completes documentation and procedures for installation and maintenance. May interact with users to define system requirements and/or necessary modifications. Assists with database systems administration.

Required Skills:

    Proficient with Internet Information Server /Services (IIS)
    Proficient in understanding Data Models and relationships to be able to write complex queries
    Strong Analytical skills to triage performance issues and provide fixes/solutions
    Experience with SQL Server
    Experience with SQL Stored Procedures
    Proven experience developing and performance tuning large scale enterprise database applications with high transactional volume
    Experience with Data Modeling (using tools like ER-Win), Data Migration and ETL processing
    Experience in developing application scenarios, process flows/models, test cases and scripts
    Strong technical documentation ability
    Experience with code deployment in development, testing and production environments
    Active Secret Clearance, or ability to acquire one

Desired Skills:

    Team Foundation Server (TFS) working knowledge/experience
    Virtual Machine (VM) working knowledge/experience
    Microsoft Azure working knowledge/experience
    Experience with scripting languages such as Shell, Perl
    Experience developing web interfaces

Required Education:

    Applicants must have a minimum of a BS in Software Engineering, Computer Science, Computer Engineering, or similar degree field, and a minimum of 8 years relevant experience

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

(https://www.applicantpro.com/j/1044444-207062)

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the issue was originally opened, we are closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
