### ISSUE TITLE
Software, Data Analyst, System (non-IT) Engineers

### ISSUE THREAD

**Issue by spearna** [tech256/jobs#38]
# Hiring!
### About Positions

Seeking: (see link above)
- Software Engineers, 
- Data (General, Sim, and Radar) Analysts, 
- System Engineers (non-IT) 
### Contact
- Tech256: @spearna
- Location: Huntsville, AL / Colorado Springs, CO / Dayton, OH
- Also, apply via the website above.

**Comment by iamvery** [comment]
@spearna still relevant?

**Comment by spearna** [comment]
It's still listed on the current openings.

**Comment by spearna** [comment]
Closing this one. Will open individual req issues with number as they are posted.
