### ISSUE TITLE
Sharepoint Developer (#1058408)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#380]
PeopleTec is currently seeking a Sharepoint Developer to support our Huntsville, AL location.

 

The candidate will serve as a technical expert for the design, development and maintenance of SharePoint sites and content as well as provide daily support to business end users. The candidate will participate on a team to develop and implement of business processes, design, security, and workflow automation requests built on the SharePoint Platform using SharePoint Designer, web design, .NET and SharePoint features. 

 

Required Skills/Experience:

    Use technical knowledge, creativity and company practices to develop solutions to complex business problems
    Work with a team to design, develop and maintain solutions for business stakeholders
    Assist in gathering initial business requirements and testing
    Develop business solutions using Web UI and SharePoint tools
    Implement SharePoint based workflows as well as designs and develops sites and content
    Interact directly with the business for development and troubleshooting
    Work independently or as part of a team
    Perform root cause analysis
    Help support existing other, non-SharePoint, third party applications
    Experience with PowerShell, HTML/HTML5, JavaScript, jQuery, CSS, C#, SQL
    Knowledge of software development phases including design, coding, testing, debugging, implementation and support
    Travel: 10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

Bachelor's degree in Information Technology or related field and equivalent experience is required.

Desired Skills:

     Experience with MS Cloud, AZURE a plus

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1058408-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
