### ISSUE TITLE
Cybersecurity Analyst (#1058420)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#381]
PeopleTec is currently seeking a Cyber Security Analyst  to support our Huntsville, AL location.

Candidate will be part of a team responsible for achieving an Authorization as part of the Risk Management Framework (RMF) process. Candidate will be part of a team implementing an MS365 GCC High Cloud Solution and ensuring security is built in during implementation. Candidate will assist in the development of the RMF package to achieve an ATO in accordance with NIST 800-53 Risk Management Framework (800-32 Rev 2) and must be capable of devising policy recommendations to streamline and accelerate successful security outcomes. Candidate will also be responsible for all RMF documentation to include the SSP.

 

Required Skills/Experience:

    Knowledgeable in National Institute of Standards and Technology (NIST)
    800-53 Rev4 or higher
    Capable of reviewing, analyzing, and assessing systems configurations/ architectures to identify security, safety, and mission-critical functions/components
    Knowledgeable in Cloud (Azure) security risks and controls
    Must be a team player with good customer interaction skills
    Travel: 10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's  Degree and 3 years or more experience in federal information security policies, practices, and legal requirements including FISMA and FedRAM is required.

Desired Skills:

    CISSP, CCSP, CCSK, or SANS security certification

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1058420-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
