### ISSUE TITLE
Senior Research Scientist - Meteorology (#1061441)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#382]
PeopleTec is currently seeking a Senior Research Scientist - Meteorology to support our Huntsville, AL location.

 

Peopletec is seeking a senior level research scientist with experience in numerical meteorology to join our team. The candidate will join an integrated development team to develop models and simulations in support of an emerging weapon system.

 

Required Skills/Experience:

    Background in computational physics 
    Good math skills, especially statistics
    Strong software and scripting programming
    Excellent written and oral communications skills
    Travel: 5%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 Education Requirements:

10+ years of experience; Master's in Physics, Atmospheric Science, Geo-Science or related field is required. 

Desired Skills:

    C/C++/C#, Fortran, Python Linux and Windows OS familiarity with Geographic Information Systems (GIS) background in meteorology experience with National Blend of Models (NBM)

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1061441-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
