### ISSUE TITLE
UX Designer 

### ISSUE THREAD

**Issue by choragus** [tech256/jobs#384]
# Hiring
UX Designer at Dynetics

https://careers.dynetics.com/job-view.php?p=5328

### Contact
- Scott Carle (Scott.Carle@dynetics.com) There may be a recruiting bounty on hiring you.

- Location: Huntsville, AL
- etc...

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
