### ISSUE TITLE
Network Support Specialist / Help Desk (#1071565)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#386]
PeopleTec is currently seeking a Network Support Specialist / Help Desk to support our El Paso, TX location.

Networking Support Technician, responsible for installing, configuring, maintaining, and troubleshooting routers firewalls and switches. Responsible for provisioning mobile devices enabling authorized users secure access to DOD exchange establishing user accounts in both Non-Classified Internet Protocol Router Network (NIPRNET) and Secret Internet Protocol Router Network (SIPRNET). Ensures Information Systems (IS), under configure and operate Information Assurance (IA) enabled technology according to DoD information system IA policies and security requirements and notify the Information System Security Officer of any changes that might adversely impact IA; including interface configuration and routing protocols network performance issues including availability, utilization, configuration, establishing connectivity. Utilizes Active Directory, Unidesk, Solarwinds, Exchange, SecureCRT, Putty, VMware, Ghost, Administered BMC Footprint Remedy ticketing documentation system to monitor current trouble job tickets. Additionally, will manage and maintain all current documentation for respective systems, computer hardware, system typologies or diagrams, IP address schemes, and router, switch, and firewall configuration, telephone mobile devices and telecommute devices for JTFN. Anticipates and assists in planning towards technology transformation and recommends the adjustment and upgrade of company hardware and software

 

Required Skills/Experience:

Security+
Networking Experience 
Secret Security Clearance
Desktop Support
Travel: 10%
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

5 years of experience is required.

 

Desired Skills:

 SEC+
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1071565-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
