### ISSUE TITLE
Network Security/Communication/IA Officer (#1072258)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#387]
PeopleTec is currently seeking a Network Security/Communication/IA Officer to support our Huntsville, AL location.

 

The primary responsibilities would include: information assurance, secure communications setup, configuration and monitoring, network administration and system configuration and monitoring. 

 

Required Skills/Experience:

Minimum of 8+ years of related work experience
Knowledge of the Department of Defense Risk Management Framework (RMF) policies and procedures
Knowledge of secure communications systems
Knowledge of network configuration, setup and monitoring
Network +, Security + and A+ certifications
Coordination with development engineers, network users, command system administration, and senior and junior information assurance team members 
Coordination with senior management 
Excellent technical domain knowledge
Interpersonal communication skills
Travel: Up to 20%
Must be a U.S. Citizen
An active DoD Top Secret clearance with SCI eligibility is required to perform this work. Candidates are required to have an active Top Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A Bachelor's degree and a minimum of 8 years of experience is desired.

Physical Job Requirements:

The candidate must be able to lift up to 25 lb. Physical agility to modify network wiring in confined spaces is required.

Desired Skills:

Bachelor's degree in related field
CISSP
Uniformed service experience with remote networks and communications 
Demonstrated experience working with command-level staffs
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1072258-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
