### ISSUE TITLE
Advanced Engineer - International Engineering (#1074142)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#388]
PeopleTec, Inc. is currently seeking a full time Advanced Engineer to support Missile Defense Agency (MDA) International Engineering in Huntsville, AL.

This position will include both product and systems engineering support for the Israeli Program Office.   This position will also be responsible for coordinating technical efforts of all support engineers and analysts based upon priorities of the MDA/IP Program Office and Chief Engineer.  Applicants must be capable of accomplishing assignments in teamwork settings.  Work may require travel 15% to 30% of the time to various locations to include program office, integration sites, and test sites within the CONUS or OCONUS.

Required Skills/Experience:

    Capable of leading and executing extensive engineering/scientific support on systems, system elements, interfacing systems, components, devices and/or processes for complex developmental and operational weapon system programs
    MDA experience with design development, testing, production, or production of missile defense weapon systems or components
    Experience with generating technical point papers and informational briefings for executive level decision makers
    Possess in-depth practical and theoretical technical/engineering knowledge
    Capable of working independently, as a team member, or leading teams/tasks to solve engineering/scientific problems
    Capable of leading implementation of system engineering processes across a program acquisition life cycle
    Capable of providing daily supervision and direction to support teams
    Education/Experience Requirements: BS in engineering, mathematics, or physics; MA/MS in related field with 10 years' experience
    Passport or the ability to obtain one
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

Desired Skills/Experience

    Experience with Missile defense technical baseline reviews (Integrated Baseline Reviews (IBRs), Development Baseline Reviews (DBRs), Director's Program Reviews (DPRs), and Program Element Reviews (PERs)) to include providing executive summaries of these reviews.
    Experience with explaining technical information for US external reporting at the OSD, Congressional Staffer and/or Military Service levels.
    Experience with preparing monthly schedule/critical path analysis reports.
    Integration of elements into missile defense weapon systems (sensor fusion, timeline analysis, engagement planning, state diagrams)
    Missile defense engineering design, requirements, and programmatic reviews (DOORs, CCBs) assessments and executive technical summaries

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1074142-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
