### ISSUE TITLE
Basic Engineer - International Engineering (#1074151)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#389]
PeopleTec is currently seeking a Basic Engineer to support the International Engineering contract in our Huntsville, AL location.

 Required Skills/Experience:

    System-level engineering analysis and assessment of international weapon system architectures, designs, and performance.
    Track system requirements within both Dynamic Object Oriented Requirements System (DOORs) and the Configuration Control Board (CCB) process.
    Prepare engineering design review entry and exit criteria, technical summaries, and action item status lists, and track actions through closure.
    Assess whether entry and exit criteria are met and recommend approaches to close identified gaps.
    Assist in preparing Plans of Action and Milestones and closure packages. 
    Assist in presenting discrepancy reports to Interoperability Test and Analysis Group and Failure Reporting and Corrective Action System (FRACAS) board.
    Must be a U.S. Citizen
    Must have current (unexpired) U.S. Passport
    A Secret clearance is required to perform this work.  Candidates are required to have an active clearance upon hire, and the ability to maintain a Secret clearance level during their employment.

 

Educational Requirements:

A completed Associates Degree in Engineering or other related field is required with at least two years of specialized experience. 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1074151-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
