### ISSUE TITLE
HR Business Partner (#1082564)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#391]
PeopleTec is currently seeking an HR Business Partner to support our Huntsville, AL location.

 

The candidate will assist with new hire processing, employee orientation, employee open enrollment, benefits administration, wellness program management, performance management, workforce analytics and employee recognition programs.

 

Required Skills/Experience:

    Minimum of 10 years of direct Human Resources experience 
    Understanding of all HR functions 
    Ability to multi-task and establish priorities in a very fast-paced work environment
    Excellent organization, analytical, communication, and interpersonal skills
    Positive attitude with meticulous attention to details
    Experience in event planning for both small and large scale company programs 
    Previous experience conducting orientation, new hire data entry, benefits administration
    Previous experience in writing/formatting/administering company newsletter
    Data auditing and reporting (company metrics, monthly reports, etc.)
    Ability to cold-call and build relationships by phone
    Successfully deliver on all deadlines and flawlessly execute in a fast-paced environment
    Audit/Maintain HRIS data for accuracy
    Enter benefit elections and changes for new and current employees
    Conduct New Employee Onboarding sessions
    Track progress and status of employee training and development
    Support employees and supervisors by tracking and reporting the organization's annual requirements for performance management data
    Develop and facilitate a PeopleTec wellness program
    Must be knowledgeable in the following areas and will administer as needed : FMLA /Disability, Military Leave, ADA, Workman's Comp, Employee Out-Processing, eVerify, tuition reimbursement requests, FLSA, salary change/promotion requests, etc.
    Attend career fairs and job fairs to promote PeopleTec and educate potential candidates about our culture, projects, and openings
    Be a point of contact for all employees regarding HR/Benefits, Recruiting, and Company Policies
    Candidate will assist with data audits, processing QSC's, benefits administration/benefits set up, verify dependent eligibility documents 
    Must be a U.S. Citizen

 

Education Requirements:

A completed Bachelor's Degree in Human Resources, or other related field is required.

Desired Skills:

    Previous experience within HR in the Aerospace and Defense Industry, Intelligence Community, or Space Industry
    Experience developing and administering internal programs and processes
    Knowledge of proposal processes and/or government contract requirements as related to HR/Staffing
    PHR or SHRM certification
    Proficient computer skills with familiarity with Microsoft Office products and SharePoint
    JAMIS / GCS experience

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1082564-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
