### ISSUE TITLE
Acquisition Analyst (#1082857)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#392]
PeopleTec is currently seeking an Acquisition Analyst to support our Huntsville, AL location.

The candidate will provide programmatic analysis and support to the ITEP PM, DPM and APM. The candidate will: review, analyze, and apply the Joint Capabilities Integration & Development System (JCIDS), DoDI 5000.02, Federal Acquisition Regulation, and applicable statutory/regulatory requirements in support of execution of the ACAT IC ITE program. The candidate will support the development, coordination, and configuration control of programmatic schedules, contract requirements packages, and decision briefings. Candidate will prepare, facilitate, and support functional Integrated Product Team meetings, briefings, and program reviews as well as develop and maintain status of task-based schedules, action items lists, minutes, and presentation materials. Candidate will assist with the management of daily operations of the Ops/Plans Division to include: organizing, formatting, assuring accuracy and completeness of documents and presentations. Candidate will also: prepare, distribute, collect, and maintain all records, reports, files, paperwork and logs for supervisors.

 

Required Skills/Experience:

    Technical expertise and in depth knowledge of the Federal Acquisition Regulation, Planning, Programming, and Budgeting Execution (PPBE), JCIDS acquisition process, DODI 5000.02 requirements, and applicable supporting statutory/regulatory documentation
    Technical experience providing strategic life cycle planning and programmatic support for ACAT I Major Defense Acquisition Programs
    Technical experience with the Department of the Army and Joint milestone decision staffing and review process
    Project management and IPT experience, including: contract actions/ SOWs, CDRL and data management, Integrated Master Schedules, requirements verification and validation, and configuration management.
    Travel: 25%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree (Science, Business/ Technical) with 10+ years of relevant work/ experience is required. 

Desired Skills:

    Acquisition: Level 3
    MBA or MS: Acquisition & Contract Management 
    Training Certification: DAWIA Level III Program Management as well as any other DAWIA certifications

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1082857-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
