### ISSUE TITLE
System Avionics Engineer (#1086143)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#394]
PeopleTec is currently seeking a Systems Avionics Engineer to support our Huntsville,AL location.

 

The candidate will support UH-60L/M IVHMS software products through all phases of software development life cycle, including: requirements development, software design, software coding, and software testing. Candidate will also perform evaluation of developer traceability, implementation, and verification adequacy of the system and software requirements. The candidate will provide feedback via written reports and briefings to the government across multiple areas being assessed. Candidate will support/facilitate developer meetings, integrated product teams (IPTs) and boards such as a Configuration Change Board (CCB), as well as key program milestones such as the Software Readiness Review (SRR), Preliminary Design Review (PDR), Critical Design Review (CDR) and Test Readiness Review (TRR).

 

Required Skills/Experience:

    Possess a thorough understanding of the Software Development Life cycle processes 
    Demonstrated experience in the analysis of software artifacts
    Experience with software development/verification tools to include integration testing in system integration labs (SILs)
    Knowledge of DO-178C software artifacts and Stages of Involvement (SOI) audits
    Knowledge of contract requirements and documents (Systems Engineering Plans, Statements of Work, etc.)
    Travel: 25%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree in Computer Science, Systems/ Software Engineering or related field with 7+ years of experience is required.

 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1086143-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
