### ISSUE TITLE
Senior Systems Engineer(#1086145)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#395]
PeopleTec is currently seeking a Senior Systems Engineer to support our Huntsville, AL location.

 

We are currently seeking a Senior Systems Engineer to support design and integration of software systems to support Army weapon systems. The candidate will be responsible for requirements definition and verification; design of hardware and software systems and components to satisfy the requirements; production and integration of the hardware and software systems; test, delivery, and post-delivery customer support of the systems. The candidate must be able to effectively interface with the software development team, the warfighter, and the engineering SMEs.

 

Required Skills/Experience:

    20+ years of related experience
    Seasoned background in safety- and security- critical systems
    Flight dynamics experience 
    Detail oriented
    Strong communication skills
    Travel: 5-10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Master's Degree in Engineering or Physics and 20+ years of experience is required.

Desired Skills:

    C/C++/C# programming
    CMMI
    ML 3 processes
    Ability to secure a Top Secret clearance 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1086145-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
