### ISSUE TITLE
Senior Software Developer

### ISSUE THREAD

**Issue by jperiodlangley** [tech256/jobs#397]
# Hiring!

## CohesionForce, Inc

LinkedIn: [CohesionForce](https://www.linkedin.com/company/cohesionforce-inc./)
GitHub: @cohesionforce

### Position:

CohesionForce has an immediate opening for an experienced C/C++ developer for a modeling and simulation system. This M&S system is comprised of legacy Ada and C++ applications that are being ported to a newer OS with additional functionality added.

The work location is **not** on Redstone Arsenal.

**Required**

- Active DoD Security Clearance
- 10+ years of experience with C/C++ (8+ with a masters)
- Ability to work with a large existing code base
- Experience with *nix OS level programming
- Ability (& patience) to follow a rigorous engineering process
- Ability to analyze and modify existing Ada code
- B.S. Degree or higher in an engineering discipline

**Desired**:

- Socket-level Communication
- Multi-threaded Applications
- CORBA/DDS Middle-ware
- Unit test frameworks
- Ada development

### Contact
- Email: jlangley@cohesionforce.com
- Twitter: [@jperiodlangley](https://twitter.com/jperiodlangley)
- Location: Huntsville, AL

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
