### ISSUE TITLE
Senior Modeling Engineer (#1087105)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#398]
PeopleTec is currently seeking a Senior Modeling Engineer to support our Huntsville, AL location.

PeopleTec is seeking a Senior Engineer to support model development efforts for the Core Lethality Model program. The ideal candidate will be experienced in working with Intelligence Community data in various forms to develop high fidelity models to support lethality and debris analyses. Additionally, the candidate will be responsible for developing scripts to automate development and verification processes. The candidate will mentor junior engineers and help mature model development processes.

 

Required Skills/Experience:

    Fortran/C/C++ BRLCAD
    Strong written communication skills
    Support product documentation efforts
    Travel: 0%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree in Engineering or Physics with 15+ years of experience is required.

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1087105-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
