### ISSUE TITLE
Radar Signal Analyst

### ISSUE THREAD

**Issue by jimscala1** [tech256/jobs#399]
The mid-level candidate is responsible for analyzing strategic radar signal data and developing presentations of results for technical briefings to leadership.  The candidate should be a self-starter and be able to operate with minimal supervision.  Required Qualifications:  Understanding of radar signal and data processing  MATLAB knowledge and experience  LINUX knowledge and experience  Ability to generate clear, concise, and intuitive presentation of results  Strong Microsoft Office skills  Strong interpersonal skills and reporting practices  Strong verbal and written communication skills  Able to work well in a team environment  Secret clearance or interim   Desired Qualifications: 

    PERL script knowledge and experience  Familiarity with X-band radars 
    Familiarity with the Missile Defense Agency (MDA) pre- and post-test analysis activities and procedures 
    Experience with root cause analysis of Strategic radar systems and interoperability  
     
    Required Education:   Applicants must have a minimum of a BS in Electrical Engineering, Physics, or similar degree field, and a minimum of 6 years relevant experience  
    This position requires a U.S. Person 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1077650-207062

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
