### ISSUE TITLE
Create contributing.md

### ISSUE THREAD

**Issue by mjcarroll** [tech256/jobs#4]
Give some sort of contribution guide.

**Comment by chadxz** [comment]
would be good to have a template for the "who wants to be hired" section. I'm not actively looking for a new gig, but would be open to hearing about possibilities from people that are interested in me & my skill set.

**Comment by mjcarroll** [comment]
@chadxz That's what I was thinking in issue #3, not sure what that would look like, but we can discuss it over there.

**Comment by iamvery** [comment]
I tend to think the issue template would cover this. Do we need to extend it in anyway?

**Comment by chadxz** [comment]
I took a look, and it seems fine for active candidates. However, for passive candidates it seems like too much. Maybe that's okay though, and this just isn't the right venue for passive candidates.

**Comment by iamvery** [comment]
I'd love the barrier of entry to be extremely low for this. The point of the template is to give folks an idea of what information they should provide. I've translated the existing docs into GH issues with labels. Does it look decent?

**Comment by chadxz** [comment]
We've kind of hijacked this issue to the point that it no longer represents what it was intended for. sorry about that @mjcarroll.

RE: low barrier to entry, here are my thoughts. After thinking about it some more, I realize that as a passive candidate, I could probably fill out an issue to be clear that i'm not actively looking but would be willing to entertain the idea of moving somewhere if the work and offer were compelling enough. So I don't think there's anything necessarily wrong with the issue template. Maybe just some verbiage in the README indicating that the list isn't just for people actively looking, but can be for anyone that wants to put their info here to be seen by employers looking for local candidates.

**Comment by mjcarroll** [comment]
All good stuff.  I think that this is probably not really relevant anymore now that we've moved to issues and added the verbiage about passive stuff.
