### ISSUE TITLE
Software Trainer

### ISSUE THREAD

**Issue by jimscala1** [tech256/jobs#400]
Nobletech Solutions is seeking a Software Trainer with previous military training experience to be the resident expert on all aspects of a military software system. The Software Trainer will instruct military members on the use of the software, obtain feedback from users, work with developers to integrate the user feedback, and test the software for workflow, usability, and accuracy.

Duties include:
Making recommendations to the software's user interface, reviewing software design, and documentation.
Performing demonstration of software for program/project management, new users, and customers.
Ensuring product requirements are being tested from a user perspective with regards to accuracy in calculations, configuration and overall functionality.
Writing and reviewing Quick Reference Guides and Readme documents to support delivery of the software product.
Up to 20% travel is required.
Knowledge Skills and Abilities:
Must have a working knowledge of the Systems Approach to Training/Instructional Systems Design (SAT/ISD) methodologies.
Must have a high functional understanding of computer software, ability to focus on small software behavior anomalies, and be able to articulate software behavior issues in both written and oral means.
Must be familiar with TRADOC 350-70 training development requirements and have experience in the use of TRADOC's Training Development Capability (TDC).
Desirable candidate will have Instructor Certification from any branch of the Military.
Requirements:
BS + 10 years' experience. Additional experience may be used as a substitute for BS degree.
Understanding of Software Process is a plus, but not required.
Candidate must be a US citizen and able to obtain a DoD security clearance.
Benefits
Nobletech Solutions offers competitive salaries and excellent employee benefits, including a company matching 401(k) safe harbor plan. We offer an insurance package that includes medical, dental, group term life, short- and long-term disability, and vision coverage. The company also has a flexible and optional 9/80 work schedule that allows employees to take every other Friday off.

Nobletech Solutions is an Equal Opportunity Employer. Employment decisions are made without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, disability, veteran status or other characteristics protected by law.

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/985249-207062

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
