### ISSUE TITLE
Systems Engineer Lead

### ISSUE THREAD

**Issue by jimscala1** [tech256/jobs#401]
Nobletech Solutions, Inc. is a Service Disabled Veteran Owned Small Business based in Huntsville, AL. We are seeking a Systems Engineer in support of the Systems, Simulation, Software, and Integration (S3I) Directorate. This position is responsible for all systems engineering and management aspect to develop a web-based tool used to schedule operations within the U.S. and bordering countries. This position will interact with stakeholders and other interested parties to determine desired functionality and capabilities of the end product.

Duties and Responsibilities:

Identify system engineering requirements from customer goals and objectives
Develop systems architecture, develop requirements, develop work flow and process flow diagrams, conducting peer reviews, develop schedules, generate program documentation, and manage the software development team.
Develop and execute tests on beta and final products to ensure compliance with requirements.
Requirements:

BS degree in Engineering and 5 years' experience in systems engineering or related experience
Experience writing and maintaining requirements
Good written and verbal communication skills
Ability to successfully manage a small team of software developers
Ability to work independently with minimal supervision
Strong interpersonal skills and reporting practices
U.S. citizen with Secret Security Clearance
Familiarity with DOORS (desired)
Understanding of common tactical data link (TADIL) messages and message interactionsBenefits

Nobletech Solutions offers competitive salaries and excellent employee benefits, including a company matching 401(k) safe harbor plan and competitive insurance package. We have a flexible and optional 9/80 work schedule that allows employees to work a nine-hour day Monday through Thursday to take every other Friday off. Nobletech Solutions strives to being committed to the success of its employees and conducts two annual performance reviews, with both leading to a bonus and/or raise based upon performance and company goals.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/982348-207062

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
