### ISSUE TITLE
Network Engineer / Systems Integrator (#1088358)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#402]
PeopleTec is currently seeking a Network Engineer / Systems Integrator to support our Huntsville, AL location.

 

PeopleTec, Inc., a 100% employee owned company, is currently seeking a Network Engineer/ Systems Integrator to provide support to Integrated Air Defense Systems.

 

Required Skills/Experience:

Skills to design, integrate, maintain and troubleshoot local and wide-area network solutions between multiple platforms and protocols (including IP and VOIP)
Supports/troubleshoots network issues and coordinates for installation of such items as routers, switches, and other ancillary equipment
Operate, monitor, and control the physical data link and transport layers of installed communications and computer systems
Designs and establishes tactical data link services extended over satellite communications systems (SATCOM), as well as point to point IP based services
Ability to diagnose and repair networking problems
Provide support to network equipment and software for multiple network architectures
Perform integration of hardware and software with Cisco equipment
Perform technology research for new technology insertion into Government networks
Experience with Microsoft/Solaris/Linux OS and applications including MS Exchange, Sharepoint and other MS server technologies, networking standards and methodologies
Experience in networking NSA Type 1 encryption devices, VMware, EPO Antivirus Server, MS Active Directory, and Cisco switches, routers, firewalls and intrusion detection/prevention systems
Ability to coordinate with various organizations at the senior level to discuss network architecture to include DISA and the Air Force Life Cycle Management Center
Experience with initiating and monitoring Telecommunication Service Requests (TSR)
Travel: 15%
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A Bachelor's Degree in a related field and 5-10 years of Network/ IT experience is required as well as Comp TIA Security+. 

Desired Skills:

Cisco Certified Network Associate (CCNA)
CompTIA Linux+
CompTIA Network+
Military experience
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1088358-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
