### ISSUE TITLE
GMD Sim Systems Integrator / System Administrator (#1091811)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#407]
PeopleTec is currently seeking a GMD Sim Systems Integrator / System Administrator to support our Huntsville, AL location.

 

PeopleTec is seeking a mid-to- senior Systems Integrator/Systems Administrator to support the GM Sim at Redstone Arsenal. Candidate will: provide systems administrative support on Redhat Linux servers and workstations; perform hardware and software installs in configuration-managed environment; perform integration of GMDSim systems into Hardware In the Loop (HWIL) test suites; troubleshoot hardware and software installations, using RedHat, network and acquired knowledge of the GMDSim software logs and behavior; implement, integrate, and supports Host Based Security Services; implement, integrate and support MultiFactor Authentication; assist team in establishing and maintaining life cycle management processes to manage multiple internal and external systems; support cyber scanning, remediation and patching; contribute to technical Configuration Control Board proceedings and responds to board actions to build, repair, modify or operate GMDSim installations; write, redline and follow Software Installation Instructions (SWII) for GMDSim; write and maintain system documentation such as hardware drawings, lists, software lists, security controls, inventory; and maintain required Systems Administration certifications.

 

Required Skills/Experience:

    Have/obtain certifications that meet DoD 8570 IAT2 compliance
    Security + certification
    Computing Environment (CE) certification
    Travel: 0%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree in Computer Science, MIS or equivalent and 8+ years of experience is required. 

Desired Skills:

      Must be able to obtain a Computing Environment (CE) certification, preferably in RedHat or Linux+ within 6 months

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1091811-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
