### ISSUE TITLE
GMD HWIL Test System Integrator/System Administrator (#1091823)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#408]
PeopleTec is currently seeking a GMD HWIL Test System Integrator/System Administrator to support our Huntsville, AL location.

 

PeopleTec, Inc.  is seeking a Mid-Level Systems Integrator/Systems Administrator to support the GMDSim Hardware in the Loop (HWIL) operating Fire Control (GFC), Virtual In Flight Information Communications (IFICS) Data Terminal (VIDT), Launch Management Systems (LMS), Missile Field Emulator (MFE), and Open Simulation Framework (OSF). Candidate will perform documented installation of systems software, updates and monthly security updates in Linux/Unix environments; Support integration of systems into existing test suite following software updates and changes; Actively support routine test activities, including technical integration, troubleshooting, element operation, and operating elements during test exercises ; Perform hardware installations, troubleshooting, and routine maintenance; Troubleshoot complex systems interfaced together with a team of respective systems administrators; Capitalize on system knowledge to assist network engineers with communications troubleshooting; Provide user support including data directories and account management; Write and maintain system documentation supporting established and evolving configuration management processes; Support hardware management lifecycle care such as inventory audits and reporting, hardware posture and cleanliness, and attention to maintenance of spares inventory; and Acquire and maintains required Systems Administration certifications.

 

Required Skills/Experience:

    Have or obtain both certifications to meet DoD 8570 IAT2 compliance within 6 months
    Security + Certification Computing Environment (CE) Certification, preferably in RedHat or Linux+
    Travel: 0%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree in Computer Science/ MIS or equivalent with 5-10 years of experience is required. 

 

Desired Skills:

    Security+ Computer Environment (CE) Certification (RedHat or Linux+) 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1091823-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
