### ISSUE TITLE
System Engineer Coordinator

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#409]
logo2.png

System Engineer Coordinator

Looking for an excellent opportunity at a CMMI award-winning organization? We have a 100% customer satisfaction rating, a great work environment, and offer competitive benefits.

Cepeda Systems and Software Analysis, Inc. (CSSA) provides software engineering, systems engineering, and process improvement services for our customers. CSSA has achieved a rating of Capability Maturity Model Integration (CMMI) Level 2 for Services and CMMI Level 3 for Development. We have a 100% customer satisfaction rating and have won numerous awards at the local and national level. We treat one another with respect, foster collaboration while maintaining individual accountability, value multiple perspectives, and diverse expertise, and encourage new ideas that surface throughout the organization. CSSA offers a comprehensive and competitive benefits package.

Key Responsibilities:

    Developing organizational tools that assist the team in prioritizing and organizing key tasks and deliverables weekly
    Analyzing schedules for analysis deadlines on the current and future releases of software to determine the prioritization of analysis activities and highlight critical schedule changes
    Candidates should be a success-oriented, resourceful, confident individual who effectively applies lessons learned
    Exhibiting team skills to facilitate technical documentation and coordinate activities to quickly resolve issues

Education and Experience:

    S. /B.A. from accredited University, 1-5 years' experience

Experience Preferred:

    Understanding of the engineering product development lifecycle

Knowledge/Skills:

    Demonstrated experience in one or more areas, is required:
        Reasonable knowledge of engineering technical terms
        Ability to develop internal documentation following specific organizational processes
        Must be a self-starter who knows how/where to go find answers
        Ability to organize and gather technical data and summarize into a technical report
        Capable of creating and enhancing Integrated MS Project Schedules
        Responsible for preparation of forms and attaining appropriate signature approvals
        Must have presentation abilities to support high-level presentations of documentation to multiple levels of governing boards

    Strong communication skills (oral/written) with all levels of the organization)
    Excellent teamwork skills, including working with internal and external departments and organizations

 Knowledge/Skills Preferred:

    Solutions Business Manager (SBM) Serena
    IBM Rational DOORS 9.5 Database
    MS Word/PowerPoint/Excel
    MS Project
    Adobe Acrobat
    SharePoint
    Microsoft Office Suite
    Experience with government standards and requirements

U.S. Citizenship is required

CSSA is an Equal Opportunity Employer

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1092195-194689

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
