### ISSUE TITLE
Software Configuration Management Analyst

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#410]
Software Configuration Management Analyst

Looking for an excellent opportunity at a CMMI award-winning organization? We have a 100% customer satisfaction rating, a great work environment, and offer competitive benefits.

Cepeda Systems and Software Analysis, Inc. (CSSA) provides software engineering, systems engineering, and process improvement services for our customers. CSSA has achieved a rating of Capability Maturity Model Integration (CMMI) Level 2 for Services and CMMI Level 3 for Development. We have a 100% customer satisfaction rating and have won numerous awards at the local and national level. We treat one another with respect, foster collaboration while maintaining individual accountability, value multiple perspectives and diverse expertise, and encourage new ideas that surface throughout the organization. CSSA offers a comprehensive and competitive benefits package.

 Key Responsibilities:

Support Army development processes to include, but not limited to:

    Implement the CCDC AvMC S3I Enterprise Process Improvement and Collaboration (EPIC) methodology to plan, monitor and control projects using well-defined configuration management best practices during design, implementation, deployment and sustainment of complex systems
    Architect, implement, and deploy Software Configuration Management (SCM) policies, and processes to support parallel development
    Design, implement and maintain configuration management deployment and reporting processes which automate code base retrieval, interim and service pack builds, build metric reporting, packaging, and Setup generation
    Establish the Configuration Management (CM) Infrastructure
    Manage/Improve the CM Toolset
    Manage/Troubleshoot the CM Environment
    Define the product and its configuration documentation identification
    Control changes to the product and its configuration documentation
    Provide status and information about a product and its configuration documentation
    Verify consistency of configurations against product documentation
    Perform Builds
    Package/Migrate Releases

Education:  B.S. in Computer Science, Software Engineering, or related discipline

Knowledge/Skills/Experience Required:

    Software Build/Release Management 5-10 years
    Configuration Control 5-10 years
    Software Development Life Cycle 5-10 years
    git 1-5 years
    Strong verbal and written communication skills
    Ability to multi-task in a fast-paced development environment

Knowledge/Skills/Experience Preferred:

    JIRA 1-5 years
    Confluence 1-5 years
    Batch file scripting (PowerShell) 1-5 years
    Ability to work collaboratively with internal and external stakeholders
    Organizational and detail-oriented skills
    Problem solving and analytical skills
    Ability to work in team environment as well as individually
    Ability to adapt to changing situations and requirements

U.S. Citizenship is required

Candidate must be able to obtain and maintain a Secret Security Clearance

CSSA is an Equal Opportunity Employer

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1091169-194689

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
