### ISSUE TITLE
GaN:  Embedded Development\Test Engineer for Missile System

### ISSUE THREAD

**Issue by omegix** [tech256/jobs#412]
# Hiring!

### About Position
C++ Software Developer, supporting the CCDC Aviation and Missile Center, Systems Simulation, Software and Integration Directorate (S3I) located on Redstone Arsenal, in Huntsville, Alabama. 

The candidate will be responsible for design and development of embedded software for military systems. The candidate will perform development activities for the full life cycle of a software program. Duties may include requirements analysis, design, coding, integration, test, documentation, and support. The candidate will also participate in software team meetings, hardware and software design reviews, and technical interchange meetings. The software engineering process also empowers the candidate to work with Cyber, Safety, QC, Operations, and Test organizations to deliver high quality working software. The candidates will work in a team environment, with well-defined goals, supporting both new and legacy embedded systems. The candidate is able to receive timely feedback on software implementation by working directly with the customer, ensuring Agility and delivering a software product that fills immediate needs.

EDUCATION REQUIREMENTS:
·         BS in Computer Science, Computer Engineering, Electrical Engineering, or related technical discipline is required. 5+ years of related experience 
 
REQUIRED SKILLS:
·         C/C++ and other Object Oriented Languages
·         Object Oriented Design methods and practices
·         Strong communication skills (written and verbal)
·         Desire to learn embedded systems concepts and participate in all phases and activities of the software development lifecycle 
 
DESIRED SKILLS:
·         Object-oriented programming and design, including unit testing.
·         Software Development for Embedded Systems
·         Unified Modeling Language (UML)
·         MS Visual Studio (VS2017), VxWorks, Linux, SCM tools
·         Enterprise Architect
·         Agile Development Experience
·         Scrum Experience
·         Certified Scrum Master
·         Working on a cross-functional teams with many engineering disciplines  
·         Continuous Integration and Automation
 
CLEARANCE:
·         Must already have or be able to obtain a SECRET clearance prior to first day of employment. Current SECRET clearance preferred.

Job Responsibilities:
Develop and executes test plans, test cases, and test procedures to ensure that all information systems products and services meet organization standards and end-user requirements.
Develops test plans, test schedule, and approach. 
Writes test cases and scripts and identifies data for test scenarios.
Conducts a walk through on test case/script with Test Managers, Requirement Leads, Project Managers, and Development Leads.
Performs tests of software and/or IT systems to ensure proper operation and freedom from defects.
Performs verification activities on work products using defined methods, procedures and criteria with an appropriate verification environment.
Documents and communicates test results. Supports analysis of test results and resolution of open issues.
Reports progress on problem resolution to management.
 
REQUIRED EDUCATION: Bachelors and five (5) years of test experience is required [4+ years of experience accepted in lieu of degree]. 
 
REQUIRED SKILLS:
-Experience with formal software testing  
-Experience with test tools utilized to simulate data input or capture data
-Knowledge of formal software qualification processes and artifacts 
-Experience creating formal test documentation
-Task and customer oriented
-Demonstrated evidence of initiative and self-starting
-Demonstrated capability to operate in a fast-paced, changing environment with flexibility and a positive attitude
-Strong analytical skills
-Strong written/oral communication skills
-Ability to work in a team environment 
 
DESIRED SKILLS:
-C / C++ / C# Programming Experience 
-Automated Test Station and Report Generation 
-Agile Process experience 
-Technical and tactical experience with M270A1or HIMARS platforms.
 
REQUIRED CLEARANCE:
 - Must be able to obtain and maintain a Secret security clearance 

### Contact
- Tech256: HR@geeksandnerds.com
-- Include that you heard about position from Tech256 Job Board

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
