### ISSUE TITLE
OCONUS Intermediate Level Analyst - International Engineering (#1095548)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#414]
PeopleTec is currently seeking an Intermediate Level Analyst to support our Missile Defense Agency (MDA) International Engineering support operations in the Tel Aviv, Israel location.

 

Job Description: 

Support International Engineering reviews (e.g., requirement reviews, design reviews at various locations in Israel) and programmatic reviews.  Prepare technical summaries, action item status lists, and track actions through closure.  Prepare agendas and technical briefings; coordinate with US and Israeli Government employees and secure approvals.  Prepare meeting minutes and coordinate with technical Points of Contact.  Submit weekly activity reports 

Work is primarily in Israel and may require occasional travel to various locations to include development, integration and test sites within CONUS and OCONUS.

Required Skills/Experience:

Possess an ability to plan, coordinate, and support product development in a fast-paced, rapidly changing environment
Outstanding people, organizational, management and leadership skills
Experience with interacting and supporting high level government customers to include generating briefing and written products and presenting information at the executive level
Capable of working as a team member to solve engineering/scientific problems
Capable of supporting engineering processes across a program acquisition life cycle
Work as a team member and assist with solving complex problems
Supporting technical reviews
Ground and flight test planning and reviews
Proficient in  use the Microsoft Office package to include Outlook, Word, PowerPoint, Excel, and Adobe Acrobat
Ability to obtain a US Passport
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment. 
Education Requirements:

Education/Experience: BS degree with 7 years experience, or 15 years of relevant experience without BS degree.
Desired Skills:

Experience in supporting the design, development, testing, production, or production of missile defense weapon systems or components
Knowledge of the various Upper and Lower Tier weapon systems within the MDA Program Office
Experience working through Failure Review Board process and resolution of findings
Experience identifying technical and program risks and recommending mitigation strategies
Experience with the following skill sets/activities:
IMTP planning, meetings and reviews
Knowledge Point and Technical Performance Measure Lists assessments, compliance, and reports
Generating Test Configuration Sheets and Test Objective Memos
Test review schedules, summaries, and revisions
Test issue identification and resolution (FRT,FRB, JAT, BDRs FRACAS)
Foreign partner test reviews (MRR, FRA, DRR)
Have a US Passport
Unaccompanied status
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1095548-305157

**Comment by GeneralPallas** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
