### ISSUE TITLE
Software Quality Assurance Engineer (#1106805)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#416]
PeopleTec is currently seeking a Software Quality Assurance Engineer to support our Huntsville, AL location.

 

Candidate will support Software Engineering and Development activities for Army Aviation and Missile programs at the US Army AMRDEC Systems, Simulation, Software and Integration (S3I) Directorate. Candidate will develop and assist in implementation of quality programs for hardware, software, and service products and develop a Software Quality Assurance Surveillance Plan and document quality activities in compliance with S3I processes and procedures. The candidate will implement a system and software quality program per the S3I Quality Standard Operating Procedures and other quality processes and procedures, and using ISO 9000-3 as a reference. The candidate will support the Army Materiel Release Process, as documented in Army Regulation 700-142, Type Classification, Materiel Release, Fielding, and Transfer; support S3I's role in software materiel release determinations. Candidate will support S3I's SQA's material release activities, including suitability and supportability assessments, by providing needed project level software data. The candidate will prepare change requests for the S3I quality processes and implement the changes once approved by the S3I Process Configuration Control Board (PCCB) or the S3I Quality Assurance Division Chief, as appropriate Reviews each project's defined process, solicitation, and management plan(s) for conformance to the EPIC process and provides feedback to the Project Leads. The candidate will measure and analyze the effectiveness of the process and develop the organizational QC processes, which a project uses as a basis for their QC activities on a project. Candidate will conduct audits of projects' processes and deliverable products. Candidate will audit the implementation of the QC processes on each project Recommend improvements to the process(es) and assist in development of management plans. The candidate will document process or product deficiencies via Quality Problem Reports (QPRs).

 

Required Skills/Experience:

2+ years related work experience
Demonstrated knowledge of software development life-cycle
ISO 9001-2008 quality management system certifications
Must be able to obtain and maintain a secret security clearance
Travel: up to10%
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A Bachelor's Degree in computer science, information systems, engineering, business, or other related scientific or technical discipline, or equivalent experience is required. 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1106805-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
