### ISSUE TITLE
Senior Cyber Forensics Analyst (#1107772)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#417]
PeopleTec is currently seeking a Senior Cyber Forensics Analyst to support our Huntsville, AL location.

The candidate will conduct analysis of information technology auditing and monitoring logs provided to detect and identify counterintelligence (CI) and insider threat indicators. The candidate will also analyze various logs with multiple tools to attribute observed activity with known cyber threat actors Tactics, Techniques, and Procedures (TTPs), while producing and sharing analytical reports with peer Law Enforcement (LE) and CI organizations 

 

Required Skills/Experience:

3+ years of focused experience in analyzing 2 or more areas of either Windows, Linux, Proprietary Firmware, 32 and 64-bit ARM Chipsets, VMware, and unique MODBUS, 61850, or DNP3 SCADA/ICS
10+ years of experience in Computer Science, Computer Engineering, or Data Science analysis
In-depth understanding of Metadata extraction and analysis
Excellent written and verbal communication skills
Ability to clearly present and communicate technical approaches and findings
Technical and project leadership experience 
Must have current DoD 8570 IAT Level III
Must be able to obtain and maintain a DoD 8570 CND-SP certification
Experience with one or more CND and Analysis tools/applications such as Network Security Manager, Bluecoat, SPLUNK, FireEye, SNORT, Augury, Domain Tools, Microsoft Excel 
Travel: Up to 5%
Must be a U.S. Citizen
An active DoD Top Secret clearance is required to perform this work. Candidates are required to have an active Top Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A Bachelor's Degree (or equivalent) in a related field, OR equivalent educational or professional experience and/or qualifications is required.

 

Desired Skills:

Defensive cyber operations (Blue Team) experience
SCI eligibility 
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1107772-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
