### ISSUE TITLE
.NET Software Developer (#1107831)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#419]
PeopleTec is currently seeking a .NET Software Developer to support our Huntsville, AL location.

The candidate will be responsible for developing .NET solutions supporting on premise applications supporting customer specific needs. The .NET Developers will maintain a strong understanding of industry and enterprise-wide trends. 

Required Skills/Experience:

6+ years of experience in the development of software applications (or related technical discipline)
Proficiency/Experience using Microsoft Visual Studio products: ASP.NET, VB/C#, DevExpress, HTML and CSS, JavaScript, and/or HTML5
Familiarity working in an Agile development environment
Must be able to develop software application solutions based on system design requirements 
Must be able to translate client's business requirements into software development solutions/ designs
Good written and verbal communication skills
Ability to meet project timelines
Travel: Up to 5%
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A Bachelor's Degree in Engineering, Computer Science, MIS or related technical field plus a minimum of 6+ years' experience is required.

 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1107831-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
