### ISSUE TITLE
Full Stack Web Developer Wanted for E-Commerce SaaS Provider

### ISSUE THREAD

**Issue by cara023** [tech256/jobs#42]
# Hiring!

## [Sharp Auction Engine, Inc.](https://sharpauctionengine.com/)
Sharp Auction Engine provides a comprehensive cloud based solution for conducting timed online auctions for auction companies across the country. We are looking to bring on new development positions as we grow our customer base and feature wishlist. 

### About Position

**Title:** Full Stack Web Developer

**Desired Skills:** 
- Basic Linux/Ubuntu/Shell literacy (e.g. grep) 
- Strong proficiency in a webserver+webapp stack (MVC and/or MVVM) and an interest in working on new and existing projects written in: PHP7: Laravel 5.2 Javascript: Nodejs Python3: Flask Golang 
- Solid understanding of Nginx, HTTP, and RESTful application architecture (socket.io is a plus) 
- Solid understanding of Git or similar version control 
- HTML5 frameworks/libraries including: jQuery, VueJS Bootstrap 3 ES6+, React, Aurelia Bower, Gulp, Webpack PhoneGap/Cordova/Electron 
- Relational SQL and Document based Databases including a basic understanding of ACID compliance (transactions) 
- Agile development methodologies -Unit Tests, Adherence to established code standards, Lint style tools 
- Flexibility in Front-End and Back-End roles 
- Ability to work independently and collaboratively 
- Ability to communicate design rationale and build consensus 
- Ability to prioritize and manage work to critical project timelines in a fast paced environment 
- Ability to develop new approaches to complex design problems 
- Must be organized, have eye for detail, and be able to put ideas into a tangible form 
- Must be able to take directions and be fluent in English. 

### Contact
- Tech256: @socianado
- Location: Huntsville, AL

**Comment by iamvery** [comment]
@cara023 still relevant?

**Comment by cara023** [comment]
Yes sir.

________________________________

**Comment by mjcarroll** [comment]
@cara023 still relevant?
