### ISSUE TITLE
Entry Level Database Developer

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#422]
Entry Level Database Developer

 Looking for an excellent opportunity at a CMMI award-winning organization? We have a 100% customer satisfaction rating, a great work environment, and offer competitive benefits.

Cepeda Systems and Software Analysis, Inc. (CSSA) provides software engineering, systems engineering, and process improvement services for our customers. CSSA has achieved a rating of Capability Maturity Model Integration (CMMI) Level 2 for Services and CMMI Level 3 for Development. We have a 100% customer satisfaction rating and have won numerous awards at the local and national level. We treat one another with respect, foster collaboration while maintaining individual accountability, value multiple perspectives, and diverse expertise, and encourage new ideas that surface throughout the organization. CSSA offers a comprehensive and competitive benefits package.

 Key Responsibilities:

Support Army development processes to include, but not limited to:

Design and develop schemas, tables, views, stored procedures, functions, and packages
Extract data and import into tables
Monitor database procedures and jobs
Write a variety of scripts, batch processes, SQL and PL/SQL queries
Work closely with customers and front-end developers to determine data requirements
Perform functional database testing, performance tuning, and optimization
Develop database documentation
Education Requirements:

B.S. in Computer Science, Software Engineering, MIS, CIS, or related discipline
Preferred Experience:

TOAD 1+ years
SQL Developer 1+ years
Hadoop 1+ years
Denodo 1+ years
Knowledge/Skills Required:

Oracle 1+ years
 Preferred Knowledge/Skills:

 Ability to work collaboratively with internal and external stakeholders.

Organizational and detail-oriented skills.
Problem-solving and analytical skills.
Ability to work in a team environment as well as individually.
Ability to adapt to changing situations and requirements
Licenses/Certifications Required:

CompTIA Security+ CE
Database certification (Oracle preferred)
U.S. Citizenship required.

Secret Security Clearance will be required but can be obtained on the job.

CSSA is an Equal Employment Opportunity Employer. We do not discriminate in the employment of individuals on the basis of race, color, sex (or pregnancy), religion, age, national origin, disability, veteran status, sexual orientation, gender identity, genetic information, or any other protected category. CSSA hires and promotes individuals solely on the basis of their qualifications for the job to be filled. If you require assistance with the application process, please contact us at careers@cepedasystems.com. We appreciate your interest in our organization.

CSSA participates in the E-Verify program.

Criminal background checks are conducted on all applicants before hire.

CSSA is a Drug-Free Workplace.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1109515-194689

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
