### ISSUE TITLE
Joint Interface Control Officer (JICO) (#1113716)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#426]
PeopleTec is currently seeking a Joint Interface Control Officer (JICO) to support our IAMD efforts in Huntsville, AL location.

 

Job Description:

Responsible for planning and management of the Joint TDL network for the IAMD air picture. 
Identify the architecture, systems and associated tactical data required to integrate the IAMD Air Picture into the Multi-Tactical Data Link Network (MTN). This includes identification of the  physical configuration, functional organization, and operational procedures used in the design, establishment, modification, and operation of TDL networks and associated voice circuits.
Assess interoperability within the J-series family of tactical data links (TDLs), including Link 16, Situational Awareness Data Link (SADL), Link 22, North Atlantic Treaty Organization (NATO) Improved Link Eleven (NILE), Variable Message Format (VMF), Common Message Format (CMF),Integrated Broadcast Service (IBS), and Interim Joint Tactical Information
Distribution Systems (JTIDS) Message Specification (IJMS).
Coordinate updates to the Joint Track Management for Air and Cruise Missile Defense Handbook, IAMD-HDBK-0001, dated 9 August 2018:  Lead a 16-person Joint Track Management Capability Standards Working Group (JTMC STD WG) consisting of subject matter experts from the Missile Defense Agency (MDA), MITRE, Georgia Tech Research Institute (GTRI), John Hopkins University Applied Physics Laboratory (JHU/APL), and Numerica. 
Coordinate updates to the Network Management Capability (NMC) Initial Capabilities Document (ICD) to include:  staffing through Functional Capability Boards (FCB) and Joint Requirements Oversight Council (JROC) as required.
Coordinate assessment of MDA Achievable Capabilities List (ACL) to generate recommended response to the Prioritized Capabilities List (PCL) with respect to integration and interoperability, including network capability of the IAMD Network.
Support exercises and wargames as the IAMD Joint System Engineering Team representative. Identify suggested changes for future joint operations. 
 

Required Skills/Experience:

10 years of experience serving as a JICO
Travel: 20-30%
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are preferred to hold a current Top Secret clearance, or have held a Top Secret clearance within the last 5 years.
 

Education Requirements:

Bachelor's Degree in Engineering, Physics, mathematics or computer science with at least 7 years experience
OR

Associates Degree in an applicable area with 15 years of experience
 

Desired Skills:

MA/MS in Engineering, Mathematics, Physics, or Computer Science
MDA experience
Missile defense system performance
Experience with interacting and supporting high level government customers to include generating briefing and written products and presenting information at the executive level
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1113716-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
