### ISSUE TITLE
Embedded Software Engineer (#1115186)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#427]
PeopleTec is currently seeking an Embedded Software Engineer to support our Huntsville, AL location.

 

The candidate will support the Army's Crew Mission Station (CMS) program initiatives.The successful candidate will implement Agile, Model Based Engineering (MBE) processes for the development of a modular open system architecture (MOSA) and software to produce the CMS product in line with Open Systems Architecture approaches.

 

The candidate will be responsible for the following tasks:

    Support program plans to govern the processes and practices used within the CMS Project
    Support trade studies to determine the software to support our process and product needs
    Support trade studies to evaluate potential COTS hardware for use as product solutions
    Support requirements analysis and development
    Support system design, functional allocation of hardware, software, and other segments and system components
    Support the development of system integration plans, procedures and scenarios used in the conduct of software and hardware system integration testing, and perform analysis of integration results to assess system impacts
    Support customer requirements in airworthiness goals and objectives.

 

Required Skills/Experience:

    Experience in modeling avionics and real time systems 
    Ability to work in a C++ environment using interactive techniques through Rhapsody
    Travel: 0%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree and 5+ years of experience; a Master's Degree and 3+ years of experience; OR a PhD with 0+ years of experience is required.

 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1115186-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
