### ISSUE TITLE
System Administrator [deciBel Research]

### ISSUE THREAD

**Issue by spearna** [tech256/jobs#43]
# Hiring!

### About Position
Seeking: (see link above)

### Contact
- Tech256: @spearna
- Location: Huntsville, AL
- Also, apply via the website above.

---

Position Description:
deciBel Research is seeking a System Administrator experienced in large/complex software development environment maintenance and operations, running on Linux and Windows operating systems. The development environment is centered on the IBM Rational Suite with a number of ancillary software tools to support the full Software Lifecycle Development Cycle (SLDC); from Systems Engineering requirements management through design, development, testing and deployment. The development environment is highly tailored and maintained in compliance with strict DOD security policies and procedures in support of the Objective Simulation Framework (OSF) development in for Missile Defense Agency (MDA) Ballistic Missile Defense System (BMDS) Test and Evaluation (T&E) in Huntsville, AL. The System Administrator will be responsible for administration of Linux and various Windows platforms, Linux RHEL 5 and 6, IBM Rational Suite, ancillary development tools (e.g., MATLAB, static code analyzers, etc.), Integrated Development Environment (IDE) suites (e.g., Eclipse, NetBeans), UNIX script development and maintenance, and development environment user account management. Will be responsible for loading and supporting development environment software and Government off the Shelf (GOTS) products. Will also coordinate efforts with prime contractor network and Information Assurance (IA) responsible parties and support various development Integrated Product Teams (IPT) to develop changes to the development environment. Must have good communication skills and able to work on multiple projects and resources to meet high-demand objectives. Must be exceptional in a team environment with the ability to articulate technical terms and concepts to non-technical people. May occasionally be required to work extended and/or off-nominal hours and be able to lift 35lbs.

Education Requirements:
Bachelor's degree in Information Technology or related discipline.

Experience Requirements:
The successful candidate will possess at least 5 years of experience with various Linux and Windows operating systems, IBM Rational Suite, and related networking (TCP/IP, DNS, Active Directory). Must have CompTIA Security+ with continuing education prior to hire. Must have the ability to work and excel in a team-oriented collaborative environment that is fast-paced and constantly changing. Must also possess outstanding customer service skills and a dedication to the customer service experience.

Special Skills Desired:
Knowledge/experience with one or more of the following: 1) Modeling and Simulation, 2) Real time Linux kernels, tuning and performance analysis, 3) GPUs, or 4) High Performance Computing Systems (rack mount, blade servers, etc.) Knowledge of system level and integration level testing. Microsoft/Linux certifications and experience in software development tools management.

Applicant selected will be subject to a government security investigation and must meet eligibility requirements for access to classified information. Must be a U.S. Citizen. Minimal travel may be required.

**Comment by jmnielsen7** [comment]
@spearna 
Hello, 

I am interested in applying for this position. How would you prefer that I submit my resume to you for this? You may find my LinkedIn profile here: https://www.linkedin.com/in/nielsenjoshua

Thank you,
Joshua Nielsen

**Comment by spearna** [comment]
@jmnielsen7  Sorry for the late response.  You have to submit your resume through the website.  Let me know when you do and I'll drop HR a line.

**Comment by jmnielsen7** [comment]
@spearna Thank you Neil. I have completed the application through your website now. I listed you as the person who I heard the job listing from.

-Josh Nielsen

**Comment by iamvery** [comment]
@spearna still relevant?

**Comment by spearna** [comment]
It's still listed on the current openings.
