### ISSUE TITLE
Javascript Developers

### ISSUE THREAD

**Issue by archanam88** [tech256/jobs#431]
Bentley Systems has exciting and challenging opportunities for Full-Stack Javascript Developers who are passionate about using cutting-edge technologies that enable our users to solve mission critical problems, save time, and greatly reduce costs related to transportation infrastructure. You will be involved in all aspects of the software development lifecycle and will exercise end-to-end ownership over important features of a new web-based product. You will leverage modern languages such as TypeScript and Go, and technologies such as Docker and Azure in a fast-moving, agile, friendly, and supportive environment. You will be a valuable member of a team that is leading the way in delivering solutions that solve some of the transportation industry’s most important challenges.

# Responsibilities
- Work closely with product management, development leads, and your peers to complete required tasks
- Participate in the design and development of new features using TypeScript and other languages
- Write well-tested, well-documented code and APIs, and participate in code reviews
- Provide and accept constructive feedback
- Commit yourself to continuous learning and adapting to and integrating new technologies 

# Required Skills
- BS in Computer Science, Engineering, Mathematics, or related field OR extensive portfolio demonstrating equivalent qualifications
- Minimum 2 years’ full-time professional software development experience
- Proficient in JavaScript or TypeScript and at least one other language
- Experience working with Git or other distributed version control system (such as Mercurial)
- Excellent verbal and written communication skills
- Ability to work independently and solve problems, and to know when to ask for help
- Ability to learn new technologies quickly, and apply them in production 

# Desired Skills
- Experience designing REST APIs using Open API standards
- Understanding of Docker, Kubernetes, Service Mesh and related technologies and concepts
- Experience using Visual Studio Code
- Experience working on a Scrum team
- Experience using React or other front end JavaScript framework
- Experience using Node.js and Express or other server technologies
- Knowledge of distributed systems, their benefits, and their drawbacks 

# What We Offer:
- A challenging, friendly, helpful, and supportive team environment
- Competitive salary and benefits
- The opportunity to have a big impact in a growing team
- The opportunity to learn and grow as a software engineer

# Job Location
Huntsville, Alabama, United States

# Contact
- Tech256: (at)Archana Maharjan 

# Apply Here
https://www.linkedin.com/jobs/view/1334412307?trk=cap_redirect

**Comment by tylerbhughes** [comment]
@archanam88 Note the changes I made to your posting. In the future, please post the entire posting. We want to make it is easy for people to identify if they want to apply to a position without them having to follow a bunch of links.

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
