### ISSUE TITLE
Safety Engineer (#1122131)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#434]
PeopleTec is currently seeking a Safety Engineer to support our Huntsville, AL location.

 

The candidate will plan, manage, coordinate, and evaluate a comprehensive system safety program for an Aviation/Weapons System.

 

Duties include:

    Conduct meetings with internal PMO Staff, matrix support personnel, and contractor personnel to determine status of safety programs, budgets, costs, schedules, and accomplishments 
    Take appropriate action to correct deficiencies and/or improve program status
    Evaluate contractor system safety and health hazard reports for technical competence, completeness and accuracy 
    Provide and advise the Government with recommended changes to contractor's documentation based on evaluations
    Lead, guide, and mentor workforce in dealing with complex problems associated with system safety
    Lead/Co-Lead System Safety Working Group and Safety IPTs
    Ensure compliance with the requirements of applicable safety regulations and industry standards
    Prepare, review, and approve major reports and / or policies for internal and external distribution

 

Required Skills/Experience:

    Experience with reliability, quality, and airworthiness
    Experience analyzing safety regulations and standards and developing mitigation plans and strategies
    Knowledge of DoD acquisition and life cycle management policies, procedures and practices
    Experience and knowledge with commercial and military safety standards, practices, and regulations such as: MIL-STD-882E, AR 385-10, AMCOM 385-17, RTCA DO-178C, SAE ARP 4754A, SAE ARP 4761, etc.
    Ability to manage complex developmental and engineering projects, work effectively with others and manage multiple projects simultaneously
    Ability to research, report and troubleshoot propulsion/engine related issues
    Travel: 25%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

3-10+ years of relevant Aviation/ Engineering work experience is required.

 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

[](https://www.applicantpro.com/j/1122131-305157 )

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
