### ISSUE TITLE
Part-Time Logistics Analyst (#1127632)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#437]
PeopleTec is currently seeking a Part -Time Logistics Analyst to support our Huntsville, AL location.

PeopleTec, Inc. is currently seeking a Logistics Analyst to work part time (approximately 1000 hours per year) on the Standardization and Evaluation Assistance Team (SEAT). The candidate will support on-site Inspections of National Guard chemical, biological, radiological, and nuclear Response Units and requires significant travel to accomplish.

 

Required Skills/Experience:

Military Logistics support systems
Property accountability
Government Purchase Card
Must be able to operate a computer, and printer
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A completed Bachelors Degree in a related field and 10 years of Military logistics experience are required. Additional Military experience may be substituted for degree requirements.

 

Desired Skills:

Subject Matter Expert in logistics providing support or oversight to National Guard Civil Support Teams (CST), Chemical, Biological, Radiological, Nuclear, and high-yield Explosive (CBRNE) Enhanced Response Force Package (CERFP) and Homeland Response Force (HRF).
Experience working with the Army or Air National Guard
Experience with State National Guard Headquarters or the National Guard Bureau
Military Education in logistics
Proficient in using Microsoft Office Software
Familiar with CoMSUPCEN
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1127632-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
