### ISSUE TITLE
Web Developer/Administrator

### ISSUE THREAD

**Issue by clayhilton** [tech256/jobs#442]
Trident Technologies has an opportunity for a full-time Web Developer/Administrator to work remotely on our contract with the United States Army Corps of Engineers (USACE) Engineering Research and Development Center (ERDC) Research and Development Environment (RDE).

There are 3 options for this position:
1. Full time onsite in Trident Technologies Corporate office
2. Full time onsite at USACE ERDC Vicksburg
3. Telework with travel to Vicksburg approx 3 times a year.

This position involves web site development and providing web site integration and administration assistance to USACE ERDC customers.

# Duties
- Web development using one or more of the following technologies: HTML, CSS, Javascript, PHP, .NET, Django, Rails, CMS (Drupal, WordPress)
- Manage web servers and web applications to include:
- Application architecture
- Installation and initial configuration
- Access control and user management
- Database connections and configurations
- Version upgrade planning and executing
- Performance optimization
- Troubleshooting and issue resolution
- Manage web applications in a virtual server environment
- Design and maintain testing environments for applications

# Required Skills
- Possession of or ability to obtain CE or SA type certification such as MCSE, RHSA, VCP, or CCNA (within the first year of employment)
- Web development experience with a language such as Java, JavaScript, Python, PHP, or Ruby
- Experience managing IIS in a business environment
- Experience creating and managing connections to Microsoft SQL databases and configuring SQL databases to support application requirements
- Experience managing web content utilizing content management systems such as WordPress or Drupal
- Must have strong problem-solving and troubleshooting skills
- Capacity to learn and implement new technologies utilizing product documentation, web resources, and product support channels
- Provide in-depth troubleshooting and technical support for web applications running on Windows and Linux based server systems.
- A solid understanding of Git version control
- The ability to communicate effectively with other technologists and business stakeholders

# Required Experience
- 4+ years’ experience managing Web based applications in a Windows business environment
- 4+ years’ experience with Windows server operating systems in a business environment

# Education Requirements
- 4 Year degree from an accredited college or university with relevant coursework or equivalent experience
- Possession of or ability to obtain CompTia Security+ or CISSP certification (within the first 6 months of employment)
- Possession of or ability to obtain CE or SA type certification such as MCSE, RHSA, VCP, or CCNA (within the first year of employment)

# Desired Requirements
- Active US government secret clearance
- 2+ years experience managing IIS, LAMP or LEMP stack
- Experience with PowerShell and/or VBScript
- Experience managing Microsoft Active Directory
- Experience with .Net framework
- Experience with smartcard or other 2 factor authentication models
- Experience managing Linux based server operating systems such as Red Hat, CentOS, or Ubuntu
- Experience managing applications to support development such as Github, JIRA, and Visual Studio
- Experience working with Container platforms such as Docker
- Experience working with web applications in a cloud environment such as AWS or Azure
- Must be able to obtain and maintain a DOD SECRET clearance

Trident Technologies offers a competitive salary, excellent benefits, and a professional work environment.
Trident Technologies is an Affirmative Action, Equal Opportunity Employer
EOE/Minorities/Females/Vet/Disabled/Gender Identity/Sexual Orientation 

See job details and required experience at link below:

https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=79069ba8-b660-4655-813b-d2cafec18d3c&ccId=19000101_000001&jobId=270436&lang=en_US&source=CC4

**Comment by GeneralPallas** [comment]
@clayhilton I have edited your post to include the full job details here. In the future, please post all job details here so people can quickly identify if the position is something they are interested in. We want to be as transparent as possible with the posting made in this repository.

**Comment by clayhilton** [comment]
Thank you for making this change for me.  Will make sure to do this going forward.

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
