### ISSUE TITLE
Senior Technical Advisor - AICET (#1129769)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#443]
PeopleTec is currently seeking a Senior Technical Advisor - AICET to support our Huntsville, AL location.

 

Candidate will serve as the Senior PeopleTec Technical Representative on the AICET Team.

 

Responsibilities Include:

    Coordinating with the Team Program Manager to discuss, plan and recommend technical direction for the AICET Program
    Keeping abreast of all AICET Technical developments, results, and issues
    Organizing quarterly technical reviews with corporate leadership to ensure timely updates to Congressional leaders
    Interacting with Government Customers in the IAMD Program Office and above
    Stepping into support technical developments/analyses as a System Matter Expert

 

Required Skills/Experience:

    Experience in Integrated Air and Missile Defense (IAMD) or Integrated Air and Missile Defense Battle Command System (IBCS) development; this includes expertise in at least one of the components: weapon system, sensor, or network that comprise IBCS
    Candidate must have experience with leading team members in the execution of system engineering disciplines to include initial requirement definition
    Travel: 10-15%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's degree in Engineering, Mathematics, Physics or Computer Science OR a Master's degree in Engineering, Mathematics, Physics, Computer Science, or related technical field is required. 10+ years of experience is also required.

 

Physical Job Requirements:

Candidate must be able to drive to the Torch Lab and to other buildings in the local area.

 

Desired Skills:

    Top Secret clearance 
    Integrated Air and Missile Defense (IAMD) Program Office experience
    Experience with Model-Based System Engineering
    Any formal engineering certifications

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1129769-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
