### ISSUE TITLE
Mid- level Software Engineer (#1130505)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#445]
PeopleTec is currently seeking a Mid-level Software Engineer to support our Huntsville,AL location.

 

The candidate will support the design, development and integration of software systems to support Army weapon systems. Candidate will be responsible for working with the systems engineering team and software architect to develop a software application that will operate in a deployed environment across tactical networks. Effort includes: integration of legacy software components, modification of existing software components into interfaces and languages that are compatible with the overall architecture, and development of new software modules. Candidate will also be responsible for designing, writing, and testing the software components.

 

Required Skills/Experience:

Detail-oriented with strong communication skills
Background in safety- and security-critical systems
C/C++, Java, Windows and Linux OS
Experienced in developing applications for military systems
Experienced working within an integrated development environment and using tools such as: Eclipse, Git, Jira, SVN, and  Redmine
Experienced working within a CMMI ML3+ environment
Experienced in applying Lean principles to various software lifecycle models (Agile, Spiral, Waterfall)
Travel: Up to 5%
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A Bachelor's degree in Computer Science, Software Engineering, or related field with 5-10+ years of experience is required.

 

Desired Skills:

Lisp, Python, Fortran, C#, Matlab, Exata, QT Front-end / Graphical User Interface development experience
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1130505-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
