### ISSUE TITLE
Senior Software Architect (#1130519)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#446]
PeopleTec is currently seeking a Senior Software Architect to support our Huntsville, AL location.

 

The candidate will support design and integration of software systems in support of Army weapon systems. The candidate must be able to effectively interface with the systems engineering team, the warfighter, and the engineering SMEs. Candidate will be responsible for designing and developing a software application that will operate in a deployed environment across tactical networks. Effort includes: integration of legacy software components, modification of existing software components into interfaces and languages that are compatible with the overall architecture, and development of new software modules. The candidate will work with the systems engineering team to define the system requirements, design a compliant architecture, and then work with developers on the team to integrate/develop software components. 

 

Required Skills/Experience:

C/C++, Java, Windows and Linux OS
Experienced in developing and maintaining micro services
Experienced in developing applications for military systems
Strong written and oral communication skills
Experienced with establishing and developing within an integrated development environment and using tools such as: Eclipse, Git, Jira, SVN, Redmine
Experienced working within a CMMI ML3+ environment
Experienced in applying Lean principles to various lifecycle models (Agile, spiral, waterfall)
Detail-oriented
Strong communication skills
Possess a seasoned background in safety- and security-critical systems
Travel: 5-10%
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A Bachelor's degree in Computer Science, Software Engineering, or related field is required as well as 10+ years of experience is required.

 

Desired Skills:

 Lisp, Python, C#, Matlab, Exata, QT Front-end development experience
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1130519-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
