### ISSUE TITLE
Information System Security Officer (ISSO) (#1132894)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#447]
PeopleTec is currently seeking Information System Security Officer (ISSO) professionals nationwide in support of the Air National Guard. 

 

The ISSO is responsible for ensuring the day to day requirements for maintaining the security posture of all information systems is accomplished. The ISSO will work closely with unit personnel to implement a government approved viable network security program at each location.  In addition, they shall aid site ISSM's and System Administrators in the daily administration of the unit's mission secure computer systems.

    Ensures access and permissions to information systems is limited to only authorized individuals.
    Ensures proper protection of information systems and immediately implements corrective measures when a system incident or vulnerability is detected.
    Ensures information systems are operated, maintained and disposed of in-accordance-with applicable Department of Defense, National Guard Bureau, Air National Guard and unit policies, directives, and procedures.

 

Required Skills/Experience:

    Experience with Air National Guard systems administration or computer security management preferred.
    Certification: DoD IAM Level 1 Certification is required, or equivalent Security+ or Security+ CE.
    Experience with ORACLE, SUN, CISCO, UNIX, LINUX.
    Travel: 5%
    Must be a U.S. Citizen
    An active DoD TS/SCI is required to perform this work. Candidates are required to have an active Top Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1132894-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @GeneralPallas.
