### ISSUE TITLE
Human Resources Generalist

### ISSUE THREAD

**Issue by EOS-Defense-USA** [tech256/jobs#448]
We are a U.S. Manufacturer of cutting edge, precise remote weapons stations.

Our employees say... "Great Environment. Excellent Team."

Now Hiring
HR GENERALIST
Can you help shape the culture of a new company? Build your own department?

Uphold the company principles of: Leadership, Relationships, Innovation & Reward and Recognition

Think you have what it takes to...

Provide Human Resources support to ensure compliance with corporate programs, policies, and employee handbook
Manage Talent Acquisition
Handle Pre-Hire and New Employee On-boarding Process
Employee Relations
Ensure legal compliance with Federal/State/Local laws
Develop In-House Talent
Administer Benefits & Compensation
Position reports directly to President.

REQUIRED:

Bachelor's degree in Human Resources, Business Administration, Organizational Development, or other related discipline (or equivalent work experience)
Minimum of 1 year of experience in an HR Generalist role covering all major areas of HR
Minimum of 3 or more years of experience in any HR Role
Broad knowledge of HR employment law, policies/practices, recruiting and benefits
Software proficiency with Microsoft Office Suite (especially Word and Excel)
Previous experience with an Applicant Tracking System (ATS) suite
SKILLS THAT ARE A PLUS:

Experience with HR in manufacturing environment
Experience directly supervising others
Experience with Government Contractors
Masters Degree
HR Certification
Demonstrated success implementing HR initiatives
Previous experience with ApplicantPro ATS
WHAT WE CAN OFFER YOU:

 

Compensation package with Medical/Dental/Vision, Life Insurance, Paid holidays & PTO, 401(k) retirement plan with competitive match, Professional development reimbursement, and more!
Driven, team-environment
Advancement Opportunity
9/80 Work Schedule
Guidance & limited training by Third party HR Consultants
 

 

 

EOS Defense Systems is an Equal Opportunity Employer

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1136096-397274

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
