### ISSUE TITLE
Senior Information Assurance / Network Administrator (#1136339)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#449]
PeopleTec is currently seeking a Senior Information Assurance / Network Administrator to support our Huntsville, AL location.

 

PeopleTec is seeking a Senior Information Assurance / Network Administrator to support multiple programs on Redstone Arsenal, AL. The successful candidate will perform Information Security System Manager (ISSM) and similar duties for multiple networks. The successful candidate will have significant and demonstrated knowledge of Military network architectures and processes at multiple classification levels. The successful candidate will also have demonstrated experience developing and staffing Risk Management Framework (RMF) packages for networks and enclaves. 

 

Required Skills/Experience:

    Demonstrated experience as an Information Assurance Manager 
    Required Certifications include: CISSP, Security + and at least one operating system-specific certification
    Experience in network architecture, installation, and maintenance across multiple classification levels
    Experience with software scanning and accreditation analysis
    Travel: Up to 5%
    Must be a U.S. Citizen
    An active DoD Top Secret clearance with SCI eligibility is required to perform this work. Candidates are required to have an active Top Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

Required experience varies with education level. Candidates with a MS/MA or equivalent require 10+ years of demonstrated experience. Candidates with BS/BA or equivalent require 18 years of experience. Candidates without a degree require 22 years of experience.

 

Physical Job Requirements:

The ability to lift up to 20 lb is required. The physical ability to install, inspect and maintain computer systems, networks, and wiring in enclosed spaces is also required.

 

Desired Skills:

    Software development experience 
    Certification as a Certified Ethical Hacker (CEH)
    Network and/or communications experience in uniformed service

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1136339-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
