### ISSUE TITLE
Network Engineer & Administrator (#1136358)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#450]
PeopleTec is currently seeking a Network Engineer & Administratorto support our Huntsville, AL location.

The candidate will serve as the network engineer and administrator supporting an Army program.  Candidate will be responsible for end to end design, implementation, installation, administration, configuration management and Risk Management Framework compliance for a classified network supporting software development and test, including high performance computing. Candidate will demonstrate high level of proficiency in Linux/UNIX, Networking, High Performance Computing, and Microsoft products. It will be the candidate's responsibility to ensure configuration management is maintained and successful DOD Authorization to Operate (ATO) is attained in the future. All systems configurations must comply with DOD required baselines. 

 

Required Skills/Experience:

    Security + w/CE or Higher DOD 8570 required certification
    Linux+ w/CE or like Linux certification
    Experience administering an enterprise network environment Scripting (Bash, Python, Perl)
    Ability to qualify for a TOP SECRET/(SCI) clearance in the future
    Demonstrate a high level of proficiency in ports, protocols, and services for each operating system and device implemented
    Team player and comfortable with presenting briefings, interacting with senior government officials and other developers and analysts
    Travel: 10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

5-10 years of experience and a Bachelor's Degree, or equivalent experience, is required. 

 

Physical Job Requirements:

Candidate must be able to lift and move computer equipment.

 

Desired Skills:

    Top Secret clearance
    Prior military experience with tactical networks such as: C/C++, JavaScript, CISSP, RHCE, CCNA ,HPC (High Performance Computing) background/experience
    Master's degree or demonstrated acceptable years of experience

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1136358-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
