### ISSUE TITLE
Senior Truth Model Engineer (#1140016)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#453]
PeopleTec is currently seeking a Senior Truth Model Engineer to support our Huntsville, AL location.

 

Duties include:

    Support integration, enhancements, testing, and analysis for truth models and truth model interactions in the Objective Simulation Framework
    Design, develop, document, test, and debug software in common programming computer languages
    Apply appropriate standards, processes, procedures, and tools throughout the development life cycle
    Ensure software standards are met
    Perform system engineering functions, to include: requirement engineering, architecture modeling, system architecture development, and trade studies
    Perform technical planning, system integration, verification and validation, cost and risk, and supportability and effectiveness analyses
    Perform functional analysis, timeline analysis, detail trade studies, requirements allocation and interface definition studies to translate customer requirements into hardware and software specifications

 

Required Skills/Experience:

    Experience with truth models
    OSF integration and testing
    OSF event support and analysis 
    Viewed as a senior authority in discipline
    Travel: 0%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree in Engineering or Physic with 20+ years of experience is required.

 

Desired Skills:

     Agile processes 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

[](https://www.applicantpro.com/j/1140016-305157)

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
