### ISSUE TITLE
Management-HR Analyst/Specialist (#1140950)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#455]
PeopleTec is currently seeking a Management-HR Analyst/Specialist  to support our Huntsville, AL location.

 

Responsibilities Include:

Extreme professionalism to screen all visitors and telephone calls, requests for information, and meetings
Manage MS Outlook calendars including: unclassified and classified meetings, teleconferences, and video teleconferences
Interface with a diverse group of internal and external stakeholders at all levels within the Army and Department of Defense (DoD)
Use independent judgement to plan, prioritize and organize a diversified workload in a high-pace and detail-oriented environment
Apply their extensive knowledge of the Microsoft Office Suite of products to develop: numerous PowerPoint briefings, Excel spreadsheets, and documentation developed utilizing Word and Adobe Acrobat
Update senior staff members on and coordinate civilian actions
Prepare forms related to recruitment, promotion and reassignment of civilian personnel
Coordinate Personnel Evaluation system actions and maintain related statistics
Review, monitor, and update civilian information databases
Monitor training requirements to ensure mandatory requirements are met
Report and document a variety of personnel actions
Monitor status of government employee Performance Plans
Maintain confidentiality when dealing with personnel records
Responsible for providing guidance related to the administration, communication, management and planning for related Human Resources support activities
Understand related policies and procedures and take initiative on routine work
Recognize the need for and establish permanent and temporary files of important classified and unclassified projects and correspondence including official and unofficial correspondence
Responsible for arranging travel using the DoD Defense Travel System (DTS) to include: travel itineraries, hotel, transportation, TDY agendas, briefing packets, and ensure that vouchers are submitted in a timely fashion for settlement of the traveler's government travel card
Responsible for assisting in the administration of the Automated Time Attendance and Production System (ATAAPS)
 

Required Skills/Experience:

Active DoD Secret clearance upon hire and the ability to maintain this level of clearance during their employment
Must have a high degree of professionalism and experience in a fast-paced work environment
Must be able to perform in a highly dynamic work environment supporting multiple military, government civilian, and contractor team members
5+ years Human Resources experience
Experience with performance review processes
Travel: 0%
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A Bachelor's Degree in Human Resources or an equivalent field is required. An additional 6+ years of related experience may be substituted in lieu of degree. Higher level of degree in related field may be substituted in lieu of experience.

 

Desired Skills:

 Prior government contracting and experience in federal civilian human resources 
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1140950-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
