### ISSUE TITLE
Software Development Team Lead (#1157876)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#459]
PeopleTec is currently seeking a Software Development Team Lead / .NET Developer to support our Huntsville, AL location.

 

PeopleTec is seeking an experienced software development lead / .NET Developer to contribute and manage a software development team and environment in support of emerging requirements supporting our government customers.  The successful candidate will thrive in a fast-paced environment and be passionate about building software in line with industry best practices and mentoring others to do the same.  Lead a software development effort inclusive of multiple developers, applications and languages.  The successful candidate will:

    Be able to program in multiple languages from highly structured to object-oriented.
    Manage and maintain an integrated requirements and configuration management system.
    Oversee use of the system by all assigned developers.
    Configure and maintain compiler and debugging environments.
    Leverage and improve corporate processes, and maintain an integrated development schedule with risk management.
    Be responsible for developing .NET solutions, supporting both on premise and cloud applications, supporting customer-specific data analysis, and software development efforts.
    Maintain a strong understanding of industry and enterprise-wide trends.
    Work with team that may include Client Stakeholders, Project Managers, Business Analysts, Front-end Developers, Database Application Developers and .NET/Web Developers.

    Drive, lead, motivate the agile team members to build complex software in an Agile/Scrum environment and apply iterative software development Scrum practices.

    Drive the values and practices of Scrum, coaching the team, jumping in to help with all aspects of each Sprint and driving the best outcome.

    Coach and mentor developers; contribute as a lead developer on an agile team.

    Tasks performed require integrating software packages, cloud services and network solutions, including highly complex application components and reusable objects residing on multiple platforms.

    Ensure team delivery of high-quality software by writing clean code, utilizing automated unit tests, continuous integration, and code reviews.

    Collaborate with project managers, product owners, designers, and other developers to deliver business value on an iterative basis.

    Translate business and functional requirements into documented user stories, technical tasks, and / or diagrams, i.e., wire diagrams, use cases, etc.

    Work with the project manager and product owner to make sure the product backlog is in good shape and ready for the next sprint.
    Facilitate & lead walkthroughs, backlog grooming sessions, and demos of technical specifications, code, and deliverables with other members of the technical team.

 

Required Skills/Experience:

    Current DoD Directive 8570.01 Baseline Certification meeting IAT Level II requirements.
    5+ years of relative work experience using Microsoft Visual Studio products: ASP.NET, DevExpress, HTML and CSS, JavaScript, and/or HTML5.
    5+ years of relative work experience using Microsoft SQL Server:  Data Modeling, Stored Procedures, SQL Agent Jobs, and SSIS Packages for ETL.
    Experience working in an Agile SCRUM environment.
    Demonstrated experience with automated and linked requirements management and configuration management systems.
    Experience configuring development environments in Windows operating systems.
    Demonstrated experience with corporate-level software development processes.
    Must be able to develop software application solutions based on system design requirements.
    Must be able to translate the Program Managers and client's business requirements into software development solutions / designs.
    Excellent verbal and written communication skills.
    Ability to meet project timelines while working within a budget.
    Ability to collaborate with peers on a project to meet client needs.
    Good technical understanding of web development methods and technology to communicate effectively with developers and translate technical issues to non- technical audiences.
    Strong working experience with Azure DevOps (TFS) practices and supporting tools.
    Travel: Up to 10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree in Computer Science / Software Engineering and 10+ years of related experience in the development of Software Applications or related technical disciplines is required.

 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1157876-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
