### ISSUE TITLE
Michael Parker

### ISSUE THREAD

**Issue by InstanceOfMichael** [tech256/jobs#46]
# Hire me?

## Michael Ryan Parker
Full Stack Web Application Developer
Remote or onsite.

### Resume

4.5 Years Full Stack Web Application Developer - Sharp Auction Engine:
- PHP7 + Laravel, Node.js + Express.js + Socket.io + Feathers.js, MySQL, Redis, Vue.js, Nuxtjs

Other:
- Beginner: Rust
- Interests: Erlang\Phoenix, Haskell, React.js, Kotlin
- Full PDF available by request

### Contact
- Tech256: @instanceofmichael

**Comment by iamvery** [comment]
@InstanceOfMichael still relevant?
