### ISSUE TITLE
AICET IAMD Intermediate MBSE Engineer (#1159258)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#460]
PeopleTec is currently seeking an AICET IAMD Intermediate MBSE Engineer to support our Huntsville, AL location.

 

The candidate will support Advanced Integration for Countering Emerging Threats (AICET) Program, which is a pilot program for the Integrated Air and Missile Defense (IAMD) Program. The objective of AICET is to enhance a net-centric air and missile defense architecture by developing and using state of the art Model-Based Systems Engineering (MBSE) tools and processes to perform concept definition, conduct architecture studies, execute models & simulation development/analysis, and deliver a viable capability enhancement to the IAMD Program Office. The concept work drives the development of the process/tool infrastructure, and the concept products validate the efficiency and efficacy of the processes and tools.The candidate will be responsible for: supporting the development and maintenance of the IAMD MBSE model baseline and analyses of interfaces/functional behaviors of IAMD, perform consequence assessments of proposed changes to IAMD functional behaviors, support the strategy for implementing new capabilities, and coordinating with the IAMD PO and other MBSE users/clients.

 

Required Skills/Experience:

    Experience on joint engineering teams to develop a systems engineering process architecture and perform concept development of new capabilities
    Familiarity with complex software systems development
    Familiarity with modeling & simulation development, planning, execution, and data analysis
    Familiarity with developing engineering processes
    Familiarity with Model-Based Systems Engineering processes and tools, including SysML and UML
    Travel: Local travel only 
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor of Science Degree or higher in a science or technology discipline (e.g. engineering, physics, math, computer science) is required. Five to ten years of demonstrated experience working on a technical program that employed MBSE methodologies is also required.

 

Desired Skills:

    Familiarity with Integrated Air and Missile Defense, PAC-3, or other directly related AMD programs
    Familiarity with radar systems, including AN/TPY-2, LTAMDS, PATRIOT, G/ATOR
    Possess an ability to plan, coordinate, and support product development in a fast-paced, rapidly changing environment
    Capable of providing engineering/scientific support on systems, system elements, interfacing systems, components, devices, and/or processes for developmental and operational weapon system engineering programs
    Excellent social, organizational, management and leadership skills
    Capability to use the Microsoft Office package to include: Outlook, Word, PowerPoint, and Excel

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1159258-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
