### ISSUE TITLE
AICET IAMD Senior M&S Developer/Analyst (#1159287)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#461]
PeopleTec is currently seeking an AICET IAMD Senior M&S Developer/Analyst to support our Huntsville, AL location.

 

The candidate will support Advanced Integration for Countering Emerging Threats (AICET) Program, which is a pilot program for the Integrated Air and Missile Defense (IAMD) Program. The objective of AICET is to enhance a net-centric air and missile defense architecture by developing and using state of the art Model-Based Systems Engineering (MBSE) tools and processes to perform concept definition, conduct architecture studies, execute models & simulation development/analysis, and deliver a viable capability enhancement to the IAMD Program Office. The concept work drives the development of the process/tool infrastructure, and the concept products validate the efficiency and efficacy of the processes and tools. The candidate will play a major role in the planning, development, and execution of simulations for new IAMD capabilities concepts based on either MBSE functional and performance characteristics, or behaviors identified by IAMD subject matter experts. These simulations are intended to assess key performance and functional characteristics for the candidate concept trade studies. The candidate will also coordinate developing the data analysis processes, aid in conducting the data reviews, and coordinate defining/developing visualizations to aid in interpreting results. The candidate will support developing the M&S plans and processes for executing the simulations, including anchoring the simulations and performing verification & validation as necessary. The candidate will also help develop plans to leverage models and results from the MBSE SysML, UML, and VPL environment and the lower fidelity simulations to develop the high fidelity models. To that end, the candidate will help coordinate with the MBSE development team to identify specific needs an aid in defining plans. 

 

Required Skills/Experience:

    Demonstrated leadership in developing M&S plans, leading teams of analysts, and preparing reports on the results
    Familiarity with modeling & simulation development, planning, execution, and data analysis
    Familiarity with DAF, NSim, ETESim, and IAMDSIM
    Familiarity with radar systems, including AN/TPY-2, LTAMDS, PATRIOT, G/ATOR
    Familiarity with concept definition/exploration process
    Travel: Local travel only 
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree or higher in a science or technology discipline (e.g. engineering, physics, math, computer science) is required. Ten to fifteen years of demonstrated experience in developing, validating, and executing models & simulations for aerospace applications is also required.

 

Desired Skills:

    Familiarity with Integrated Air and Missile Defense Familiarity with developing engineering processes
    Familiarity with Model-Based Systems Engineering based on MagicDraw
    Possess an ability to plan, coordinate, and support product development in a fast-paced, rapidly changing environment
    Excellent social, organizational, management and leadership skills
    Capable of working as a team member to solve engineering/scientific problems
    Capable of playing a major role on engineering/scientific teams on systems, system elements, interfacing systems, components, devices, and/or processes for developmental and operational weapon system engineering programs
    Capable of implementing system engineering processes across a program acquisition life cycle
    Work as a team member and assist with solving complex problems
    Capability to use the Microsoft Office package to include: Outlook, Word, PowerPoint, and Excel
    Ability to lead a team of engineers and plan/coordinate/execute cross-disciplinary activities 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1159287-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
