### ISSUE TITLE
Technical Business Analyst/Business Intelligence

### ISSUE THREAD

**Issue by GeocentSteve** [tech256/jobs#466]
# Geocent is hiring Technical Business Intelligence Analysts!

### About Position
**Overview:**

Title:  **Technical Business Analyst/Business Intelligence**
Location:  **Huntsville, AL**
Number of openings:  **2**
Hiring Terms:  **Direct-hire, FTE**

The Geocent family changes the world by creating unique technical to solve the nation’s most challenging problems. Come join Geocent to be a part of a positive culture as we strive towards:  Enabling Our Warfighters, Protecting the Homeland, Enabling Deep Space Exploration, Serving Our Veterans, Securing the Infrastructure, and Building the Cloud.

**Responsibilities:**
- Provides expertise in the formulation of systems scope and objectives relative to the business plan and client requirements.
- Analyzes business and technical processes to formulate and develop new and modified business information processing and data models.
- Works as a member of a project team responsible for providing technical guidance related to the business implications of the data and data models of various systems.
- Devises and/or modifies procedures to solve technical problems related to data warehouse capacity and limitations, operating time and form of desired results.
- Creates detailed specifications and data models from which programs will be written.

**Qualifications:**
- Experience with Sparx Systems Enterprise Architect or Rational Modeling
- Experience with Data Warehouse
- Experience with UML 2.0
- Experience gathering and interpreting technical requirements
 
*Must have **OR** be able to obtain DoD Secret security clearance - US CITIZENSHIP IS REQUIRED*

**EEO Statement:**
Geocent is an Equal Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, pregnancy, sexual orientation, gender identity, national origin, age, protected veteran status, or disability status.

### Contact
- Steve Oholendt, Geocent Corporate Recruiter 
- steve.oholendt@geocent.com
- tech256 slack: @GeocentSteve

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
