### ISSUE TITLE
Data Scientist

### ISSUE THREAD

**Issue by GeocentSteve** [tech256/jobs#467]
# Geocent is hiring Data Scientists in Huntsville!

### About Position
**Overview:**

Title:  **Data Scientist**
Location:  **Huntsville, AL**
Number of openings:  **2**
Hiring terms:  **Direct-hire, FTE**

The Geocent family changes the world by creating unique technical to solve the nation’s most challenging problems. Come join Geocent to be a part of a positive culture as we strive towards:  Enabling Our Warfighters, Protecting the Homeland, Enabling Deep Space Exploration, Serving Our Veterans, Securing the Infrastructure, and Building the Cloud.

**Responsibilities:**
- Brings data from operational and other systems to life by creating value added elements that can advance business objectives.

**Qualifications:**
- 3 years' experience in data analytics
- 2 years' IBM SPSS or SAS software
- Experience with SQL Server
- Understanding of data concepts, with the ability to write complex SQL statements to store, retrieve, manipulate, integrate, validate, and summarize data
- Statistics/Mathematics experience/background
- Strong data science skill set; experience with some of the following:  Python, R, Hadoop, ML/DL/AI knowledge, data visualization, Apache Spark, Java, data mining tools

*Must have **OR** be able to obtain DoD Secret security clearance - US CITIZENSHIP IS REQUIRED*

**Nice to have:**
- Prior involvement in Predictive Analytics and/or use of SPSS modeler
- IBM Data Analytic Badges

**EEO Statement:**
Geocent is an Equal Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, pregnancy, sexual orientation, gender identity, national origin, age, protected veteran status, or disability status.

### Contact
- Steve Oholendt, Geocent Corporate Recruiter 
- steve.oholendt@geocent.com
- tech256 slack: @GeocentSteve

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
