### ISSUE TITLE
Electrical Engineer - Mid Level

### ISSUE THREAD

**Issue by EOS-Defense-USA** [tech256/jobs#469]
Do people describe you as Analytical? Inventive? Detail Oriented?

If so, this opportunity is waiting for YOU!

 

ELECTRICAL ENGINEER - Mid Level

 

EOS Defense Systems USA, is a world leader in space information and intelligence services, optical sensor units and remote weapon systems for the land, sea, and air. 

 

What We Can Offer YOU!

    Driven, Team Environment

    Advancement Opportunities

    Benefit Package with Medical/Dental/Vision, Life Insurance, Paid Holidays & PTO, 401(k) Retirement Plan with Generous Company Match

    9/80 Work Schedule (Every Other Friday Off)
    Opportunity to Help Build and Shape Company Culture

 

Job Responsibilities

    Responsible for electrical/electronic designs from conception to manufacturing including: library part creation, schematic capture, component placement, and routing

    Research new components, technologies, and methods to incorporate into new designs

    Create and review all documentation required to support electrical configuration and implementation using the Altium Designer tool set

    Perform electrical design analyses in support of product development activities

    Interface with software, systems, and mechanical engineering disciplines to ensure that the overall design requirements are captured and accomplished

    Work with systems engineers to ensure that all requirements are identified, captured and analyzed, such that design can be developed that satisfy the requirements

    Conduct test and evaluation activities on electrical designs to verify and sign-off of all design requirements

    Work with Project Engineers to ensure design solutions are delivered on time and on budget and meet other project management requirements

 

Required Qualifications

    BA/BS in Electrical Engineering, Computer Science or related field of study

    4 - 7 years of applicable experience

    Understanding of technical theories / concepts in field of electrical engineering design and manufacturing
    Effective written, verbal, and interpersonal communication skills

    Ability to work in team environment interacting with a variety of functional areas and management levels

 

Preferred Qualifications

    Post graduate qualifications in Engineering

    Previous experience in a manufacturing organization

    Previous experience working with government contractors

    Experience with Remote Weapons Stations

    Experience with the Altium Designer tool set

    Experience with mechanical turrets and slip rings

 

DON'T LET THIS OPPORTUNITY GET AWAY...APPLY TODAY!

 

EOS Defense Systems is an Equal Opportunity Employer

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1161957-397274

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
