### ISSUE TITLE
COLSA  Corporation Frontend Software Engineer

### ISSUE THREAD

**Issue by nallbradley** [tech256/jobs#47]
# Hiring!

### About Position
Seeking a front end software engineer

###Requirements
Bachelor’s degree in computer science, information systems, engineering, business, or other related field, or equivalent experience
Five years applicable software development and engineering experience
Professional experience in web technologies (HTML or HTML5)
Professional experience in frontend technologies (JavaScript, AngularJS, jQuery, or Typescript)
Professional experience in frontend styling technologies (CSS, SCSS, SASS, Grunt, or Bootstrap)
Professional experience in backend technologies (C#, Java, Ruby, PHP, or Node.js)
Professional experience in database technologies (MYSQL, SQL, or MongoDB)
Must have the ability to obtain and maintain a DoD security clearance

### Contact
- Location: Huntsville, AL

**Comment by iamvery** [comment]
@nallbradley still relevant?

**Comment by nallbradley** [comment]
No longer relevant. Can be closed.

Bradley Nall
