### ISSUE TITLE
Software Engineer - Mid

### ISSUE THREAD

**Issue by EOS-Defense-USA** [tech256/jobs#470]
EOS is a world leader in space information and intelligence services, optical sensor units and remote weapon systems for the land, sea, and air.

What We Can Offer YOU!

    Driven, team-environment
    Advancement Opportunity
    Compensation package with Medical/Dental/Vision, Life Insurance, Paid holidays & PTO, 401(k) retirement plan with competitive match
    9/80 Work Schedule (every other Friday off)
    Opportunity to help build and shape company/culture

Job Overview

As a Software Engineer you will design and develop software that integrates the data from an advanced suite of sensors into a responsive, reliable, and safe control system. You will interface with our Systems, Mechanical, and Electronics Engineering teams to contribute to our high performing, world leading Remote Weapon Stations (RWS). You will serve as the software architect for numerous model and simulation projects to include embedded programming. 

 Job Duties

    Analyze, design, code, test and integrate software systems/programs to enable proper functioning of hardware systems/subsystems
    Prepare engineering change requests and software trouble reports
    Stand up in-house software development tools and configuration management
    Evaluate and utilize leading edge software development tools
    Participate in formal & informal teams and assume leadership role, as needed. 

Required Qualifications

    BA/BS in Software Engineering, Computer Science or related field of study
    4 - 7 years of applicable experience
    Working knowledge of C, C++ and/or Java programming languages
    Proven experience with network design and integration
    Experience with engineering processes such as CMMI, or SPICE or similar methodologies.
    Possess a working knowledge of embedded or real-time software development experience. 
    Knowledge of electronics technologies including RF, electronics, computer systems and test equipment
    Effective written, verbal, and interpersonal communication skills
    Ability to work in team environment interacting with a variety of functional areas and management levels

Preferred Qualifications

    MA/MS in Software Engineering, Computer Science or related field of study
    Previous experience in a manufacturing organization
    Previous experience working with government contractors

U.S. Government Security Clearance Preferred

Occasional travel may be necessary

EOS Defense Systems is an Equal Opportunity Employer

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1161929-397274

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
