### ISSUE TITLE
Software Airworthiness Engineer (#1171466)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#475]
PeopleTec is currently seeking a Software Airworthiness Engineer to support our Huntsville, AL location.

PeopleTec is seeking software individuals to support Army Aviation Systems at Redstone Arsenal. A software engineering and/or systems engineering background is required. The candidate will be expected to perform software systems airworthiness evaluations for Army Aviation systems as well as provide software technical expertise, participate in systems reviews, and provide software airworthiness assessments to the Aviation Engineering Directorate (AED). Candidates will often be required to work individually or as a member of a SW Airworthiness team.

 

Required Skills/Experience:

Must have a working knowledge of current operating systems and programming languages to include C, C++, C#, Ada
Understand the software development life cycle (SDLC) IEEE 12207, MIL-STD-498, etc
Have Software development or V&V analysis experience with a critical system similar to safety critical system
Have applicable software design engineering experience
Travel: None
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

Bachelor's degree in computer science, electrical or computer engineering with 5-8 years experience is required.

 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1171466-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
