### ISSUE TITLE
Senior Systems Administrator - Cummings Aerospace

### ISSUE THREAD

**Issue by dannagle** [tech256/jobs#477]
Overview

The Senior Systems Administrator is a full-time exempt position. The Senior Systems Administrator is responsible for leading the planning, implementation, management, administration, and control of corporate information systems under direction of the Operations Manager. The Senior Systems Administrator will be responsible for implementing technical and administrative controls involving the security of corporate information systems and other programs as assigned. The Senior Systems Administrator will mentor other Systems Administration staff.

 
Responsibilities

Configure and Monitor wired/wireless networks to ensure high availability for Cummings Aerospace staff and external partners.
Maintain and monitor hardware and software associated with enterprise environment and associated projects as required.
Day to day maintenance on associated infrastructure to include but not limited to Desktop Support, Windows Hyper-V Virtualization; Windows Server 2016; Networking and Firewall technologies; and backup infrastructure.
Mentoring and leading other members of the systems administration team to assist with day to day activities.
Leading in the planning and architecting of solutions to improve and utilize existing functionality of the Cummings Aerospace network.
Working with the Cybersecurity Manager to ensure technology implementation meets requirements for policy and governance.
Assisting in communicating and providing Information Systems Security education, training, and awareness program.
Maintaining a working knowledge of system functions, security policies, technical security safeguards, and operational security measures.
Completing required SENIOR SYSTEMS ADMINISTRATOR training to maintain certifications and compliance with government regulations (as assigned by the Cybersecurity Manager and Lead Facility Security Officer).
Assist with day to day troubleshooting for Microsoft desktops, Linux and Microsoft server infrastructure, firewall/switch, Virtual Private Networking (VPN) and backup technologies.
Assist in planning and engineering of replication activities and secure network design.
May require support outside normal business hours including evenings and weekends.
 

Skills and Competencies

Bachelor’s degree in relevant field required and at least 5 years’ experience supporting DoD programs (Senior Systems Administrator, etc.) and/or organizations or a degree in the area of Information Technology. Or, 10 years’ experience supporting DoD programs (Senior Systems Administrator, etc.) and/or organizations or a degree in the area of Information Technology.
Candidate should possess necessary certifications per DoD directive 8570.1. IAT Level II will be required within six months of hire.
Candidate must demonstrate excellent verbal and written communication skills.
Ability to organize work and deliver on time work products.
 

Clearance

Active DOD Secret Security clearance required.

Cummings Aerospace provides equal employment opportunities (EEO) to all employees and applicants for employment without regard to race, color, religion, sex, national origin, age, disability or genetics. In addition to federal law requirements, Cummings Aerospace complies with applicable state and local laws governing nondiscrimination in employment in every location in which the company has facilities. This policy applies to all terms and conditions of employment, including recruiting, hiring, placement, promotion, termination, layoff, recall, transfer, leaves of absence, compensation and training.

Cummings Aerospace expressly prohibits any form of workplace harassment based on race, color, religion, gender, sexual orientation, gender identity or expression, national origin, age, genetic information, disability, or veteran status. Improper interference with the ability of Cummings Aerospace’s employees to perform their job duties may result in discipline up to and including discharge.

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
