### ISSUE TITLE
Lead Visual Effects Artist (#1178040)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#478]
PeopleTec is currently seeking a Lead Visual Effects Artist to support our Huntsville, AL location.

 

PeopleTec, Inc. is seeking a Senor level Visual Effect (VFZ) Artist to join a team developing extraordinary games and interactive stories for the Army Game Studio. Destruction, explosions, and weapons effects are not just an accent to our game, but are a star feature. You will work with a team of technical and animation experts tackling the challenge of creating amazing destructive content. You must be creative, talented, and motivated with AAA experience solving complex particles, physics, and animation scenarios. As the senior VFX artist, you have an aptitude for critical thinking. You must be fearless in creativity and you are extremely well-versed in real-time particle systems and creating cutting-edge destructive elements. The candidate must be eager to tackle the challenges of the ever changing landscape of VFX and unafraid to seek and create new solutions. The candidate must also a team player who is organized with excellent communication skills. All candidates must have a portfolio/reel to be considered. 

 

Required Skills/Experience:

    Experience in a modeling, technical art, or animation role in video game development
    Experience as a VFX artist using particles, physics systems, and rigid/soft body simulation to create explosions, weapons effects, fire, smoke and all manner of destructible assets
    Mastery of Maya, Unity, and/or Unreal 4 High efficiency in Houdini, After Effects, and supporting tools
    Ability to communicate effectively with Artists, Designers, and Technical Artists
    Creatively solve technical and optimization issues that arise
    Work with art and design leads to make our game more immersive through destruction
    Travel: None 
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's degree in Art, Game Development, Animation or Related Field with 2+ Years of Modeling, Technical Art or Animation 3+ Years experience as an VFX artist is required. 

 

Desired Skills:

     Ability to assist with other art tasks, including: lighting 2d, 3d, modelling, texturing or concept tasks
    Experience with one or more scripting / programming languages
    Understanding of real-time physics systems
    Basic knowledge of rigging, skinning, and key-frame animation
    Traditional art and animation skill

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1178040-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
