### ISSUE TITLE
Cloud Engineer - Siemens - Huntsville, AL

### ISSUE THREAD

**Issue by joescii** [tech256/jobs#48]
# Hiring!

### Job Description
 Work with cross-functional teams to develop products, business
processes and online commercialization of cloud applications and
migration of current applications to cloud. Design, develop, modify,
and implement highly available and scalable cloud services for
products. Perform research and development on new cloud technologies
and methodologies.
 
Ability to understand complex products, solutions, and problems.
Creates, documents, and executes software design, which may involve
significant re-architecture of important systems, defining and
coordinating implementation. Promote innovation through the ability to
introduce new technology/knowledge into at least one area of a product
and to cross-functional teams. Provide problem resolution and technical
leadership for the group. Works without supervision on highly complex
projects with complete latitude for independent judgment and technical
expertise.
 Experience utilizing automation technologies and restful web services –
JSON, Chef, XML, Ruby, Python - or other scripting languages.
 
#### Minimum Requirements:
Bachelor’s degree in computer science, engineering, or other related
discipline required
3+ years of professional experience in software development
• Define, design and deliver a distributed automation platform for
compute, storage, database, queuing and other infrastructure
• Understanding of IT concepts - Security best practices and
application – SSH, public key encryption, access credentials and
certificates, SSL, data encryption in motion and at rest
• Experience (one or more years) in designing, developing and deploying
cloud based solution using AWS.
• Understanding of core AWS services, uses, and basic architecture best
practices
 Proficiency in at least one modern programming language such as:
• C++, C#, Java, Python, PHP, Ruby on Rails

#### It is highly desirable that the candidate possess one or more of the following:
Certified AWS associate level Developer
• Designing and deploying dynamically scalable, highly available, fault
tolerant, and reliable applications on AWS
• Selecting appropriate AWS services to design and deploy an
application based on given requirements
• Experience with developing and maintaining applications written for
Amazon Simple Storage Service, Amazon DynamoDB,Amazon Simple Queue
Service, Amazon Simple Notification Service, Amazon Simple Workflow
Service, AWS Elastic Beanstalk, and AWS CloudFormation.
 Proactive business skills and strong collaborative skills are required.
 • Demonstrated leadership skills; ability to work independently with
minimal supervision as part of a globally distributed team
• Proven ability to collaborate effectively across disciplines, product
lines, roles and geographical and time zone boundaries
• Excellent oral/written communication & listening skills will be
necessary to present information, analysis & recommendations to all
levels of employees, including management, and customers.
• Highdegree of organization to manage & maintain project plans, road
maps & provide accurate updates as part of the review cycle.

### Contact
- Tech256: @joescii
I'll get you in contact with the recruiter trying to fill this one. I interviewed for it back in May, so I can also give you a good idea of what they're looking for beyond what is in this description.

**Comment by iamvery** [comment]
@joescii still relevant?

**Comment by joescii** [comment]
Nope, thanks!
