### ISSUE TITLE
Multiple Entry, Associate, & Senior-level MBSE Openings

### ISSUE THREAD

**Issue by GeocentSteve** [tech256/jobs#482]
# Geocent is hiring multiple Entry, Associate, & Senior Level Model-Based Systems Engineers (MBSE) in Huntsville!

### About Position
**Overview:**

Title(s):  **Entry, Associate, & Senior MBSE**
Location:  **Huntsville, AL**
Number of openings:  **6-8**
Hiring terms:  **Direct-hire, FTE**
**MUST HAVE Active DoD Secret Clearance or higher**
**US Citizen only for Federal Security clearance job requirement**

JOIN GEOCENT AND HELP US SOLVE THE WORLD'S BIGGEST PROBLEMS

Whether we’re enabling space exploration, protecting our homeland, or serving our veterans,
our projects combine science, technology, and strategy to create big solutions for the world’s most difficult challenges.

This individual will have the opportunity to participate in the the Air Force's multi-billion Ground Based Strategic Deterrent (GBSD) program, replacing the Minuteman III land based Intercontinental Ballistic Missile (ICBM). Become a part of our team in supporting the USAF’s nuclear deterrence mission to replace the entire weapon system and refurbish the existing ground systems infrastructure.

Geocent's Aerospace & Defense Engineering Sector offers exciting and challenging opportunities in the Space and Missile Defense Industry. Geocent employees across the country subscribe to the company's culture of focusing on results when serving our large, diverse group of clients nationwide.

**Responsibilities:**

Modeling requirement and verification activities; verification and certification planning with regards to test, analysis, demonstration and examination; Develop and extend system models using existing requirements, interface documentation, and related design and systems engineering documents; Enters and verifies the accuracy of the functional architecture framework in the appropriate databases to increase own knowledge and familiarity with using architecture tools and framework

**Qualifications:**
- DoD systems design, architecture definition, and analysis
- Experience with Model Based Engineering tools and languages such as MagicDraw or Cameo Systems Modeler, Sparx Systems' Enterprise Architect (EA), CORE, and UML/SysML/DoDAF
- Experience with requirements development tools such as DOORS
- Ability to conduct trade studies
- Active Secret Security Clearance:  Final Secret with the investigation date within last 5 years OR Final Top Secret with an investigation date within the last 5 years.

**EEO Statement:**
Geocent is an Equal Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, pregnancy, sexual orientation, gender identity, national origin, age, protected veteran status, or disability status.

### Contact
- Steve Oholendt, Geocent Corporate Technical Recruiter 
- steve.oholendt@geocent.com
- tech256 slack: @GeocentSteve

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
