### ISSUE TITLE
Mid-Sr. Electromagnetic Effects Engineer (E3) - 2 openings

### ISSUE THREAD

**Issue by GeocentSteve** [tech256/jobs#483]
# Geocent is hiring 2 Mid-Senior Level Electromagnetic Effects Engineers (E3) in Huntsville!

### About Position
**Overview:**

Title(s):  **Mid-Sr. Electromagnetic Effects Engineer**
Location:  **Huntsville, AL**
Number of openings:  **2**
Hiring terms:  **Direct-hire, FTE**
**MUST HAVE Active DoD Secret Clearance or higher**
**US Citizen only for Federal Security clearance job requirement**

JOIN GEOCENT AND HELP US SOLVE THE WORLD'S BIGGEST PROBLEMS

Whether we’re enabling space exploration, protecting our homeland, or serving our veterans,
our projects combine science, technology, and strategy to create big solutions for the world’s most difficult challenges.

This individual will have the opportunity to participate in the the Air Force's multi-billion Ground Based Strategic Deterrent (GBSD) program, replacing the Minuteman III land based Intercontinental Ballistic Missile (ICBM). Become a part of our team in supporting the USAF’s nuclear deterrence mission to replace the entire weapon system and refurbish the existing ground systems infrastructure.

Geocent's Aerospace & Defense Engineering Sector offers exciting and challenging opportunities in the Space and Missile Defense Industry. Geocent employees across the country subscribe to the company's culture of focusing on results when serving our large, diverse group of clients nationwide.

**Responsibilities/Qualifications:**
- Review segment design layouts to ensure compliance with EME checklists
- Maintain and release EME Control plan and Spectrum Supportability Risk Assessment with complete E3 analysis of each SDS along with co‐site assessments; 
- Document potential design risks to system operations;
- Review component specifications for EMI/EMC, grounding and bonding, TEMPEST, and frequency management requirements
- EMI/EMC/TEMPEST/Spectrum Analysis
- Active Secret Security Clearance:  Final Secret with the investigation date within last 5 years OR Final Top Secret with an investigation date within the last 5 years.

**EEO Statement:**
Geocent is an Equal Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, pregnancy, sexual orientation, gender identity, national origin, age, protected veteran status, or disability status.

### Primary Contact:
- Kat Bowman, Senior Corporate Technical Recruiter 
- katherine.bowman@geocent.com
- 256-690-5321 (office)
 
### Secondary Contact: 
- Steve Oholendt, Corporate Technical Recruiter 
- steve.oholendt@geocent.com
- tech256 slack: @GeocentSteve

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
