### ISSUE TITLE
Job openings Software Development, Engineering and AI

### ISSUE THREAD

**Issue by SarahTaylorHSV** [tech256/jobs#485]
[SrSigProcEngr_JobDesc.docx](https://github.com/tech256/jobs/files/3600696/SrSigProcEngr_JobDesc.docx)
[Technical Manager VxWorks.docx](https://github.com/tech256/jobs/files/3600700/Technical.Manager.VxWorks.docx)
[Software Engineering Manager JD #4.doc.docx](https://github.com/tech256/jobs/files/3600702/Software.Engineering.Manager.JD.4.doc.docx)

**Comment by GeneralPallas** [comment]
@SarahTaylorHSV if you don't mind could you create separate posts for each job and put the job description n each post. Our goal is to make it as easy as possible for our community to identify if they are interested in a position. Feel free to look at the other postings in this repository to see how we typically accept postings.

**Comment by PallasStreams** [comment]
Since you have created separate posts for each of these positions I'm going to go ahead and close this now. Thanks for creating those postings and making it easier for our community to view the postings.
