### ISSUE TITLE
Sr. Signal Processing Engineer-ML/CV

### ISSUE THREAD

**Issue by SarahTaylorHSV** [tech256/jobs#486]
This position will contribute to product development through research, implementation, and validation of algorithms in the areas of sensor signal processing, computer vision and AI/Machine Learning. The position will lead or support various tasks and activities within a project and will organize, schedule, and task team activities in overall coordination with the Project Manager.

Required Experience
•	United States Citizenship
•	4-year BS degree in Engineering. CS, EE, or CE preferred (advanced degree MS/ Ph.D. is a plus)
•	10+ years of experience in signal processing algorithm development
•	Proficient in: C/C++, Python, MATLAB (NumPy, SciPy, Matplotlib, scikit-learn is a plus)
•	Proficient in MS Office (MS Word, Excel, PowerPoint)

Desired Skills
•	Experience developing algorithms for resource-constrained embedded systems
•	Experience porting MATLAB/Octave algorithms to other languages (i.e. C/C++)
•	Experience in other programming languages (Java), AI/ML Tools (TensorFlow)
•	Familiarity with feature selection and classification approaches
•	Familiarity with Digital Image Processing and motion-based detection techniques
•	Familiarity with Convolutional Neural Networks and object recognition through deep learning
•	Familiarity with Radar theory and Radar Signal Processing

Contact information:
Sarah Taylor
256-533-1444
staylor@grnhuntsville.com

[SrSigProcEngr_JobDesc.docx](https://github.com/tech256/jobs/files/3605330/SrSigProcEngr_JobDesc.docx)

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
