### ISSUE TITLE
Technical Manager VxWorks

### ISSUE THREAD

**Issue by SarahTaylorHSV** [tech256/jobs#487]
We have an excellent opportunity for an embedded software engineer to work on cutting edge development projects in Huntsville, Alabama.  The position can be an MTS or a Senior Engineer. The Member of Technical Staff candidate will have proven skills in development of embedded software for embedded hardware systems. The job requires solid people skills for interaction with customers and/or our services project teams.  The qualified candidate will be self-driven with relevant embedded software experience that can be applied to a variety of new processor and peripheral devices.
**Responsibilities**
-Design, implementation and validation of embedded software E.g.  Board Support Packages (BSP) for custom and/or COTS embedded hardware systems  
-Design, implementation and test of software drivers for a variety of peripheral devices commonly used in embedded hardware systems. 
-Development of hardware test code, support bring-up and validation of custom embedded hardware systems. 
-Provide customer site support
-Work independently on customer site managing day to day interactions  \
**Requirements**
-Bachelor’s degree in computer science, electrical engineering or equivalent in a related subject area
-Minimum of 5 years of embedded software design experience preferably with VxWorks and Linux. 
-Experience with low level embedded SW (e.g. BSPs and device drivers) development, debugging/trouble shooting
-Experience using embedded software development environments (e.g. Workbench, Eclipse) 
-Experience in custom embedded hardware bring up
-Strong C programming experience
-Software development experience on one or more common embedded processor types (PowerPC, MIPS, X86, ARM, etc.)
-Prior customer success management experience a plus
-Experience with Multi-core & Virtualization architectures a plus.  
Contact information
Sarah Taylor
256-533-1444
staylor@grnhuntsville.com

[Technical Manager VxWorks.docx](https://github.com/tech256/jobs/files/3605363/Technical.Manager.VxWorks.docx)

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
