### ISSUE TITLE
DTS Travel Assistant (#1191892)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#489]
PeopleTec is currently seeking a DTS Travel Assistant to support our Huntsville, AL location.

 

Duties include:

    Create and finalize travel arrangements for CONUS and OCONUS travel for senior leaders using the Defense Travel System (DTS)
    Provide guidance regarding Joint Travel Regulations (JTR) and policies regarding government travel, including booking with contract fares
    Assist all travelers to create travel authorizations and vouchers in a timely manner
    Serve as a primary point of contact to analyze, modify, and resolve travel plans, including making changes to existing flight and hotel reservations
    Coordinate with the Executive Assistant to effectively de-conflict calendars with travel schedule
    Coordinate visit requests with security for various sites. Review and resolve any purchase card discrepancies

 

Required Skills/Experience:

    High degree of professionalism and experience in a fast paced work environment
    Prior experience using the Defense Travel System (DTS) and knowledge of Joint Travel Regulations (JTR)
    Ability to perform in a highly dynamic work environment supporting multiple military, government civilian, and contractor team members
    Experience in related field of expertise at the program/project level
    Proficient level experience with utilization of Microsoft Office Suite of products (Word, Excel, PowerPoint
    Outlook) and Adobe Acrobat
    Ability to prepare detailed written reports and briefings suitable for presentation to senior leaders
    Excellent written and oral communication skills
    Travel: 0%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

High School diploma and DTS experience in a DoD program/project office environment is required.

 

Desired Skills:

    Associates Degree
    DTS

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1191892-375181

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
