### ISSUE TITLE
Electrical Engineer

### ISSUE THREAD

**Issue by SarahTaylorHSV** [tech256/jobs#490]
The Electrical Engineer will be primary motivator and contributor to the analysis, conceptual design, development, and testing of electrical circuit boards, cables, power supply box and wiring harness used on industrial metering and pump products. The Engineer will also contribute heavily in embedded software applications to run microcontroller based boards.

Essential Functions
•	Define requirements for electronic control software and interfacing hardware components including encoder feedback
•	Design, model, implement, and test electronic controls for various industrial equipment
•	Schematic design and layout support of Printed Circuit Boards (PCBs)
•	Design experience with analog electronics and filtering techniques
•	Understand firmware how to read firmware written in ANSI C/C++ for micro controllers/digital signal processors and FPGA/CPLD’s
•	Determine and verify the system requirements by analysis and modeling of control systems using simulation tools such as MATLAB, Spice, Altium ect.
•	Work closely with mechanical and software systems engineers to develop robust controllers for various electro-mechanical systems/devices
•	Implement designs with schematic capture and layout tools
•	Lead / Support and execute the NPD process for future products to ensure design robustness
•	Lead/mentor junior engineers in the product design and development process
•	Lead the requirements analysis process at a Product, System, Sub-system and component level
•	Develop and maintain project timing plans
•	Lead/support product design reviews
•	Lead quality improvement initiatives for legacy products
•	Engage with commercial team to identify and analyze customer needs, develop business cases and product specifications
•	Develop design verification and validation plans for hardware; perform verification and validation tests documenting the test results
•	Review and debug low level software and electrical designs/hardware (reading electronic schematics and PCB layouts)
•	Support (technical and engineering) marketing, field service, sales and customers regarding technical information and engineering problems
•	Investigate/create engineering change requests to improve product, correct errors, facilitate production, and reduce cost (RCCM – Root Cause / Counter Measure)
•	Interface with regulatory agencies to gain appropriate approvals on new products

Point of Contact 
Sarah Taylor 
256-533-1444
staylor@grnhuntsville.com
https://www.linkedin.com/in/sarah-taylor-b14429aa/

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
