### ISSUE TITLE
AICET IAMD Junior M&S Developer/Analyst (#1199536)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#492]
PeopleTec is currently seeking an AICET IAMD Junior M&S Developer/Analyst to support our Huntsville, AL location.

 

The candidate will support the Advanced Integration for Countering Emerging Threats (AICET) Program, which is a pilot program for the Integrated Air and Missile Defense (IAMD) Program. The objective of AICET is to enhance a net-centric air and missile defense architecture by developing and using state of the art Model-Based Systems Engineering (MBSE) tools and processes to perform concept definition, conduct architecture studies, execute models & simulation development/analysis, and deliver a viable capability enhancement to the IAMD Program Office. The concept work drives the development of the process/tool infrastructure, and the concept products validate the efficiency and efficacy of the processes and tools. 

 

Duties Include:

    Support the planning, development, and execution of simulations for new IAMD capabilities concepts based on either MBSE functional and performance characteristics, or behaviors identified by IAMD subject matter experts
    Support performing the data analysis
    Aid in conducting the data reviews
    Assist in defining/developing visualizations to aid in interpreting results
    Support developing the model, executing the simulations, making updates to the models, and performing data analysis on the simulation results
    Support leveraging models and results from the MBSE SysML environment and the lower fidelity simulations to develop the high fidelity models

 

Required Skills/Experience:

    Familiarity with modeling & simulation concepts, planning, execution, and data analysis
    Familiarity with concept definition/exploration process
    Familiarity with Model-Based Systems Engineering 
    Travel: Local travel only; Out of town travel in not likely 
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's of Science Degree or higher in a science or technology discipline (e.g. engineering, physics, math, computer science) is required. Zero to five years of demonstrated experience in developing, validating, and executing models & simulations is also required.

 

Desired Skills:

    Familiarity with Integrated Air and Missile Defense or similar engineering systems
    Possess an ability to plan, coordinate, and support product development in a fast-paced, rapidly changing environment
    Excellent social, organizational, management and leadership skills
    Capable of working as a team member to solve engineering/scientific problems
    Capable of supporting engineering/scientific efforts on systems, system elements, interfacing systems, components, devices, and/or processes for developmental and operational weapon system engineering programs
    Work as a team member and assist with solving complex problems
    Capability to use the Microsoft Office package, including: Outlook, Word, PowerPoint, and Excel
    Ability to actively participate in a team of engineers and help plan/coordinate/execute cross-disciplinary activities  

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1199536-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
