### ISSUE TITLE
Software Engineer 1

### ISSUE THREAD

**Issue by EOS-Defense-USA** [tech256/jobs#493]
![image](https://user-images.githubusercontent.com/52424577/65338837-a6b27e80-db90-11e9-9f88-e833104e10ff.png)

**It is an exciting time to a be a part of EOS!**

**APPLY TODAY :** https://eosdusa.applicantpro.com/jobs/1188246.html

**Are you looking for a career that will challenge you, offers limitless growth, and provides you with the opportunity to work on unique projects? We want to hear from you! EOS Defense Systems USA is a manufacturer of cutting edge, precise remote weapons stations.** 

We are looking for a top-notch **Software Engineer I** who will design and develop software that integrates the data from an advanced suite of sensors into a responsive, reliable, and safe control system. The perfect candidate will interface with our Systems, Mechanical, and Electronics Engineering teams to contribute to our high performing, world leading Remote Weapon Stations (RWS). This position will serve as the software architect for numerous model and simulation projects to include embedded programming.

**What We Can Offer YOU!**

- Driven, Team Environment
- Advancement Opportunities
- Benefit Package with Medical/Dental/Vision, Life Insurance, Paid Holidays & PTO, 401(k) Retirement Plan with Generous Company Match
- 9/80 Work Schedule (Every Other Friday Off)
- Opportunity to Help Build and Shape Company Culture

**Responsibilities:**
- Analyzes, design, code, test and integrate software systems/programs to enable proper functioning of hardware systems/subsystems
- Prepares engineering change requests and software trouble reports
- Stand up in-house software development tools and configuration management
- Evaluates and utilize leading edge software development tools
- Participates in formal & informal teams and assume leadership role, as needed
- Other duties as directed

**Key Attributes:**
- Problem solver
- Detail oriented
- Works Collaboratively
- Solution oriented
- Communicates well

**Education/Experience Required:**
- BA/BS in Software Engineering, Computer Science or related field of study
- 1-3 years of applicable experience
- Working knowledge of C, C++ and/or Java programming languages

**Experience Preferred:**
- Modeling and simulation experience
- Experience with network design and integration
- Previous experience in a manufacturing organization is
- Previous experience working with government contractors
- Experience with engineering processes such as CMMI, or SPICE or similar methodologies
- Possess a working knowledge of embedded or real-time software development experience 

**Knowledge/Skills Needed:**
- Knowledge of electronics technologies including RF, electronics, computer systems and test equipment
- Effective written, verbal, and interpersonal communication skills
- Ability to work in team environment interacting with a variety of functional areas and management levels

U.S. Government Security Clearance Preferred

Occasional travel may be necessary

EOS Defense Systems is an Equal Opportunity Employer

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
