### ISSUE TITLE
Sr. Signal Processing Engineer

### ISSUE THREAD

**Issue by SarahTaylorHSV** [tech256/jobs#495]
This position will contribute to product development through research, implementation, and validation of algorithms in the areas of sensor signal processing, computer vision and AI/Machine Learning. The position will lead or support various tasks and activities within a project and will organize, schedule, and task team activities in overall coordination with the Project Manager.
-Additionally, the senior signal processing engineer may perform evaluations of various algorithms in prototyping environments such as MATLAB before implementing final algorithms in languages such as C/C++ that are able to run on resource-constrained embedded systems. The senior signal processing engineer would perform real-world field experimentation and evaluation of system performance, analyze and interpret results and make improvements to the implemented approaches. This may include overseeing or executing all levels of testing and validation events as well as oversight of the test and build process to ensure that developed/integrated software components function and interoperate as required within and between systems. The position may also require technical presentations of algorithm implementation and results to customers. Finally, the position requires ensuring comprehensive technical documentation of algorithms and software system operation that fully reflects the product. Travel may be required in support of these activities.

Flexibility, a strong teamwork approach, and the desire to work in a fast-paced environment with existing and new product lines are necessary for success.  A willingness to learn new technologies is required. The position will be in the Engineering team reporting to the Director of AI/ML and working closely with the Product Development team. The company offers a competitive salary, fun work environment, fringe benefits, and an equity opportunity.

Required Experience
•	United States Citizenship
•	4-year BS degree in Engineering. CS, EE, or CE preferred (advanced degree MS/ Ph.D. is a plus)
•	10+ years of experience in signal processing algorithm development
•	Proficient in: C/C++, Python, MATLAB (NumPy, SciPy, Matplotlib, scikit-learn is a plus)
•	Proficient in MS Office (MS Word, Excel, PowerPoint)

Desired Skills
•	Experience developing algorithms for resource-constrained embedded systems
•	Experience porting MATLAB/Octave algorithms to other languages (i.e. C/C++)
•	Experience in other programming languages (Java), AI/ML Tools (TensorFlow)
•	Familiarity with feature selection and classification approaches
•	Familiarity with Digital Image Processing and motion-based detection techniques
•	Familiarity with Convolutional Neural Networks and object recognition through deep learning
•	Familiarity with Radar theory and Radar Signal Processing

Culture and Core Value Traits
•	Ability to work as part of a team while maintaining independent thinking
•	Highly results driven and self-starter in addition to excellent communication skills
•	Good at thinking outside the box and have an aptitude for innovation and problem solving

### Contact
Sarah Taylor
256-533-1444
staylor@grnhuntsville.com
Tech256: @sarahtaylorhsv

[SrSigProcEngr_JobDesc.docx](https://github.com/tech256/jobs/files/3658565/SrSigProcEngr_JobDesc.docx)

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
