### ISSUE TITLE
Proposal Coordinator (#1206399)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#498]
PeopleTec is currently seeking a Proposal Coordinator to support our Huntsville, AL location.

Our fast-paced Business Development Team is looking for a Proposal Coordinator with experience in the development of compliant and compelling federal proposals. The Proposal Coordinator will be supporting corporate growth through proposal development efforts including: proposal process improvement activities, capture and business intelligence research, data call coordination, proposal schedule management, and supporting our BD knowledge management system. Flexible working hours are required; including nights and weekends.

Required Skills/Experience:

Professional written and oral communication skills
Strong working knowledge of MS Office Suite (especially Word, PowerPoint and Excel), experience with Office 365 a plus
Highly skilled at document editing, formatting and configuration control
Ability to write proposal content where required
Proficient planning, time management, and organizational skills
Meticulous attention to detail and proactive approach to task management
Ability to manage numerous deadlines and task prioritization with conflicting priorities
Flexibility to work efficiently and effectively under tight deadlines in a team environment
Ability to independently execute assigned tasks with little or no supervision
Exceptional internal and external customer service orientation with ability to interface with proposal stakeholders to meet proposal deadlines
Strong process improvement orientation
Experience using SharePoint in proposal development/maintenance and BD knowledge management
Understanding of the federal Government Request for Proposal (RFP) process
Must be a U.S. Citizen
Must be able to satisfy federal government requirements for access to government information
 

Education Requirements:

A completed Bachelor's Degree in a technical or business related degree and 4 or more years of experience are required.

Desired Skills/Experience:

An active Secret clearance is desired. Candidates are required to have the ability to obtain and maintain a Secret clearance level during their employment.
Familiarity with or training in Shipley proposal management methods
APMP certification would be viewed favorably
Experience in multiple roles within the proposal management area is desired.
Experience with Customer Relationship Management (CRM) tools
Familiarity and experience with Deltek GovWin IQ
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1206399-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
