### ISSUE TITLE
Systems / Network Analyst (#1207577)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#499]
PeopleTec is currently seeking a Systems / Network Analyst) to support our Huntsville, AL location.

 

PeopleTec, Inc., a 100% employee owned company, is currently seeking a Systems / Network Analyst to provide support to Joint Air Defense Operations. The ideal candidate would have military air defense systems experience as well as applications, IT, and IA experience. 

 

Required Skills/Experience:

Tactical data link protocol and communications expertise
Sensor integration in support of Link-16 and JREAP Tactical Data Links
Assist in process development for applications such as Splunk, Cisco ISE, and SNMP tools
Perform configuration management for operational system to include hardware and software configurations
Provide technical support in connection with tactical and operational level air and missile defense communications systems
Assist in maintaining IA/RMF requirements
Experience developing and writing SOPs
Experience implementing STIGs for network compliance inspections
Experience with active directory (AD), lightweight directory access protocol (LDAP ) and group policy objects (GPO)
Experience working with DoD Classified / Unclassified networks
Working knowledge in Microsoft Office Products
Monitor the network and provide high level expertise with regard to network troubleshooting using tools such as network traffic analyzers
Provide physical and data integration with Battle Management Command, Control, Computers, Communications and Intelligence (BMC4I) systems 
CompTIA Security+
Travel: 10%
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A Bachelor's degree in a related field or 8+ years of military experience in lieu of a degree is required.

 

Desired Skills:

Military experience preferred specifically in Air Defense
Cybersecurity experience
MS Visio experience
 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1207577-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
