### ISSUE TITLE
Software Developer [deciBel Research]; Immediate Need

### ISSUE THREAD

**Issue by spearna** [tech256/jobs#50]
# Hiring!

### About Position [BGQ-1701: Software Developer]
Seeking: (see link above)

### Contact
- Tech256: @spearna
- Location: Huntsville, AL
- Also, apply via the website above.

---

Position Description:
deciBel Research is seeking a Jr to Mid-Level Software Developer with Python, C, and Shell Script programming skills. Will be working with a Senior Level Cybersecurity team to fulfill requirements for the U.S. Army. Limited hands-on hardware experience is required, including the ability to reverse engineer simple subsystems, plan, setup, and conduct simple lab tests and relevant analysis.

Education Requirements: 
Bachelor’s degree in Physics, Science, Technology, Engineering, or Math.

Experience Requirements: 
The successful candidate will know how to program in Python, C, and Shell Script. Linux System Administration skills are also needed. Must also possess a knowledge of Computing and Network Architecture and Integration. Documentation skills are needed as well as developing Verification and Validation processes. Must have familiarity of DISA STIGs, as well as a general Cybersecurity knowledge base.

Special Skills Desired: 
A high degree of self-initiative and a willingness to work with multiple entities throughout the organization, ability to think fast and improvise on the spot and adapt to change quickly. Prior Military experience is a plus. Database experience is a plus.

Applicant selected will be subject to a government security investigation and must meet eligibility requirements for access to classified information. Must be a U.S. Citizen. Minimal travel may be required.

**Comment by iamvery** [comment]
@spearna still relevant?

**Comment by spearna** [comment]
Nope. Thanks for the check. I'll scan the other posts, too.
