### ISSUE TITLE
Technical Writer/Proposal Coordinator (#1217713)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#501]
PeopleTec is currently seeking a Technical Writer/Proposal Coordinator to support our Huntsville, AL location.

 

Our fast-paced Business Development Team is looking for a Technical Writer/Proposal Coordinator with experience in the development of compliant and compelling federal proposals. The successful applicant will be a proactive "go-getter" and must be able to work well as part of a team.

 

Job Duties:

    Coordinate with corporate leadership on proposal development and processes, documentation development and improvement, and miscellaneous assignments as required
    Support the improvement of processes for opportunity identification, qualification, capture, and win rates
    Create proposal inputs and edit writing of others for grammar, readability, and effectiveness
    Manage the continual monitoring of federal opportunity websites (such as GovWin and FBO) for current and future efforts
    Collect, analyze, and report quarterly BD metrics
    Update and maintain the proposal repository (i.e., manage historical proposals along with supporting documentation, such as Past Performance citations, appraisal reports, certification praises, customer accolades, etc.)
    Support capture managers in coordination assignments and document preparation
    Research and understand Statements of Work (SOWs)/Performance Work Statements (PWSs), Requests for Proposals (RFPs), and other proposal requests from US Government customers and prime contractors/teammates
    Communicate and coordinate with teammates for proposal and contractual documentation
    Prepare and manage data calls and follow-ups
    Coordinate efforts across several projects simultaneously
    Organize, track, and communicate proposal requirements to the Proposal Team
    Create writing templates and other proposal tools, such as document outlines and compliance matrices
    Track action items to completion throughout the proposal process
    Perform desktop publishing in compliance with solicitation requirements and company standards
    Manage proposal production (including printing, binding, packaging, and shipping) to ensure that proposal development is on track and on time
    Attend meetings as required
    Perform other duties as assigned

 

Required Skills/Experience:

    Experience using SharePoint in proposal development/maintenance and BD knowledge management
    Understanding of the Federal Government Request for Proposal (RFP) process
    Exceptional internal and external customer service orientation with ability to interface with proposal stakeholders to meet proposal deadlines
    Familiarity and experience with Deltek GovWin IQ
    Proficient planning, time management, and organizational skills
    Experience coordinating and liaising among several parties on a single project
    Meticulous attention to detail and proactive approach to task management
    Ability to manage numerous deadlines and task prioritization with conflicting priorities
    Strong analytical and critical thinking skills
    Flexibility to work efficiently and effectively under tight deadlines in a team environment
    Ability to independently execute assigned tasks with little or no supervision
    Strong process improvement orientation
    Strong working knowledge of MS Office Suite (especially Word, PowerPoint and Excel), experience with Office 365 a plus
    Must be a U.S. Citizen
    Must have the ability to obtain a Secret level DoD Clearance

 

Education Requirements:

A completed bachelor's degree in a technical or business-related field with 10+ years of experience is required. 8+ years of proposal development working within the DoD is highly preferred.

 

Desired Skills/Experience:

    Familiarity with or training in Shipley proposal development methods
    Secret Clearance (or the ability to obtain one)
    APMP certification would be viewed favorably
    Experience in multiple roles within the proposal development process 
    Experience with Customer Relationship Management (CRM) tools 

 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1217713-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
