### ISSUE TITLE
Senior Software Developer (#1219513)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#503]
PeopleTec is currently seeking a Senior Software Developer to support our Huntsville, AL location.

 

The candidate will support the design, development and integration of software systems in support of Army weapon systems. New program and moving fast! Candidate must be a quick learner and ready to hit the ground running. The candidate must be able to effectively interface with the systems engineering team, the warfighter, and engineering SMEs to decompose system requirements and capabilities into product requirements. The candidate is responsible for designing and developing a flexible software application that will operate in a deployed environment across tactical networks as well as within a systems integration lab. Effort includes: integration of legacy software components, modification of existing software components into interfaces and languages that are compatible with the overall architecture, development of new software modules, and developing ICDs. The software development tasks are broad and varied and include time synchronization, communications, algorithm implementation, GUI design/development, data management, processing and visualization. The candidate will be working directly with mid-level software developers on this effort.

 

Required Skills/Experience:

    C/C++
    Java
    Python
    Windows and Linux OS
    Strong written and oral communication skills
    Experience in establishing and maintaining an integrated development environment
    Use tools such as: Eclipse and Git
    Travel: Up to 5%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree in Computer Science, Software Engineering, or related field is required. 10- 15+ years of demonstrated experience is also required.

 

Desired Skills:

    Experience in developing and maintaining web services, mapping/GIS, real time applications, military applications and/or micro services 
    Experience working within a CMMI ML3+ environment Design patterns
    Experience in applying Lean principles to various lifecycle models (Agile, spiral, waterfall)
    Background in safety and security critical systems
    Experience auto-generating code from Matlab/Simulink C#, Exata and QT front-end development experience

 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1219513-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
