### ISSUE TITLE
Millennium Corporation - Software Test Engineer

### ISSUE THREAD

**Issue by jdsteinhauser** [tech256/jobs#505]
# Software Test Engineer

### Overview
Millennium Corporation is hiring a Software Test Engineer in Huntsville, AL.  Qualified candidates must be able to obtain and maintain a TS/SCI Security Clearance.

### Responsibilities

- Balance UI design, user needs and business goals to create intuitive user interface experiences.
- Use advanced design technologies.
- Participate in all aspects of the agile scrum process.
- Communicate and collaborate well with team members.
- Clearly communicate and document your design decisions.
- Work with developers and architects to understand design decisions.
- Talking with users and leadership to understand the exact need and expected functionality.
- Developing test plans and procedures based on user feedback, software requirements, and user acceptance requirements.
- Perform problem solving activities with developers to understand what is causing the potential issue.
- Attend code reviews.
- Perform exploratory testing to find and document defects in the software.
- Developing unit, integration, regression and functional tests.
- Performing formal and informal software testing.
- Conducting feature, regression, integration, user acceptance, and exploratory testing.

#### Required

- Bachelor's degree and 1+ years related experience, additional years of experience will be considered in lieu of degree
- Must be eligible to obtain a DOD Top Secret security clearance
- Experience working in a Windows, MacOS, and/or Linux environment
- Complex problem-solving skills.
- Experience developing test procedures.
- Very detail oriented.
- Passionate about product quality and user experience.
- Experience designing and writing both formal and informal test procedures.

#### Desired

- Experience with Atlassian JIRA and Confluence
- Experience in a fast-iterative environment and product development teams
- Experience writing unit-tests for frontend frameworks and technologies.
- Experience developing integration testing.
- Experience developing UI tests.
- Experience with automated testing frameworks (e.g., Cucumber, Selenium)
- Experience performing unit testing, performance testing, and client-side end-to-end testing (UI testing).
- Knowledge of database fundamentals.
- Experience with source repositories (GIT, Perforce, TFS)
- Experience in code languages (Python, C#, C++, JavaScript, NodeJS)

### Contact
- Tech256: (at)jdsteinhauser
- Location: Huntsville, AL

[Apply Today!](https://careers-millgroupinc.icims.com/jobs/1428/software-test-engineer/job)

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
