### ISSUE TITLE
Millennium Corporation - Sr. Frontend (UI) Web Developer

### ISSUE THREAD

**Issue by jdsteinhauser** [tech256/jobs#506]
# Sr. Frontend (UI) Web Developer

### Overview
Millennium Corporation is hiring a Sr. Frontend (UI) Web Developer in Huntsville, AL.  Qualified candidates must be able to obtain and maintain a TS/SCI Security Clearance.

### Responsibilities

- Balance UI design, user needs and business goals to create intuitive user interface experiences.
- Use advanced design technologies.
- Participate in all aspects of the agile scrum process.
- Communicate and collaborate well with team members.
- Clearly communicate and document your design decisions.
- Work with UX/UI Designers to develop a cohesive user experience.
- Develop and enhancing UI components.
- Working with the backend developers and architect to ensure data from APIs to the UI.
- Solving complex problem using innovative thinking.
- Ability to work with other team members to understand code changes and review business requirements to match development activity.
- Participate in code review
- Review pull requests from other developers.
- Ability to ensure quality of the delivered components.
- Be a value addition to the team to collaborate and achieve success by completing project goals.
- Debugging code and finding problems.

#### Required

- Bachelor's degree and 4+ years related experience, additional years of experience will be considered in lieu of degree
- Must be eligible to obtain a DOD Top Secret security clearance
- Ability to develop, test, implement and maintain complex applications
- Experience developing web applications.
- Experience working in a Windows, MacOS, and/or Linux environment
- Complex problem-solving skills
- Understand authentication techniques such as (JWT, OAuth)
- Web technologies (HTML or HTML5)
- Frontend languages (JavaScript, jQuery, or Typescript)
- Experience with at least one frontend frameworks (e.g., Angular, React, VueJS)
- Experience with at least one frontend styling technologies (e.g., CSS, SCSS, SASS, Grunt, or Bootstrap)
- Experience with database technologies (MYSQL, SQL, Oracle, PostgreSQL or MongoDB)

#### Desired

- Experience with Atlassian JIRA and Confluence
- Experience in a fast-iterative environment and product development teams
- Experience writing unit-tests for frontend frameworks and technologies.
- Ability to design, develop, and maintain applications within the cloud environment

### Contact
- Tech256: (at)jdsteinhauser
- Location: Huntsville, AL

[Apply Today!](https://careers-millgroupinc.icims.com/jobs/1427/sr.-frontend-%28ui%29-web-developer/job)

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
