### ISSUE TITLE
Millennium Corporation - Tech Lead Developer (Full Stack)

### ISSUE THREAD

**Issue by jdsteinhauser** [tech256/jobs#507]
# Tech Lead Developer (Full Stack)

### Overview
Millennium Corporation is hiring a Tech Lead Developer (Full Stack) in Huntsville, AL.  Qualified candidates must be able to obtain and maintain a TS/SCI Security Clearance.

### Responsibilities

- Balance UI design, user needs and business goals to create intuitive user interface experiences.
- Use advanced design technologies.
- Participate in all aspects of the agile scrum process.
- Communicate and collaborate well with team members.
- Clearly communicate and document your design decisions.
- Work with all roles (backend, frontend, UX/UI Designer, and architects) to develop a cohesive experience between API and UI.
- Ability to work with other team members to understand code changes and review business requirements to match development activity.
- Participate in code reviews.
- Facilitate and lead code reviews.
- Review pull requests from other developers.
- Planning sprints and conducting sprint reviews.
- Leading sprint retrospectives.
- Ensure code quality through (code quality metrics, unit tests, functional test, and integration tests)
- Ability to ensure quality of the delivered components.
- Be a value addition to the team to collaborate and achieve success by completing project goals.
- Debugging code and finding problems.
- Establishes and enforces standards for data infrastructure and management.
- Establishes and maintains technology and architecture standards for web APIs, including authentication, authorization and logging.
- Provides input into overall software architecture.
- Uses SQL to create ETL processes and application APIs.
- Ensuring the team is meeting deadlines and business goals.
- Ensuring and maintaining a healthy amount of technical debt.

#### Required

- Bachelor's degree and 8+ years related experience, additional years of experience will be considered in lieu of degree
- Must be eligible to obtain a DOD Top Secret security clearance
- Ability to develop, test, implement and maintain complex applications and databases
- Experience developing complex relational schemas in relational databases.
- Experience developing web applications.
- Experience debugging code and root cause analysis techniques.
- Experience working in a Windows, MacOS, and/or Linux environment
- Complex problem-solving skills.
- Experience with using ORMs (Entity Framework, PonyORM, Django, TypeORM)
- Experience with backend languages (C#, .NET Core, Java, Python, or Node.js)
- Experience with database technologies (MYSQL, SQL, MongoDB, or Graph Databases)
- Experience with Web API development (Restful Web Services or SOAP).
- General knowledge of unit testing, performance testing, and client-side end-to-end testing (UI testing) and associated frameworks and tools.

#### Desired

- Frontend technologies (JavaScript, AngularJS, jQuery, or Typescript)
- Frontend styling technologies (CSS, SCSS, SASS, Grunt, or Bootstrap)
- Experience with Atlassian JIRA and Confluence
- Experience in a fast-iterative environment and product development teams
- Experience writing unit-tests for frontend frameworks and technologies.
- Ability to design, develop, and maintain applications within the cloud environment.
- Experience working with Agile software development methodology.
- Experience working in an R&D or capability development environment.
- Knowledge of cyber security practices and principles.

### Contact
- Tech256: (at)jdsteinhauser
- Location: Huntsville, AL

[Apply Today!](https://careers-millgroupinc.icims.com/jobs/1426/tech-lead-developer-%28full-stack%29/job)

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
