### ISSUE TITLE
Ballistic Missile Defense System Assessment Basic Analyst (#1223865)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#508]
PeopleTec is currently seeking a Ballistic Missile Defense System Assessment Basic Analyst to support our Huntsville, AL location.

 

Duties include:

    Review Integrated Master Test Plan (IMTP) and Integrated Master Assessment Plan to understand planned capabilities, test events, and assessment activities
    Recommend modifications to these documents as necessary to enable a thorough assessment of element capabilities and limitations from a system perspective
    Define assessment requirements sufficiently to test element capability
    Review test execution to understand the tested capability and document any caveats relative to element performance
    Prepare presentations for senior leadership to communicate capabilities and limitations of the element relative to system performance
    Coordinate with test and other MDA element representatives to understand and address concerns and issue

 

Required Skills/Experience:

    Experience with Microsoft Office suite of applications
    Capability to perform analysis of performance of complex systems
    Proficiency in written and oral communication skills to independently develop technical white papers, briefings, as required by the customer to communicate complex technical issues across MDA Engineering Directorate
    Strong communications skills 
    Ability to work within a collaborative environment composed of Government, Prime Contractor, Sub-Contractor and Supporting Contractor personnel in a badge-less contractor environment
    Travel: 5%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree in Engineering, Computer Science or related field with 1+ years of experience is required.

 

Physical Job Requirements:

The candidate must be able to report to Redstone Arsenal VB-2 building.

 

Desired Skills:

    Matlab, Python, C++, and other programming language knowledge and experience
    Familiarity with Missile Defense Agency and Ballistic Missile Defense System
    MDA or military experience
    Understanding of the MDA Engineering practices and processes
    Familiarity with the BMDS system level documentation such as the BMD System Description Document and BMD System Specification

 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1223865-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
