### ISSUE TITLE
GFC Advanced System Analyst (#1223876)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#509]
PeopleTec is currently seeking a GFC Advanced System Analyst to support our Huntsville, AL location.

 

This position will support the Missile Defense Agency (MDA) in developing strategies and plans for assessing system capabilities and limitations based on performance of various elements of the Ballistic Missile Defense System.

 

Duties Include:

    Conducting the BMD system performance capability and limitation assessment of GMD Fire Control (GFC) based upon objective evidence collected from Ballistic Missile Defense System (BMDS) System Flight Test, Ground Test, and Digital Analysis
    Lead Development of GFC Assessment Plans (APs) To Help Drive Assessment Requirements (ARs) For BMDS Testing
    Support GFC Analysis and Reporting for BMD Sensor Assessments, Testing, and Exercises
    Report System Test GFC Capability/Limitation Findings in MDA/EEA Annual Assessment Report (AAR)
    Recommended GFC system level assessment performance capabilities/limitations corrective action plans and mitigation strategies
    Provide DE leadership with well-informed decisions while ensuring the GFC system under assessment is correctly characterized and performance accurately communicated
    Identifying and tracking Action Items or any Watch Items resulting from the Assessment Requirement coordination process

 

Required Skills/Experience:

    Ability to provide DE leadership with well-informed decisions while ensuring the BMDS system under assessment is correctly characterized and performance accurately communicated 
    Ability to develop DE Engineering Board executive level briefings; presenting to executive leadership, coordination and participation in technical meetings
    Interface and coordinate with system assessment stakeholders to ensure technical accuracy and verify correct capture of assessment requirements to support BMD Technical Capability Declarations (TCD) and/or Operational Capacity Baseline (OCB) decisions for DE Leadership
    Coordinate and implement the needs of internal and external customers while addressing all concerns
    Ability to analyze system performance by understanding high-fidelity models
    Provide predictive analysis on system performance for a data source in Ground Test
    Past experience with modeling and simulation
    10+ yrs. of experience supporting the Defense industry 
    Travel: 5%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Master's Degree in Engineering, Computer Science, or related field with 10+ years of experience is required.

 

Physical Job Requirements:

The candidate must have the ability to report to Redstone Arsenal in VB-2 building.

 

Desired Skills:

    Experience with Ground Test supporting the BMD system
    Working Knowledge of Integrated Master Assessment Plan (IMAP), Integrated Master Test Plan (IMTP), Assessment Integrated Product Team (AIPT), and BMD System Test Requirements Processes
    Familiarity with OCB, SEIC, ISG, PCB Engineering Board Processes
    Capability to translate MDA/DE Technical Baseline, Warfighter Requirements, and Standard Test Practices into MDA System Level Assessment Plans (APs) and Assessment Requirements

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1223876-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
