### ISSUE TITLE
Joshua Nielsen - IT/Systems Administration

### ISSUE THREAD

**Issue by jmnielsen7** [tech256/jobs#51]
# Hire me?

# Joshua Nielsen

IT Professional specializing in Systems Administration in HPC environments.

Most recently worked as a Systems Administrator at HudsonAlpha Institute for Biotechnology (HAIB) where I operated as full-time HPC cluster administrator for over five years.

**Experience In:**
• VMWare ESX server management
• SAN hardware administration
• RHEL/CentOS compute cluster administration
• IBM Extreme Cloud Administration Toolkit (xCAT)
• IBM GPFS and Nexenta ZFS administration
• Linux server deployment & kickstarting 
• PXE image deployment solutions
• Apache web server administration
• Torque/MOAB and LSF cluster job schedulers/managers
• BNT, HP, and Cisco Switch management
• Network and server SNMP metric gathering 
• IBM Tivoli and Veeam backup administration

## Resume

PDF Available upon request.
**LinkedIn:** https://www.linkedin.com/in/nielsenjoshua

### Contact
- Tech256: @jmnielsen7

**Comment by jmnielsen7** [comment]
@iamvery How can I apply the appropriate labels to this post?

-JN

**Comment by iamvery** [comment]
I think a repo contributor has to do it. I'll add them when I'm back at the computer unless someone beats me to it ☺

**Comment by iamvery** [comment]
Updated! Look good to ya?

**Comment by jmnielsen7** [comment]
Yes, thank you!

**Comment by iamvery** [comment]
@jmnielsen7 still relevant?

**Comment by jmnielsen7** [comment]
@iamvery Thanks for checking. No, this can be closed now.
