### ISSUE TITLE
Advanced Ground Test System Analyst (#1223885)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#510]
PeopleTec is currently seeking an Advanced Ground Test System Analyst to support our Huntsville, AL location.

 

This position will support the Missile Defense Agency (MDA) in developing strategies and plans for assessing system capabilities and limitations based on performance of various elements of the Ballistic Missile Defense System.

 

Duties Include:

    Review Integrated Master Test Plan and Integrated Master Assessment Plan to understand planned capabilities, test events, and assessment activities
    Recommend modifications to these documents as necessary to enable a thorough assessment of element capabilities and limitation from a system perspective
    Characterize the system performance assessment of threats based upon objective evidence collected from Ballistic Missile Defense System (BMDS) System Flight Test, Ground Test, and Digital Analysis
    Lead development and author Assessment Plans (APs) which help drive Assessment Requirements (ARs) for BMDS Ground Testing
    Lead Analysis and Reporting for BMDS Assessments, Testing, and Exercises. Report System Ground Test Capability & Limitation Findings in MDA/EEA Annual Assessment Report (AAR)
    Collect data for system level assessment performance to report Capability & Limitations corrective action plans and mitigation strategies

 

Required Skills/Experience:

    Provide MDA/DE leadership with well-informed decisions while ensuring the BMDS system under assessment is correctly characterized and performance accurately communicated
    Develop DE Engineering Board executive level briefings; present to executive leadership, coordinate and participate in technical meetings.
    Interface and coordinate with system assessment stakeholders to ensure technical accuracy and verify correct capture of assessment requirements to support BMD Technical Capability Declarations (TCD) and/or Operational Capacity Baseline (OCB) decisions for DE Leadership
    Identify and track Action Items or any Watch Items resulting from the Assessment Requirement coordination process
    Coordinate and implement needs of internal and external customers while addressing all concerns
    Analyze system performance by understanding high-fidelity models
    Provide predictive analysis on system performance for a data source in Ground Test
    Past experience with modeling and simulation
    10+ yrs. experience supporting the Defense Industry
    Travel: 5%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's or Master's Degree in Engineering, Computer Science, or related field and 10+ years of experience is required.

 

Physical Job Requirements:

The candidate must have the ability to report to Redstone Arsenal in the VB-2 Building.

 

Desired Skills:

    Top Secret Clearance
    Experience with Ground Test supporting the BMD system
    Working Knowledge of Integrated Master Assessment Plan (IMAP), Integrated Master Test Plan (IMTP), Assessment Integrated Product Team (AIPT), and BMD System Test Requirements Processes
    Familiarity with OCB, SEIC, ISG, PCB Engineering Board Processes
    Capability to translate MDA/DE Technical Baseline, Warfighter Requirements, and Standard Test Practices into MDA System Level Assessment Plans (APs) and Assessment Requirements 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1223885-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
