### ISSUE TITLE
Operations Analyst/Integrator (#1223927)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#511]
PeopleTec is currently seeking an Operations Analyst/Integrator to support our Huntsville, AL location.

 

Duties Include:

    Provide programmatic support to a product line in an Army product office through programmatic, managerial, and technical/operational recommendations
    Support product component area operations within project office environment
    Use independent judgement to plan, prioritize and organize a diversified workload in a high-pace and detail oriented environment
    Responsible for updating and maintaining documentation, formulating detailed responses to taskers thru the integration of schedule, budget, and technical/performance activities
    Communicate and coordinate across engineering, business, and logistics functions in order to prepare complete and accurate responses to time sensitive requests for information
    Participate in meetings, supports program management reviews, schedule working groups, and prepares briefing materials, notes, responses, and trip reports

 

Required Skills/Experience:

    Familiar with DoD and U.S. Army acquisition policies and regulations
    Demonstrate strong attention to detail
    Understand roles and responsibilities of functional areas
    High degree of professionalism and experience in a fast paced work environment
    Ability to perform in a diverse work environment supporting multiple military, government civilian, and contractor team members
    Experience in related field of expertise at the program/project level
    Proficient level experience with utilization of Microsoft Office Suite of products (Word, Excel, PowerPoint, Outlook) and Adobe Acrobat
    Demonstrate experience working individually as well as organizing and facilitating working groups
    Ability to prepare detailed written reports and briefings suitable for presentation to senior level military and corporate leadership, as well as present material orally
    Experience with Planning, Programming, Budgeting, and Execution processes at Project, PEO, and Department of the Army levels
    Understand the integration of requirements, budget, and programmatic processes
    Travel:Up to 5%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A completed Bachelor's Degree in a related field (Procurement and Acquisition Management, Systems Engineering, or equivalent) and 5-10 years of relevant work experience is required.

 

Desired Skills:

    5-7 years of Program Management experience for similar DoD Program Offices 
    Knowledge of DoD program planning and budgeting cycles and reporting requirements
    Knowledge of the DoD Acquisition process and procurement regulations
    Collection and analysis of information to assess cost, schedule, and performance associated with risk identification and risk management activities

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1223927-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
