### ISSUE TITLE
Computer Network Defense (#1226248)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#513]
PeopleTec is currently seeking a Computer Network Defense to support our Huntsville,AL location.

 

Candidate will be responsible for consolidating ACAS vulnerability reports, HBSS compliance metrics, incident report mitigation into one consolidated view/product for all subscribers.

 

Duties Include:

Conduct deeper analysis on that consolidated data to identify recommended mitigation plan for multiple sites, to include identifying vulnerabilities and recommending compliance corrections that will address the vulnerabilities
Provide intrusion-detection, malware and threat analysis, monitoring, and incident reporting for Non-classified Internet Protocol Router Network (NIPRNET) , Redstone Arsenal, Defense Research and Engineering (DREN) and Army Research Lab (ARL) networks
Conduct network vulnerability assessments using Interrogator tool to evaluate attack vectors, identify system vulnerabilities and develop remediation plans and security procedures
Review alerts, snort signatures, and packet-level data collected from sensors on a daily basis and report findings to RCERT-CONUS, US Cyber Command, and local site
Provide daily support to the Army Research Lab Computer Network Defense as a CND analyst
Monitor between 10 -27 network "sensors" daily that collect network traffic to determine malicious activities
Conduct network vulnerability assessments using monitoring tools from Interrogator and G80 command line to evaluate attack vectors and identify system vulnerabilities
Monitoring tools used are Snort and TCPDUMP
Follow up on all incident reports, confirm mitigations, track POA&M due dates, and escalate 
 

Required Skills/Experience:

CySA or CEH certification 
Travel: 10%
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

2-4 years of relevant experience is required.

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1226248-305157

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been over 90 days since the last activity, we will be closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please reach out to @PallasStreams.
