### ISSUE TITLE
.NET Developer Position

### ISSUE THREAD

**Issue by rocketcityexpresso** [tech256/jobs#55]
# .NET Developer

### About Position
Doesn't require Security Clearance
Our client is looking for a technical professional with programming experience in C# & C++, and .net. An added bonus would be experience with MVVM, MVC, WPF, winforms or WCF. This team supports the Naval Health Research center by building models and simulations for DoD medical planning. This project will help to optimize the operational health and readiness of the nation's armed forces.

### Contact
Elizabeth Mapp | Recruiter – Applications
T 256.924.7749 | F 256.924.7750 | emapp@TEKsystems.com
310 The Bridge Street – Suite 160
Huntsville, AL 35806

**Comment by iamvery** [comment]
Position filled?

**Comment by iamvery** [comment]
Ah, perhaps reposted https://github.com/tech256/jobs/issues/56

**Comment by rocketcityexpresso** [comment]
Aye. I didn't want to post under the wrong github account :)
