### ISSUE TITLE
.NET Developer

### ISSUE THREAD

**Issue by oconnef** [tech256/jobs#56]
# .NET Developer

### About Position
Doesn't require Security Clearance
Our client is looking for a technical professional with programming experience in C# & C++, and .net. An added bonus would be experience with MVVM, MVC, WPF, winforms or WCF. This team supports the Naval Health Research center by building models and simulations for DoD medical planning. This project will help to optimize the operational health and readiness of the nation's armed forces.

### Contact
Elizabeth Mapp | Recruiter – Applications
T 256.924.7749 | F 256.924.7750 | emapp@TEKsystems.com
310 The Bridge Street – Suite 160
Huntsville, AL 35806

**Comment by iamvery** [comment]
@oconnef still relevant?

**Comment by craftLouisville** [comment]
Probably not, though I'd presume TEKSystems is always looking for people.
