### ISSUE TITLE
Web App Stylist with CSS +LESS Experience

### ISSUE THREAD

**Issue by cara023** [tech256/jobs#57]
# Hiring!

### About Position

Sharp Auction Engine is looking for a new teammate or several freelancers who specialize in CSS + LESS to bring a more customized, personal look to our client's web pages.

Duties:

Work with Senior Staff as well as independently to write custom CSS code for software interface. 
 
Requirements:
- 2-3 years experience with CSS + LESS
- Bootstrap 3
- Excellent communication skills and an eagerness to work with an awesome team

 Send all resumes to social@sharpauctionengine.com
### Contact
- Tech256: @martin478
- Twitter: @auctionengine
- Location: Huntsville... Maybe Anywhere if you're disciplined
- etc...

---

**Comment by cara023** [comment]
Could this also say Freelance?

**Comment by iamvery** [comment]
@cara023 still relevant?

**Comment by AshleyMartin478** [comment]
@iamvery yes!

**Comment by mjcarroll** [comment]
@cara023 still relevant?
