### ISSUE TITLE
Software Engineer- C / C++ for Harman

### ISSUE THREAD

**Issue by dannagle** [tech256/jobs#59]
# Hiring! SVSI by Harman (part of Samsung) 
Apply here:
https://jobs.harman.com/job/Huntsville-Software-Engineer-C-C%2B%2B-AL-35801/397352700/

### About Position
Develop new and analyze existing embedded software to add features, make modifications, fix bus, and/or port to different platforms.

### Contact
- Tech256: @dannagle
- Twitter: @NagleCode
- Location: Huntsville

**Comment by blmeadows** [comment]
@dannagle is this still relevant?

**Comment by dannagle** [comment]
Nope.
