### ISSUE TITLE
QA Analyst/ Automated Tester

### ISSUE THREAD

**Issue by AshleyMartin478** [tech256/jobs#60]
Hiring!

**# Sharp Auction Engine
www.sharpauctionengine.com**

Sharp Auction Engine is looking to bring on a new team member in to improve our code quality. This position will work closely with our development and support staff to reduce the amount of software abnormalities directly affecting the customer’s experience. 

**Job Description:**
To oversee web-based application testing
Develop automated test suites
Mentor junior engineer staff

**Requirements:**
2+ years experience with Manual and Automated testing preferred
Basic understanding of Web PhP, JavaScript
Ability to create test plans and or test cases
Experience working with developers in an Agile/Scrum environment
Strong verbal and written communication skills (required)
Strong expertise in use of stress testing tools and software testing methodologies
Excellent grasp of basic SQL queries and Internet technologies

### Contact
- Tech256: @martin478
- Location: Huntsville, AL
- Email: social@sharpauctionengine.com

**Comment by mjcarroll** [comment]
@AshleyMartin478 still relevant?
