### ISSUE TITLE
Software Sales Position

### ISSUE THREAD

**Issue by AshleyMartin478** [tech256/jobs#62]
Sharp Auction Engine

www.sharpauctionengine.com

**Description:**
The SAE Software Sales Representative works hand in hand with our Marketing & Support Teams to represent our product at its best. This person is an outgoing, self motivated individual who reaches out to auctioneers nationwide.  Previous sales experience is a plus. 

**Responsibilities**
- Must be tech savvy and able to talk to users who are not tech savvy
- Works with the Customer Success Manager to convert trial cases into customers
- Identify markets for our product. Consistent personal prospecting and lead follow-up on qualified opportunities for the company.
- Achieve assigned quotas and associated performance standards
- Manage and progress identified sales opportunities in accordance with company's standard sales process.
- Reach out to a minimum of 10-15 leads a day through personal email and sales calls
- Thorough knowledge of the SAE software, in order to better explain, demonstrate, and sell the product to new users. Help customers maximize their software package
- Carrying oneself in a professional manner when interacting with potential clients
- Responsible for proper documentation and follow-through of all sales
- Familiar with Hubspot or prior experience with and CRM a plus
- Recognize the customer's specific needs and adapt
- Stay aware of competitors features to compare products 
- This position is the point of contact for all sales inquires

**Benefits**
- Full Time
- Competitive salary for experience
- Health care/401k
- Commission is uncapped
- Additional bonuses on large prospects and bounties on new territories

Email resumes to social@sharpauctionengine.com

### Contact
- Tech256: @martin478
- Email: social@sharpauctionengine.com

**Comment by mjcarroll** [comment]
@AshleyMartin478 Still relevant?
