### ISSUE TITLE
Brandon M. Bost - Software Developer (C++, C#, HTML/CSS/JS, etc.)

### ISSUE THREAD

**Issue by bmbost** [tech256/jobs#64]
# Hire me?

## Brandon M. Bost
Graduated from Athens State University in 2016 with a Bachelor of Science degree in Computer Science, CIS Option. Have kept skills up by joining freeCodeCamp.com and pursuing the Front End Developer Certificate since graduating, currently halfway through curriculum. Recently joined The Odin Project to broaden development skills and learn Ruby and Rails. Used skills learned so far in freeCodeCamp to create my own portfolio website as well.

### Resume
www.creativen00b.com

### Contact
- Tech256: @frenzyheart
- (256) 529-3058
- bmbost1983@gmail.com

**Comment by mjcarroll** [comment]
@bmbost still relevant?

**Comment by bmbost** [comment]
No, I was able to find a developer job. Forgot I posted this.
