### ISSUE TITLE
Jr. Radio Frequency Engineer (#1386735)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#649]
PeopleTec is currently seeking a Jr. Radio Frequency Engineer to support our Huntsville, AL location.

 

This position will require the selected candidate to be able to incorporate continuous and pulsed RF signals through antennas, connector, cables and processors in the arena of GPS navigation, transponder and Identification Friend or Foe (IFF). The FW ASIL includes aircraft bus 1553 and ARINC 429 channels that may be monitored simultaneously with the RF signal.

 

 

Required Skills/Experience:

    Conduct research and recommend for provisioning suitable RF cable and connectors that will interconnect subsystems
    Operate laboratory equipment in the manner of waveform analysis for timing and distortion of signal and use laboratory equipment to inject replicated signals
    Conduct signal analysis for signal strength and integrity, waveform distortion and bandpass limitation or signal throughput using spectrum analyzers, network analyzers, oscilloscopes and signal generators
    Interface with diverse government agencies in the manners of frequency allocation, approval and certification for airspace and signal management. Signal delay from the RF subsystems would be an important data product
    Be proficient in the MS Office series of products of Word, Power Point, Excel, Outlook and Visio
    Have experience writing technical reports
    Capable of working independently without continuous oversight after receiving initial training
    Be a demonstrated self-starter with strong interpersonal communications skills 
    Ability to work across geographically diverse groups
    Travel: None
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

STEM related Bachelors Degree and at least two years of related experience

 

Physical Job Requirements:

The laboratory replicates the equivalent functionality that is found in several aircraft series used in the Special Electronic Mission Aircraft (SEMA) fleet utilizing actual and simulated aircraft equipment.

 

Desired Skills:

    Experience or studies related to navigation, identification or communication
    Experience working with Labview and a CAD modeling software
    Direct experience with army aviation equipment and aircraft wiring

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1386735-424912

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasStreams will follow up with you.
