### ISSUE TITLE
UI/UX Web Application Developer 

### ISSUE THREAD

**Issue by Dosshoggin** [tech256/jobs#65]
# Hiring!

### Application Web Developer

ResourceTek is the Human Capital division of BWSC, Inc., a multi-discipline Engineering firm. We specialize in providing technical services to industry and government in all areas of Engineering, Information Technology, and a broad range of other Technical disciplines. 

In support of our client that specializes in utilizing modeling & simulation technology to support weapon systems development, we are seeking an Application Web Developer in Huntsville, AL.  This is a project oriented position.

Responsibilities
•	Initial – Web based; scalable to mobile
•	Clean, fun, leverage the 3D mascot, consistent look & feel, branding
•	Intuitive – use implied input standards for menu’s, drop downs, etc. (no new concepts)
•	Storyboard/visual hierarchy all pages (Affinity diagram - denoting dependencies)
•	SEO Fundamentals/Considerations
•	Clear call to action on each page – limit number of choices per page
•	Linking to other sites via API calls
•	Fast loading/operation – limited use of forms/questions – limit <1 min per page action
•	Make it stand out – fresh and novel – not bland/sanitary or common
•	Inverted design – critical (important) content first
•	Appropriate/balanced use of imagines
•	Audience – broad age range
•	Quick turn, flexible – AGILE process; piece out to developers
•	Support analytics – information architecture

### Contact
- Tech256: @andrew
- Location: Huntsville, AL
- adoss@resource-tek.com
-256.533.4336

**Comment by Dosshoggin** [comment]
Feel free to contact me directly via email with your resume or give a call directly at the office. 
Andrew Doss
adoss@resource-tek.com
256.533.4336

**Comment by mjcarroll** [comment]
@Dosshoggin is this still relevant?
