### ISSUE TITLE
SW IV&V Engineer (#1387441)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#650]
PeopleTec is currently seeking a SW IV&V Engineer to support our Huntsville, AL location.

 

PeopleTec is seeing an Independent Verification and Validation (IV&V) Software Engineer to support a team at S3I RSA. The selected candidate will support the IV&V for the Improved Turbine Engine Program (ITEP) software and controls executing on the Electronic Engine Controller. This also includes the Engine Health Management System algorithms. Principal Duties and Responsibilities.

 

Duties Include:

    Provide in-depth software IV&V technical expertise for performing software IV&V reviews, evaluations, analysis, simulation, and testing on the ITE software
    Provide technical coordination and support technical review meetings as requested
    Perform code level IV&V for ITEP software to ensure the engine vendor has delivered a complete and accurate set of software source code, build scripts, and execution binaries
    Participate as the ITE SW IV&V agent in IPT's, design reviews, code reviews, test plan reviews, test report reviews, and problem report reviews
    Review and analyze the ITE ECS software requirements to verify that the software requirements are developed to satisfy the system requirements allocated to the software
    Witness engine vendor incremental software release test events

 

Required Skills/Experience:

    Two years applicable software engineering experience
    Ability to obtain a DoD Secret Clearance 
    Travel: None
    Must be a U.S. Citizen

 

Education Requirements:

B.S degree in computer science, software engineering, or other related technical field or equivalent experience

 

Desired Skills:

    Knowledge of and familiarity with the IEEE 1012-1998 Standard for Software Verification and Validation
    Familiarity with aviation systems, engines, engine control units, and aviation systems integration
    Demonstrated experience with software architecture, systems engineering, software integration, and verification and validation
    IV&V experienced with at least one of the following: evaluating software requirements for completeness, correctness, consistency, accuracy, and readability and testability
    Test Verification including test witnessing, test analysis, test plan analysis, and system design analysis
    Strong written, verbal, and interpersonal communication skills with ability to interact well in group meeting/working

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1387441-424912

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasStreams will follow up with you.
