### ISSUE TITLE
Front End Engineer - D&D Beyond

### ISSUE THREAD

**Issue by drmcknight** [tech256/jobs#651]
[D&D Beyond](https://www.dndbeyond.com) is currently seeking a Front End Engineer!

D&D Beyond is the official digital toolset for Dungeons & Dragons fifth edition, and aims to enhance the D&D experience by making game management easier for players both at the table and between sessions. Players can create, manage, and keep track of characters, as well as browse all of the official rules in the compendium. We’re also giving players the ability to create custom homebrew content to use in the toolset.

Our D&D Beyond team is seeking an experienced front end engineer that is passionate about client-side technologies and creating the highest quality D&D tools in the market. This involves working with a cross-functional team on a day-to-day basis and participate in establishing best practices for the organization via the Front End Guild. You will build official digital tools for Dungeons & Dragons - a fast-growing, extremely customer-focused product - and create highly interactive user experiences collaboratively designed with experts. You will also have the opportunity to delight millions of users with the products you help create, while shipping code to production multiple times a week.

### Responsibilities:
- Building high-quality solutions with modern web technologies such as React, HTML5, and Sass
- Consuming RESTful APIs using industry-standard best practices
- Contributing to and consuming NPM libraries, both internal and open source
- Giving quality feedback on code reviews for peers
- Writing maintainable, and unit-tested code at scale
- Researching and learning new technologies and sharing your knowledge with your peers
- Participating in on-call rotations for full-stack infrastructure
- Learn and grow your skills while teaching and mentoring your peers

### This is an exciting opportunity because you will:
- Build official digital tools for Dungeons & Dragons
- Create highly interactive user experiences collaboratively designed with experts
- Work on a fast-growing, extremely customer-focused product
- Work within a cross-functional team of experienced and passionate people
- Learn and grow your skills while teaching and mentoring your peers
- Delight millions of users with the products you help create
- Ship code to production multiple times a week

### You will be successful here because you:
- Have 4+ years of software engineering/ web development experience focusing on the front end
- Demonstrate team ownership over individual silos
- Practice continuous improvement
- Value delivering software value as quickly as possible
- Aren’t afraid to experiment, fail, and learn from your mistakes
- Consider the big picture and think long term about solutions
- Understand best practices regarding performance and caching
- Seek out and offer constructive feedback
- Thrive working on an agile and cross-functional team
- Are comfortable challenging team members and the status quo
- Are passionate about growing as a team member

### Bonus if you have experience with:
- React/Redux, JavaScript transpilers (Babel, and CSS pre-processors (Sass, PostCSS)
- Responsive web design, accessibility web standards and best practices (WAI-ARIA, WCAG)
- Functional programming
- Test-driven development
- Cross-browser support, feature flags, web animations, and inline SVG
- Creating and maintaining CI/CD build and deploy processes for JavaScript packages and applications
- AWS infrastructure integration and management

Please apply at the link below!
https://www.fandom.com/careers/listing/2160294?gh_jid=2160294

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasStreams will follow up with you.
