### ISSUE TITLE
Model Based System Engineer and Analyst (#1388166)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#653]
PeopleTec is currently seeking a Model Based System Engineer and Analyst to support our Huntsville, AL location.

 

The candidate will support the Advanced Integration for Countering Emerging Threats (AICET) Program, which is a pilot program for the Integrated Air and Missile Defense (IAMD) Battle Command System (IBCS) Program. The objective of AICET is to enhance a net-centric air and missile defense architecture by developing and maturing concepts utilizing low, mid and high fidelity simulations to prototype algorithms and software to support rapid integration into an Agile Large Solution development environment. The team uses state of the art Model-Based Systems Engineering (MBSE) tools and processes to perform concept definition, conduct architecture studies, to deliver a viable capability enhancement to the IAMD Program Office. The concept work drives the development of the process/tool infrastructure, and the concept products validate the efficiency and efficacy of the feature to insert in the software development backlog. The candidate will be responsible for supporting the development and maintenance of the IBCS MBSE model baseline, conducts analyses of interfaces/functional behaviors, perform consequence assessments of proposed changes to IBCS functional behaviors, support the strategy for implementing new capabilities, and coordinate with the IAMD PO and other MBSE users/ clients.

 

Required Skills/Experience:

    Five to ten years of demonstrated experience working on a technical program that employed MBSE methodologies
    Working experience on joint engineering teams to develop a systems engineering process architecture and perform concept development of new capabilities
    Familiarity with Model-Based Systems Engineering processes and tools, including SysML and UML
    Travel: None
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

Bachelor of Science Degree or higher in a science or technology discipline (e.g. engineering, physics, math, computer science). Need five to ten years of demonstrated experience.

 

Physical Job Requirements:

Ability to report to a lab on the 2nd floor of a building

 

Desired Skills:

    Experience with Rhapsody or MagicDraw is a plus but not necessary
    Familiarity with Integrated Air and Missile Defense, PAC-3, or other directly related AMD programs
    Familiarity with radar systems, including PATRIOT, AN/TPY-2, LTAMDS, and/or G/ATOR
    Possess an ability to plan, coordinate, and support product development in a fast-paced, rapidly changing environment
    Capable of providing engineering/scientific support on systems, system elements, interfacing systems, components, devices, and/or processes for developmental and operational weapon system engineering programs
    Familiarity with complex software systems development
    Familiarity with modeling & simulation development, planning, execution, and data analysis
    Familiarity with developing engineering processes
    Excellent social, organizational, management and leadership skills
    Capability to use the Microsoft Office package to include: Outlook, Word, PowerPoint, and Excel

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1388166-424912

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasStreams will follow up with you.
