### ISSUE TITLE
Information Assurance Officer / Systems Administrator (#1392143)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#654]
PeopleTec is currently seeking an Information Assurance Officer / Systems Administrator to support our Huntsville, AL location.

Primary responsibilities would include information assurance support, systems administration, network configuration and monitoring. Excellent oral and written coordination and communication with internal team members, across government customer functional teams, command system administration, and senior and junior information assurance team members is required. This program requires excellent technical domain knowledge.

 

Required Skills/Experience:

Minimum of 5+ years of related work experience 
Candidate must display and demonstrate knowledge of the Department of Defense Risk Management Framework (RMF) policies and procedures
Candidate must display and demonstrate knowledge of automated information systems procurement, configuration, deployment, and maintenance
CompTIA Security + and A+ or other computing environment certifications to meet DoD 8570 IAT II are required upon employment
Significant experience as a Linux system / network administrator is desired
Advanced certifications such as Certified Ethical Hacker, CCNA Security, CASP+CE, GCIH, or CISSP are desired
Virtualization/cloud experience or certifications with provisioning or automation of computing tasks is desired.
Travel: 5%
Must be a U.S. Citizen
An active DoD Top Secret/SCI clearance is required to perform this work. Candidates are required to have an active Top Secret/SCI clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A completed Bachelor's Degree in a related field and a minimum of 5 years of related experience is preferred. Experience accepted in lieu of Bachelor's requirement.

 

Physical Requirements:

Requires ability to lift up to 30 lbs. 

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1392143-424912

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasStreams will follow up with you.
