### ISSUE TITLE
Earned Value Management Analyst (#1393415)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#655]
PeopleTec is currently seeking an Earned Value Management Analyst to support our Huntsville, AL location.

 

Duties Include:

Perform earned value analysis
Participate in IBR activities
Perform schedule analysis
Write technical reports Interoperate EVM data received from other OEMs/Government agencies Work Closely with Control Account Managers to develop budgets and resource allocations to support IPT and Program goals Work with Business Analyst, and Schedulers to produce, prepare and analyze Earned Value/Financial reports Supported cost/schedule reconciliation efforts for Month End IPMR submittals
Prepare briefings for the customer and prepare management reports
Review and analyze data and produce reports in support of acquisition programs to include but not limited to Monthly Acquisition Report (MAR)
Candidate will be responsible for arranging travel using the DoD Defense Travel System (DTS) to include: travel itineraries, hotel accommodations, transportation, TDY agendas and briefing packets and ensure the vouchers are submitted in a timely fashion for settlement of the traveler's government travel card
Assist in the administration of the Automated Time Attendance and Production Systems (ATAAPS)
Other duties to include: facilitating Support Agreements Coordination and Repository, Manpower Tracking, Tasker Input and Tracking, Management Controls, Historical Reporting, Coordinate and Update Weekly Staff Call Slides for Business Division
 

 Required Skills/Experience:

Working knowledge of Earned Value Management (EVM) Industry Standard, ANSI/EIA 748-A
Prior experience implementing EVM systems to include: system description, implementation procedures, Integrated Baseline Reviews (IBR) and system verification/validation
Hands-on experience with EVM software to include, but not limited to: wInsight, Cobra, Micro Frame Project Manager (MPM), Microsoft Project, or Primavera.
Must have experience with utilization of Microsoft Office Suite products (Word, Excel, PowerPoint, Outlook, Project) and Adobe Acrobat
Must have a working knowledge of DTS and ATAAPS
Excellent written and oral communication skills
Ability to prepare detailed written reports and briefings suitable for presentation to senior level military and corporate leadership, as well as present material orally.
Demonstrated experience working individually as well as organizing and facilitating working groups.
Capable of conducting independent analyses, evaluation, and assessment of logistics.
Travel:Up to 10%
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

A completed Bachelor's Degree in a related field with 10 years of relevant* work experience.

*Relevant experience = directly traceable to job description requirements 

 

Desired Skills:

Experience with GFEBS, PMRT, and/or other Government financial systems.
10+ years of IMS/EVM experience for similar DoD Program Offices preferred.
Knowledge of DoD program planning and budgeting cycles and reporting requirements.
Knowledge of the DoD Acquisition process and procurement regulations.
Collection and analysis of information to assess cost, schedule, and performance associated with risk identification and risk management activities.
Other scheduling software applications such as: ARTEMIS Microsoft Project Open Plan Professional PrimaVera AMS Real Time Project Milestones Professional
 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1393415-424912

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasStreams will follow up with you.
