### ISSUE TITLE
Embedded Developer in Huntsville

### ISSUE THREAD

**Issue by markatradiobro** [tech256/jobs#656]
# Opportunity

RadioBro is seeking to grow its software development team. We're looking for a new team member that is interested in developing code on ARM devices like Atmel D21/E70/A5. 

## Requirements

This position can be full time, part time, co-op, or internship.

US citizenship required.

We make new designs for circuits, and (once virus moves on) plan to work with the hardware as an integral part of the team. Qualified team members can work from home in the interim.

## Application Process

We're a small company. Feel free to apply directly to me or through FB/email. Don't hesitate to reach out for more information!

![94333467_2044375955705938_7352859950621655040_n](https://user-images.githubusercontent.com/30094002/80514413-16b68d80-8946-11ea-8af5-241ddc838e9a.jpg)

**Comment by markatradiobro** [comment]
Accidentally closed. Reopened now.

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasStreams will follow up with you.
