### ISSUE TITLE
Quality Analyst (#1401072)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#658]
PeopleTec is currently seeking a Quality Analyst to support our Huntsville, AL location.

 

PeopleTec is seeking a Software Quality Analyst/Engineer to support the US Army S3I Directorate. The candidate will perform Software and Systems Engineering development activities and assist in the implementation of quality programs for hardware, software and service products. Responsibilities include but are not limited to the following:

Developing a Software Quality Surveillance Plan to document quality activities in compliance with S3I processes and procedures
Implementing Quality Standard Operating Procedures (SOPs) and other processes per ISO regulations
Supporting materiel releases as documented in Army Regulation 700-142, Type Classification, Materiel Release, Fielding, Transfer, etc.
Reviewing defined processes, management plans for conformance to the EIPC process and provide feedback
Measure and analyze the effectiveness of quality processes
Conducts audits of projects processes and deliverable products
Recommends improvements to the processes and procedures
Assist in developing management plans as requested
Documenting known deficiencies via Quality Problem Reports (QPRs)
 

Required Skills/Experience:

Minimum of 8 years experience
Must have a working knowledge of databases, spreadsheets, and the Software Development Life Cycle (SDLC)
Travel: None
Must be a U.S. Citizen
An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
 

Education Requirements:

Bachelor of Science in Computer Science, Engineering, Information System's or related scientific discipline. 5-10 Years experience

 

Desired Skills:

 Advanced Degree 
 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/1401072-424912

**Comment by PallasStreams** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasStreams will follow up with you.
