### ISSUE TITLE
Developer Looking for Freelance Work

### ISSUE THREAD

**Issue by dmhamilt** [tech256/jobs#66]
# Hire me?

## David Hamilton
Design Web Applications, 
Document with UML, SysML, MBSE.
Develop Database in MySQL, Access, or SQL
Web Based Languages and Frameworks: PHP, Laravel, Vue.js, JQuery, JS, CSS
Also have Experience in VBA for Excel, Access, and Word

### Contact
- Tech256: @dmhamilt
- (256) 614-5469

**Comment by mjcarroll** [comment]
@dmhamilt is this still relevant?
