### ISSUE TITLE
Senior .NET Developer

### ISSUE THREAD

**Issue by RocketCityHR** [tech256/jobs#67]
SENIOR .NET DEVELOPER

Cybernetic Retail Solutions is a boutique retail consultation firm.  We employ experts in all operational segments of retail from merchandising, point of sale (POS), warehouse systems, sales audit, loss prevention, customer relationship management (CRM), accounting, enterprise selling (Omni Channel), and e-commerce.  We provide our clients with strategic planning, business process reviews, custom system solutions, and provide an easy to use toolset to grow sales and drive efficiencies.  We currently have clients nationwide including California, Florida, Maryland, Texas, New York, Washington, and Massachusetts.

We are looking for driven, energetic, results oriented and committed candidates to become part of our firm as we grow to meet client needs.  As part of our firm you will learn how different retail companies run their business, learn about their challenges, be exposed to a variety of retail systems, be given the opportunity to provide solutions, and see your work directly impact the clients we work with.

Responsibilities:

    Work with project management and systems analyst to understand development requirements
    Provide system solution design options
    Develop new web based applications
    Develop APIs
    Develop integration using other 3rd party APIs and Web Services
    Develop flat file feeds and automated processes
    Modify existing applications and integration feeds
    Create and modify database tables, views, functions, and stored procedures
    Ability to write T-SQL for new and existing applications
    Troubleshoot and resolve technical issues
    Mentor and assist with managing lower level programmers
    Assist with determining best direction for code management and implementing best practices

Qualifications:

    Programming Languages: C# (preferred), Visual Basic (good to have), HTML, CSS, XML
    Database: Microsoft SQL Server
    Software: Microsoft Visual Studio (ASP.NET)
    Desire to understand existing client systems and database structure
    Excellent communication skills
    Excellent problem solving and analytical skills
    Ability to design custom application solutions
    Ability to research issue resolutions independently and escalate to supervisor as needed
    Excellent time management skills to complete assigned tasks without direct supervision on time
    Ability to multitask
    Ability to work in a team environment and deal with different personality types
    Comfortable with providing feedback on system improvement suggestions
    Must be able to sit and work at a computer for extended periods of time
    May be required to work nights and weekends depending on the project or critical system issues
    Proven work experience or a degree in Information Systems, MIS, Computer Science, or Computer Engineering
    Retail experience is a plus

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/573265-194482

**Comment by mjcarroll** [comment]
@RocketCityHR is this still relevant?

**Comment by RocketCityHR** [comment]
Michael,

The Senior .NET Developer is not still relevant.

Thanks!
