### ISSUE TITLE
ITEP Integration SME (#1470633)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#680]
PeopleTec is currently seeking an ITEP Integration SME to support our Huntsville, AL location.

 

Duties Include:

    Serve as Project Engineer for the Improved Turbine Engine (ITE) for air vehicle integration within the Aviation Turbine Engine Project Office
    Serve as the subject matter expert for hardware integration of the Future Attack Reconnaissance Aircraft (FARA)
    Support ITE contract technical, cost, and schedule requirements, and IAW ATE Technical Division best practices
    Collaborate with the aircraft and engine Prime Contractors' program and technical leads and other personnel to ensure the contract technical work tasks are identified, defined, scheduled, resourced, and executed
    Coordinate technical positions with Government airworthiness and test evaluation organizations to define and measure the program path to secure airworthiness qualification and safety confirmation of changed and new configurations
    Support engine/integration lead to manage prime contractor performance to meet technical requirements, develop program plans and cost/budget/schedule estimates
    Coordinate with other ITE Integrated Product Teams (IPTs) and UHPO, AAHPO, FARA CP, and FARA PoR air vehicle teams to ensure optimum integration of the engineering segments
    Work with and support a diverse group of Government, support contractor, and OEM technical and subject matter experts to meet ITE goals and objectives
    Support the ITE Systems Engineering, Propulsion, Controls and Software, Integration, FARA and T&E IPTs/WGs.

 

Required Skills/Experience:

    10+ years of relevant work experience in a technical field related to commercial or military aviation
    3+ years of work in a technical field related to RotaryWing Aviation Propulsion/Turbine Engines, or equivalent academic experience/coursework
    Knowledge of contract requirements and documents (e.g., Statements of Work, Integrated Master Schedules)
    Travel: 25%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

MA/MS +10 years of experience or BA/BS +18 years of relevant experience required. 24 years of strong relevant experience may be substituted in lieu of a degree.

 

Desired Skills:

    2 years of work in a Project/Program Management Office or equivalent technical contract management experience
    Experience working on Army Aviation development programs
    DAWIA Level III or Project Management Professional Certification

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1470633-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
