### ISSUE TITLE
Sr. Systems/Software Engineer  (#1471113)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#681]
PeopleTec is currently seeking a Sr. Systems/Software Engineer to support our Huntsville, AL location.

 

The Senior Systems/Software Engineer will be focused on autonomous systems. The successful candidate will have expertise in analysis, design, development, integration, and test of software intensive complex autonomous systems. The candidate will have a strong working knowledge of artificial intelligence and autonomy. The candidate should have prior experience working with unmanned systems and/or robotics with a focus on software. This position will be as an individual contributor who will be the program's subject matter expert in autonomous software systems supporting a DoD customer.

 

Required Skills/Experience:

    Strong knowledge of systems and/or software architecture. This includes experience with the development and analysis of architecture using UML, SysML, DoDAF, and/or other applicable modeling languages
    Experience with software architecture tools such as NoMagic Cameo, Sparks Enterprise Architect, IBM Rhapsody.
    Understanding of Model Based Systems and Software Engineering principles and tools
    Experience designing and developing modular software within a compartmentalized autonomy architecture
    Experience developing detailed software and systems test and evaluation plans
    Experience conducting field testing of computing solutions including fielding computer hardware and software on manned, unmanned systems or mobile robotic systems for flight/field demonstration
    Strong working knowledge of standard Microsoft office tools
    Capable of working independently, as a team member, or leading tasks to solve engineering and scientific problems within a research and development environment
    Demonstrated ability to work in a multidisciplinary and physically distributed team environment
    Proven ability to effectively communicate by verbal and written methods to include: face-to-face, phone, briefs, emails, information papers, white papers, executive summaries, agendas, minutes, plans, and reports
    Travel: 15%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

Bachelor's Degree in Engineering, Computer Science, or Mathematics and at least 10 years of relevant experience required

 

Desired Skills:

    Master's Degree in Engineering (Robotics, Electrical, Aerospace, Computer, Software) or Computer Science
    Applied software engineering experience in unmanned aircraft mission systems and remote sensing systems
    Strong quantitative and analytic abilities to integrate and analyze data, solve problems, and effectively communicate results to engineers as well as non-technical team members and decision makers
    Experience in the development and coordination of analysis products (e.g., problem definition, analysis plan and resourcing, interim documentation, and delivery of final analysis products)
    Experience in military concept development, requirements definition and trade studies for new systems sensor and/or effector systems development
    Experience developing and/or testing computing systems for military aircraft
    Understanding of the civil or military airworthiness process for complex software/ computing systems
    Modeling and simulation experience including understanding of high-level architecture or distributed interactive simulation
    Experience supporting flight or ground vehicle testing
    Understanding of cyber security as it applies to defense systems
    Previous experience developing end to end mission solutions for DoD/government customers 

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1471113-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
