### ISSUE TITLE
Intermediate Software Systems Engineer  (#1477427)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#683]
PeopleTec is currently seeking an Intermediate Software Systems Engineer to support our Huntsville, AL location.

 

The candidate will support Accelerated Integration to Countering Emerging Threats (AICET) Program, which is a pilot program for an Integrated Fires Program for the US Army customer.  The objective of AICET is to enhance a net-centric air and missile defense architecture by developing concepts and algorithms, using state of the art Model-Based Systems Engineering (MBSE) tools and processes to perform concept definition, conduct architecture trade studies, execute models & simulations development/analysis, and deliver a viable capability enhancement to the Integrated Fires Mission Command (IFMC) Program Office.  The concept work drives the development of the process/tool infrastructure, and the concept products validate the efficiency and efficacy of the processes and tools.

 

The Intermediate Software Systems Engineer will collaborate with our joint team on assessing potential changes to the IFMC system software and aid in producing tools for data analysis and support MBSE collaboration in an integrated digital environment.

 

Education Requirements:

A Bachelor of Science Degree or higher in a science or technology discipline (e.g. engineering, physics, math, computer science)

 

Required Skills/Experience:

    Five to ten years of demonstrated experience in developing software tools and code for complex battle management command and control systems or aerospace applications
    Able to code in Java and C++
    Travel: Minimal short duration trips may be required
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Desired Skills:

    Experience in Integrated Air and Missile Defense, PAC-3, or other directly related Air and Missile Defense (AMD) program offices
    Experience working on joint engineering teams developing a software engineering process architecture and/or performing concept development of new capabilities
    Familiarity with radar systems, including AN/TPY-2, LTAMDS, PATRIOT, G/ATOR
    Familiarity with air and missile defense interceptors, including Army Patriot Interceptors, Navy Standard Missiles, Ground Based Interceptor, THAAD
    Possess an ability to plan, coordinate, and support product development in a fast-paced, rapidly changing environment
    Capable of providing  engineering/scientific support for upgrading or developing software for  systems, system elements, interfaces, components, devices, integration, and processes supporting developmental and operational weapon system engineering programs
    Familiarity with modeling & simulation development, planning, execution, and data analysis
    Familiarity with developing engineering processes
    Familiarity with Model-Based Systems Engineering processes and tools
    Excellent social, organizational, management and leadership skills
    Capability to use the Microsoft Office package to include: Outlook, Word, PowerPoint, and Excel

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

 

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1477427-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
