### ISSUE TITLE
Human Resources Assistant (#1497210)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#686]
PeopleTec is currently looking to welcome a Human Resources (HR) Representative onto our high-energy HR team to support our fast-paced corporate office in Huntsville, AL.

  

The successful candidate will act as an ambassador for our PeopleFirst culture by supporting various HR and corporate functions. Duties will include: general HR administrative support, filing and record keeping, HRIS processing and auditing as well as support of corporate/morale events, wellness, and employee recognition programs. 

 

Responsibilities:

    Maintain/Audit Human Resources Information System (HRIS) data for accuracy
    Support New Employee Orientation and prepare employee personnel files
    Answer questions related to offered benefits; process enrollment and change requests
    Facilitate Performance Review process by auditing employee/manager comments and requested salary increases; recognize and escalate performance issues
    Ensure pay equity through evaluation of various compensation data points
    Support compliant hiring and promotion practices through demonstrated understanding of labor laws
    Assist with other general HR duties and projects as needed
    Plan events for both small and large scale company programs as defined by the HR Director
    Complete data auditing and reporting (company metrics, monthly reports, etc.)
    Support and track progress and status of employee training and development
    Promote company's reputation as one of the "Best Places to Work"
    May attend career fairs and job fairs to promote PeopleTec and educate potential candidates about our culture, projects, and openings
    Successfully deliver on all deadlines and flawlessly execute tasks/projects in a fast-paced environment

 

Required Skills/Experience:

    3-5+ years of direct Human Resources experience 
    Ability to multi-task and establish priorities in a very fast-paced work environment
    Excellent organization, analytical, communication and interpersonal skills
    Positive attitude with meticulous attention to details
    Proficient computer skills and familiarity with Microsoft Office products and Sharepoint
    Must be a U.S. Citizen

 

Education Requirements:

A completed Bachelor's Degree in Human Resources, or other related field is preferred. Experience may be substituted in lieu of a degree.

 

Desired Skills:

    Previous experience within HR in the Aerospace and Defense Industry, Intelligence Community, or Space Industry
    JAMIS / Humanic experience 

 

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1497210-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
