### ISSUE TITLE
OCONUS Intermediate Engineer (#1503759)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#689]
PeopleTec is currently seeking an OCONUS Intermediate Engineer to support our Missile Defense Agency (MDA) International Engineering support operations in Tel Aviv, Israel.

 

Job Description:

Serve as the principal On-site Technical Representative (OTR) in support of the Missile Defense Agency (MDA) U.S.-Israeli Cooperative Program Office (MDA/IP) in Tel Aviv, Israel.  Duties and responsibilities include the following: conduct engineering analyses; identify and document engineering issues and recommend possible solutions; participate in program status reviews, technical interchange meetings, working groups, test planning reviews, engineering meetings,  and working groups as assigned;  collect Action Items and draft Executive Summaries and/or  minutes for these meetings; support manufacturing and production engineering activities; review technical data and documentation, and provide analysis and recommendations, and help draft technical reports/responses. Ancillary duties may include coordinating technical meetings, conference calls, Video Teleconferences (VTCs) / Classified VTCs (CVTCs), and associated documentation between MDA/IP, IMDO and Israeli industry partners.  Individual may serve temporarily as backup for all MDA/IP Annex tasks as directed by the Annex Lead (administrative, program management, or Embassy coordination duties).  A furnished apartment will be provided; and either a leased vehicle or mileage using a personal vehicle will also be authorized. 

 

Travel Requirements: 

    Primary work location is in Tel Aviv, Israel with occasional travel to various Israeli locations to include development, integration and test sites.

 

 Education Requirements:

    Education/Experience: BS degree in an engineering discipline (Electrical, Mechanical Aerospace, etc.) with 5 to 10 years of experience

 

Required Skills/Experience:

    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work (Top Secret preferred).  Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.
    Capable of working independently, or as a team member, to solve engineering and scientific problems
    Capable of providing engineering / scientific support on missile systems, for developmental and operational weapon system engineering
    Ability to plan, coordinate and support engineering activities in a fast-paced, rapidly changing environment
    A self-starter with excellent people, organizational, and communication skills
    Experience with the Adobe Acrobat, and Microsoft Office suite to include Outlook, Word, PowerPoint and Excel
    Ability to obtain, and maintain, a U.S. Passport

 

Desired Skills (any of the following are helpful):

    Experience in the design, development, testing, or production of missile defense weapon systems and/or components
    Experience with the U.S. missile defense system and associated elements
    Experience with foreign partner missile defense systems
    Experience with weapon system Interoperability
    Experience with weapon system production and delivery
    Knowledge and experience with Failure Review Board (FRB) and Root Cause and Corrective Analysis (RCCA) processes
    Knowledge of MDA policies, procedures, organization, and Boards
    Familiarity with current and possible future threats, (threat designs, functionality, performance, counter-measures) and the ability to defend against these threats
    Experience with interacting and supporting high-level Government customers
    Fluent in Hebrew
    Master's Degree in Engineering 
    Possess a current DoD Top Secret clearance

 

 EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1503759-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
