### ISSUE TITLE
Deputy Program Manager (#1504854)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#690]
PeopleTec is currently seeking a Deputy Program Manager to support our Huntsville, AL location.

 

The candidate will be responsible for managing all aspects in developing capabilities supporting our customers specific requirements. The Senior Program Manager will help to identify new growth opportunities to provide capabilities to the Missile Defense Agency, Integrated Air and Missile Defense (IAMD) Program Office, and additional customers to meet warfighter needs.

 

Required Skills/Experience:

    Capable of managing and staffing a large team of personnel in providing technical design, development, integration, test and support
    Serve as a manager resource and team member in designing, developing plans to implement systems and procedures to facilitate the delivery of program applications for new and existing product lines
    Work closely with corporate management personnel to leverage existing skill sets and capabilities as a basis for future work
    Capable of ensuring personnel resources are planned and allocated to perform all required tasks
    Extensive knowledge and experience in planning, measuring, and monitoring technical, schedule, and cost performance
    Establish and maintain excellent working relationships with existing customers
    Perform and support Group and Corporate Business Development initiatives
        Lead future business capture activities for assigned business unit
        Assist with proposal management activities
    Ability to solve complex problems and communicate effectively
        Excellent written and verbal communication skills are essential
        Exceptional organizational skills including attention to detail and multi-tasking skills 
    Strong working knowledge of MS Office tools
    Travel: ~5%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A completed Bachelor's Degree in a related field is required. Master's Degree preferred

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1504854-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
