### ISSUE TITLE
Senior Propulsion Engineer (#1509145)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#693]
PeopleTec is currently seeking a Senior Propulsion Engineer to support our Huntsville, AL location.

 

The candidate will serve as a senior engineer support contractor for the T901 Improved Turbine Engine Program (ITEP) on the Engine Development team within the Aviation Turbine Engine Project Office's ITEP Product Office.

 

Duties Include:

    Assist in identification, assessment, and monitoring of technical maturity of critical technology elements (CTEs) and NonCTE watch items in support of T901 ITE
    Provide senior level review and approval of all Technology Readiness Assessments (TRA), Technical Performance Measurements (TPM), technical reviews, and other technology-related assessments and reviews
    Provide senior level review of all ITEP technical efforts to include contractor proposals and contract data requirements list (CDRL) deliverables with emphasis on engine and engine controls test plans, procedures, and reports
    Supports the coordination, development, review, and approval of verification planning related to the development and testing of the ITE engine and engine controls system
    Provide status to IPT and program leadership 
    Support ITE contract technical, cost, and schedule requirements, and IAW ATE Technical Division best practices
    Collaborate with engine Prime Contractors' program and technical leads and other personnel to ensure the contract technical work tasks are identified, defined, scheduled, resourced, and executed
    Coordinate technical positions with Government airworthiness and test evaluation organizations to define and measure the program path to secure airworthiness qualification and safety confirmation of changed and new configurations
    Support Engine Controls tech lead to manage prime contractor performance to meet technical requirements, develop program plans and cost/budget and schedule estimates
    Spearhead the standup and management of the Government's T901 engine control dry rig and S3I Independent Verification & Validation (IV&V) effort
    Support the ITE Systems Engineering, Propulsion, Controls and Software, Integration, and T&E IPTs/WGs

 

Required Skills/Experience:

    Comprehensive experience with DoD turboshaft engine development programs
    Comprehensive experience with engine control integration
    Comprehensive experience with Systems Integration Lab (SIL), dry rig testing
    Comprehensive knowledge of gas turbine, turboshaft engine operations and engine control systems
    Ability to manage development and engineering projects, work effectively with others and manage multiple projects simultaneously
    Ability to plan, organize, and direct the work of teams or task forces conducting comprehensive trade studies, technical projects, and problem resolution
    Travel: 25%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

Master's Degree and 10 years of relevant experience or a Bachelor's Degree and 18 years of relevant experience required

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1509145-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
