### ISSUE TITLE
Senior Avionics Systems Engineer (#1514451)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#695]
PeopleTec is currently seeking a Senior Avionics Systems Engineer to support our Huntsville, AL location.

 

The candidate will provide engineering support at Systems Simulation Software and Integration (S3I) to implement a reconfigurable Avionics System Integration Laboratory (ASIL).

 

Required Skills/Experience:

    5+ years of system engineering experience in laboratory test/development environment
    Experience integrating COTS (Commercial Off the Shelf) equipment with hardware 
    Develop technical package (Schematics, drawings, bill of materials, etc.) 
    Experience developing Test Plans and Procedures
    Experience developing automated test scripts and LabVIEW 
    Experience creating software and hardware requirements, design, interface and test documentation and analysis of test results 
    Experience producing Test Reports
    Experience working with ARINC 429 and MIL-STD-1553
    Travel: 10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree and 5+ years of experience are required. 

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1514451-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
