### ISSUE TITLE
Security Specialist (#1516299)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#697]
PeopleTec is currently seeking a Security Specialist to support our Huntsville, AL location.

 

We are looking for an experienced Security Specialist to provide government, on-site support for a critical customer. The position will focus primarily on Physical Security, using security-in-depth methods as well as Operations Security knowledge in field environments. The candidate will ensure asset protection is maintained while allowing required operations to continue. Other duties include: visitor control, document control, as well as policy and procedure development.

 

Required Skills/Experience:

    Must be eligible for and obtain a Top Secret security clearance in order to access classified information and also be able to meet additional security eligibility requirements
    Experience in Information Security, Physical Security, Operations Security, Communications Security, and Personnel Security
    Posses a strong sense of responsibility, solid work ethic, mature judgment, and discretion in handling sensitive information
    Able to effectively communicate with all levels of military, government, and industry partners
    Proficient in Microsoft Office applications (Word, Excel, and PowerPoint at a minimum)
    Knowledgeable of DoDM 5205.07, DoDM 5200.01, AR 380-5, AR 380-381, as well as general security procedures and policies
    Travel: Up to 30%; OCONUS travel may be required
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

6+ years of security experience

 

Desired Skills:

    Bachelor's Degree
    Knowledge of security surveys, inspections, and assessments 

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1516299-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
