### ISSUE TITLE
Database & Operations Analyst Manager (#1519687)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#698]
PeopleTec is currently seeking a Database & Operations Analyst Manager to support our Huntsville, AL location.

The candidate will utilize existing database management tools to optimize space planning database and maximize the effects of capabilities in support of real-world COCOM operations.The contractor will utilize aforementioned tools, functions and respective processes to maintain the accuracy and currency within analytical database to enable effective evaluation. The candidate will also support USASMDC, Army, USSPACECOM & USSTRATCOM in Joint Space Mission planning and capability development with the following functions:

    New Satellite, Transponder and Signal Modeling Ground Station Modeling
    Telemetry, Tracking and Control (TT&C) Modeling
    Data downlink Modeling
    Real-time Downlink Modeling
    Engineering and Capability Development

The contractor shall acquire information and data associated with each respective function and analysis. Utilizing a space planning database, Microsoft Access & Excel and other tools, the contractor will process all data this includes:

    Target Identification, Organization & Prioritization Research
    Deconfliction
    Quality Control
    Shortfall Identification
    Request for Intelligence (RFI) Compilation & Submission
    Missing Space Systems & Components Modeling
    Missing Data Deduction & Calculations
    Correcting and Repairing Corrupt Files
    Acquisition and Transfer of Orbital Positioning Element Sets (ELSETs)
    Unit of Measure Conversion
    Data Entry 
    Testing and evaluation

 

Required Skills/Experience:

    5+ years of  military experience or experience in military operations, daily operational support, planning, coordination, facility, personnel, training and technical analyses
    Microsoft Access and Excel experience
    Travel: 10%
    Must be a U.S. Citizen
    An active DoD Top Secret clearance with SCI eligibility is required to perform this work. Candidates are required to have an active Top Secret clearance with SCI eligibility upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

Bachelor's Degree and 5 years of experience is preferred. 5 additional years of experience can be substituted in lieu of a degree.

 

Desired Skills:

    Familiarity of Joint Ops, BDE/Staff MDMP, Space & Cyber Intel
    Understanding of DOD inter-agency coordination mechanisms

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1519687-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
