### ISSUE TITLE
AI Software Developer Position! Immediate Need

### ISSUE THREAD

**Issue by spearna** [tech256/jobs#70]
# AI Software Developer Position! 

### About Position
[BGI-1743: Software Developer (Huntsville, AL)](http://www.decibelresearch.com/careers/openings.html)  
deciBel Research is seeking a Software Developer that will contribute to the development of an artificial intelligence knowledge based machine learning project, as well as productize and optimize other prototype algorithms. The project is a research-based initiative taking concepts through development to test and ultimately fielded into an integrated system. Will be a highly productive member of the team responsible for contributing to the software baseline on a daily basis.

### Experience & Familiarity
- ≥ 5 years of related experience
- Languages: CPP, FORTRAN, and C.
- Experience with artificial intelligence and machine learning
- Git/Git Lab or other version control software
- Agile development practices such as Scrum and continuous integration

### Contact
- Email: nspear@dbresearch.net
- Location: Huntsville, AL

---

**Comment by blmeadows** [comment]
@spearna is this still relevant?
