### ISSUE TITLE
Pricing Analyst (#1521670)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#700]
PeopleTec is currently seeking a Pricing Analyst to support our Huntsville, AL location.

 

Responsibilities Include:

    Conduct in depth analysis of proposals to evaluate fair and reasonableness using Cost & Price analysis quantitative techniques per the FAR and DFAR
    Establish reasonableness of cost and pricing
    Participate in cost and pricing reviews with management, customer and supplier representatives
    Generate price and cost analysis reports providing recommended price positions to support negotiations with customer and suppliers
    Identify risks and opportunities to the cost estimate
    Conduct supplier statistical price analysis and audits of subcontractor cost proposals to review basis of estimates and source documentation verifying proposal cost estimates for single/sole sourced procurements, as per FAR parts 15 and 31
    Ability to calculate direct, indirect cost rates
    Prepare recommendations on negotiation objectives concerning cost, profit, and price
    Prioritize work on a variety of proposals at the same time
    Partner with the proposal managers and proposal teams to respond to customers RFPs
    Review RFPs and derive material, labor and other requirements
    Support Supply Chain Management (SCM) development of RFP/RFQs
    Work with SCM, vendors and subcontractors to develop a consolidated bill of material
    Prepare estimates and develop cost volumes in accordance with FAR for submission in response to RFPs and other estimates on cost-type and fixed price efforts
    Gather and organize historical data for same or similar programs in support of proposals
    Participate in the customer and supplier negotiation processes including customer, DCMA and DCAA fact-finding and audits

 

Required Skills/Experience:

    5+ years of experience in a related field
    Proficiency in MS Office including Excel, Work, PowerPoint
    Working Knowledge of FAR, DFAR, TINA and other Government procurement regulations as they pertain to bid/costing proposals
    Experience in bidding to different contract types (FFP, CPFF, T&M)
    Strong analytical skills and demonstrated ability to meet goals and deadlines accurately and on time in a fast paced environment
    Ability to work productively under minimal supervision and follow instructions (oral and written)
    Ideal candidate must be able to work cooperatively with others and maintain effective work relationships with all those contacted in the course of performing required duties
    Ability to maintain confidentiality and proprietary information
    Other duties as assigned by the company CFO and management
    Travel: None
    Must be a U.S. Citizen

 

Education Requirements:

A completed Bachelor's Degree in a related field from an accredited university is required.

 

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1521670-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
