### ISSUE TITLE
Senior Weapon Systems Analyst/Aerospace Engineer

### ISSUE THREAD

**Issue by BDHowe** [tech256/jobs#704]
# Senior Weapon Systems Analyst / Aerospace Engineer

### Description

The candidate will work with a team of Government and Industry engineers to perform weapon system analysis, concept development, feasibility studies, and trade studies to aid the Army with critical technology development and technology roadmap development.

### Duties
- The candidate will conduct weapon system trade studies to identify optimal system configurations and key technology drivers.
- The candidate will participate in the analysis of all aspects of missile systems including concepts of employment, threat system identification and analysis, surveillance and fire control sensors, missile sensor systems, target tracking, and extrapolation algorithms, aerodynamics, propulsion, controls, and data links.
- The candidate will participate in the development of weapon system performance requirements analysis and development.
- The candidate will participate in the development, maintenance, and use of models and simulations of required fidelity (engineering level, 3DOF, 6DOF, etc.) to derive system requirements and assess system performance.
- The candidate will aid the Government Engineering team in assessing system performance, scenario development, and analysis.
- The candidate must be able to work within a fast-paced environment, often with evolving requirements.
- The candidate will write and present technical documentation as required.

### Education Requirements
- BS or MS degree in Electrical Engineering, Aerospace Engineering, Mechanical Engineering or other relevant science field.

### Qualifications
- 15+ years of relevant experience.
- Good communication skills and the ability to present analysis findings.
- Demonstrated experience in DoD weapon systems analysis/engineering activities.
- Experience in systems engineering to include requirements derivation and management.
- Experience in modeling and simulation of complex weapon systems.
- Candidate must be able to obtain a security clearance.

## [Indeed Listing](https://www.indeed.com/jobs?q=weapon%20analyst&l=huntsville%20alabama&vjk=9a95787aef5d8487)

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
