### ISSUE TITLE
Deputy Program Manager/Business Development Liaison (#1528553)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#706]
PeopleTec is currently seeking a Deputy Program Manager/Business Development Liaison to support our Huntsville, AL location.

 

The candidate will assist with management activities across five different technical activities currently on contract and in development. The Deputy Program Manager/Business Development Liaison will help to identify new growth opportunities to provide capabilities to the Missile Defense Agency, Integrated Air and Missile Defense (IAMD) Program Office, and additional customers to meet warfighter needs. This work also includes coordinating with the corporate business development to identify, create, and capture areas of opportunities, and develop PeopleTec' s positions.

 

Program Management Duties Include:

    Knowledge and experience in planning, measuring, and monitoring technical, schedule, and cost performance
    Ability to solve complex problems using a Business Case Analysis approach
    Experience with supervising personnel and writing performance evaluations
    Capable of developing requisitions for personnel needed in existing or new developmental areas
    Experience with interviewing candidates and making selection recommendations
    Perform and support Group and Corporate Business Development initiatives

 

Business Development Duties Include:

    Develop group business development strategy & capture objectives
    Support development of group growth plans to ensure alignment with strategic goals
    Manage group business pipeline data by reviewing & updating entries in PeopleTec's CRM tool
    Develop internal cross-organizational relationships within PeopleTec
    Develop and execute pursuit and capture strategies and plans to win new or follow-on business, including, but not limited to identifying, assessing and shaping business opportunities, creating and managing contact plans, and messaging to potential customers and stakeholders
    Conduct competitive analysis
    Identify potential industry teammates
    Provide group Strategic Plan inputs for assigned defense market segments and customers
    Represent assigned group in meetings, conferences and workshops

 

Required Skills/Experience:

    Management experience within a DOD program
    Considerable initiative/preference for conducting business development activities
    Organizational skills
    Ability to drive convergence and resolution to challenges
    Possess strong written and verbal communication skills
    Travel: Local travel may be required
    Must be a U.S. Citizen
    The ability to obtain and maintain a Secret Clearance upon hire is required for this role

 

Education Requirements:

A completed Bachelor's Degree in a technical or business related field and 8 years of relevant experience in Business Development in the Defense market, or an equivalent combination of education and experience required

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1528553-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
