### ISSUE TITLE
Sr. Control System Cyber Architect (#1535755)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#708]
PeopleTec is currently seeking a Sr. Control System Cyber Architect to support our Huntsville, AL location.

 

The candidate will provide valuable feedback and constructive communication with the Customer to assist in the development of the organization's Concept of Operations (CONOPs). 

 

Duties Include:

    Support the effort to standardize OT architectures which meet the organization's or site's cybersecurity, resiliency, and monitoring requirements while maintaining operational capability of the control system
    Conduct full hardware and software analysis of control systems either currently used by or being reviewed by the Customer for implementation; task could involve decomposition of hardware to detect supply chain tampering, penetration testing of the firmware/application, and other in-depth security checks
    Based on the security assessment of hardware and software, provide executive and technical reports and summaries to the Customer which details the recommended technical and operational solutions to implement to mitigate or to remove risk
    Develop methodologies, threat assessments, and mitigations for various control systems which describe how these systems would be securely engineered and architected without adverse impact to the operational and functionality capability of the system
    Determine ways to integrate secure control system architectures into existing networks
    Assist in the design and development of cyber security architectural artifacts and templates
    Manage the monitoring and tracking of the Customer's ICS Security Command Plan implementation and report the status to senior leadership staff
    Deliver incident mitigation strategies to leadership and support cyber-related incident management activities
    May perform onsite installation, configuration, and implementation of control system architectures

 

Required Skills/Experience:

    Minimum of 10 years of work-related experience in IT/OT environments
    Previous control systems experience
    Knowledge of UFC 04-010-06, 25 05 11, NIST SP 800-82, FRCS Overlay, and other applicable control system policies/procedures/TTPs 
    Must possess one of the following: CISSP, CISM, CASP, CISA, CCISO, GCIH
    Travel: Up to 10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

BS Degree in related field and 10+ years experience or 16+ years of experience in lieu of degree

 

Desired Skills:

    Master's Degree in related field or equivalent
    Hands-on engineering or architecting of control systems
    Ability to lead a team
    GPEN, GICSP, GRID Any ICS vendor certifications

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1535755-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
