### ISSUE TITLE
Control System Cyber Analyst (#1535770)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#709]
PeopleTec is currently seeking a Control System Cyber Analyst to support our Huntsville, AL location.

 

The candidate will assist the Senior Control System Architect and other staff members to meet the Customer's mission objectives.

 

Duties Include:

    Support the effort to standardize OT architectures which meet the organization's or site's cybersecurity, resiliency, and monitoring requirements while maintaining operational capability of the control system
    Conduct full hardware and software analysis of control systems either currently used by or being reviewed by the Customer for implementation; task could involve decomposition of hardware to detect supply chain tampering, penetration testing of the firmware/application, and other in-depth security checks
    Develop methodologies, threat assessments, and mitigations for various control systems which describe how these systems would be securely engineered and architected without adverse impact to the operational and functionality capability of the system
    Determine ways to integrate secure control system architectures into existing networks
    Contribute to the design and development of cyber security architectural artifacts and templates
    May perform onsite installation, configuration, and implementation of control system architectures

 

Required Skills/Experience:

    Minimum of 6 years of work-related experience in IT/OT environments
    Previous control systems experience 
    Must possess one of the following: Security+ CE, C|EH, CASP, or other IAT II certification
    Travel: Up to 10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

Bachelor's Degree in related field and 6 years experience or equivalent experience (12 years) along with hands-on engineering or architecting of control systems GICSP, GRID and any ICS vendor certifications

 

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1535770-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
