### ISSUE TITLE
Hire me: Security pen tester/network admin 

### ISSUE THREAD

**Issue by gregtampa** [tech256/jobs#71]
My resume link below

https://docs.google.com/document/d/1C_94oaZXujKh0tw0WrxwNRHKyUXK6FsCCYhQp_b8C-0/edit?usp=sharing

**Comment by blmeadows** [comment]
@gregtampa is this still relevant?

**Comment by gregtampa** [comment]
Yes but better link now is

Http://www.gregtampa.com/resume.pdf
