### ISSUE TITLE
Proposal Coordinator (#1538782)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#710]
PeopleTec is currently seeking a Proposal Coordinator to support our Huntsville, AL location.

Our fast-paced Business Development Team is looking for a Proposal Coordinator with experience in the development of compliant and compelling federal proposals. The successful applicant will be a proactive "go-getter" and must be able to work well as part of a team. The candidate will work coordinating efforts across several projects simultaneously, requiring self-organization and time management skills.

 Job Duties:

    Organize and participate in team meetings
    Maintain and coordinate schedules
    Schedule resources and facilities
    Format proposal materials and edit documents for grammar and content
    Request, collect, and organize information such as data calls and writing assignments
    Maintain files and resource libraries in SharePoint
    Develop proposal compliance matrices
    Prepare PowerPoint briefings for proposal meetings
    Prepare internal and external correspondence, complete timely/accurate data entry, and compile/analyze reports
    Research, collect, and store business development data and information
    Search for relevant data and verify accuracy to give the Business Development team greater insight into opportunities.
    Research and document key customer organization structure, POCs, and program specific decision makers
    Data entry and validation within our Customer Relationship Management tool
    Assist in administrative duties for the Proposal Managers and Proposal Operations
    Assist in conference and industry event coordination, scheduling, and planning
    Limited weekend and after-hours work may be required

 

  Required Skills/Experience:

    HIGHLY PROFICIENT in planning, time management, and organizational skills
    HIGHLY PROFICIENT in Microsoft Office Software to include Word, Excel, and Power Point
    Work efficiently and effectively with flexibility under tight deadlines in a team environment
    Experience in the proposal development process 
    Exceptionally meticulous attention to detail
    Excellent written and oral communication skills; proofreading and editing skills preferred
    Experience coordinating and liaising with several parties on a single project
    Ability to work in a fast-paced environment
    Knowledge of commonly used concepts, practices, and procedures within the Government contracting industry preferred
    Enthusiastic, self-motivated, and team-oriented
    Work well with professionals from various backgrounds
    Must be a U.S. Citizen

 Education Requirements:

    Bachelor's degree in Business, English, Marketing, Communications, or a related field
    2-3 years of relevant work experience working in a government contracting industry is highly preferred

Desired Skills:

    Familiarity with or training in Shipley proposal development methods
    Excellent writing, editing, proofreading and formatting skills
    APMP certification would be viewed favorable

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1538782-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
