### ISSUE TITLE
Help Desk Support/SharePoint Specialist (#1543985)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#714]
PeopleTec is currently seeking a Help Desk Support/SharePoint Specialist to support our Huntsville, AL location.

This role will act as Help Desk Support while also maintaining the ability to perform SharePoint tasks as assigned.

SharePoint duties include but are not limited to: Site creation, archiving, site administration, Office 365 Groups, OneDrive SharePoint membership & permissions, monitoring event and usage logs, content management, and page configuration within SharePoint will be required. Interaction with content managers and end users to included but not limited to Content management training, requirements gathering for design-based application, first line of support, and general evangelism for SharePoint.

This role will also require monitoring & validating SharePoint and Office 365 backups for security and disaster recovery situations. This role would also require administration and troubleshooting of on premise & remote desktops, laptops, and mobile devices.

Required Skills/Experience:

    2+ years of relevant work experience including "hands-on" IT support
    Knowledge of Office 365, Windows 10, and Azure Active Directory will be necessary to perform troubleshooting tasks and issue resolution
    Experience with Microsoft 365 suite, including Teams, SharePoint, OneDrive, and Office 365
    Experience with Azure Active Directory and Microsoft Admin Center
    Knowledge of SharePoint Online and Office 365 Groups management
    Experience using backup services such as Veeam or AvePoint, to validate & test SharePoint & on Prem backups
    Must be a U.S. Citizen

Education Requirements:

    A Bachelor's degree in a related field is preferred. Years of experience may be substituted in lieu of a degree

Physical Job Requirements:

    Ability to lift up to 20 pounds with or without reasonable accommodation

Desired Skills:

    Self-starter with a positive attitude
    High level of professionalism with the ability to maintain sensitive and confidential information
    Customer orientation and ability to adapt/respond to different types of characters
    Reviewing Security Hierarchy
    Validating site backups 
    Auditing server utilization
    Knowledge of mobile device administration (iOS & Android)
    Knowledge of AV systems for livestream & teleconferencing systems
    NIST Special Publication 800-171 or NIST Special Publication 800-53
    Office 365 GCC High Experience
    Customer Service

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1543985-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
