### ISSUE TITLE
Senior Model Based Systems Engineer (#1555007)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#718]
PeopleTec is currently seeking a Senior Model Based Systems Engineer to support our Huntsville, AL location.

 

Our team is looking for an exceptionally motivated self-starting candidate with  a deep background in Model Based Systems Engineering (MBSE). The candidate will provide hands-on technical leadership to our growing team of cyber, space, and engineering professionals who design, implement, test, and deploy cyber effects in a lab environment and develop a syndicated system integration lab. Candidate needs to have a strong background in modular systems and open architectures (MOSA).

 

Duties Include:

    Staff expert on Future Vertical Lift (FVL)/aviation projects' development lifecycle, including pursuit and order capture, system design, requirements definition, requirement allocation, requirement traceability, use case development for software/hardware, systems integration, verification testing and qualification
    Development of system and data models in order to design, develop, document and test both hardware and software systems, ranging from black box to the complex end-to-end platform systems for FVL and other aviation platforms
    Facilitate MBSE training with other team members, cultivating and reinforcing appropriate MBSE best practices, processes, and behaviors, while identifying, analyzing, and correcting problems
    Develop and implement system models to support development and integration of new and future aviation systems, this includes modeling system and subsystems with the intent to create a verifiable model
    Utilize MOSA principles, streamline integration and persistent test capabilities for FVL and other Army Aviation stakeholders to provide common architectures for PMs to leverage in achieving the Army's intent of a modular modernized force
    Assess architectures & designs early in the lifecycle to identify MOSA issues
    Assess feasibility and utility of delivery and storage of digital twins of aviation systems' models

 

Required Skills/Experience:

    5+ years of experience in working with MOSA principles
    10+ years of experience in MBSE, system requirements, acquisition
    In-depth understanding of MBSE & MOSA principles
    Technical and project leadership experience
    Excellent written and verbal communication skills 
    Travel: 10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree in Engineering and 10+ years of experience are required.

 

Desired Skills:

    Master's Degree in Engineering
    Experience developing aviation designs/models for OEMs
    PEO Aviation experience

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1555007-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
