### ISSUE TITLE
Trusted Microelectronics Subject Matter Expert (#1555020)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#719]
PeopleTec is currently seeking a Trusted Microelectronics Subject Matter Expert to support our Huntsville, AL location.

 

Our team is looking for an exceptionally motivated self-starting candidate with a deep background in trusted microelectronics, failure analysis, and counterfeit detection. The candidate will provide hands-on technical leadership to our growing team of cyber, space, and engineering professionals who design, implement, test, and deploy cyber effects in a lab environment and develop a syndicated system integration lab.

 

Duties Include:

    Lead the design and construction of a state-of-the-art trusted microelectronics laboratory for critical hardware/integrated circuit analysis
    Prepare Mean-Time-Between-Failure and Mean-Time-To-Repair analyses
    Assess engineering plans, hardware design specifications, Technical Design Packages, and other documentation that provides context to hardware componentry to prepare for microelectronics assessments
    Work closely with system engineering and test engineering to develop & incorporate developmental test tools and artificial intelligence/machine learning (AI/ML) to complement trusted microelectronics assessment methodology
    Assess & validate hardware portion of test plans, test procedures, throughput models, failure analysis, and risk analysis
    Work closely with quality control to understand quality requirements and improve reliability, availability, and maintainability of systems

 

Required Skills/Experience:

    5+ years of experience in hardware assessments & failure analysis
    In-depth understanding of the counterfeit microelectronics problem
    Experience with aviation systems
    Excellent written and verbal communication skills
    Technical and project leadership experience
    Travel: 10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

Bachelor's Degree in Engineering and 5 years of experience are required.

 

Desired Skills:

    Master's Degree and 10+ years of experience
    Counterfeit detection experience
    Knowledge & involvement with Defense Microelectronics Activity (DMEA), Naval Surface Warfare Center, Crane Division, Joint Federated Assurance Center, CCDC AvMC, and/or quality assurance organizations
    Aviation OEM experience

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1555020-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
