### ISSUE TITLE
Aviation Developmental Test Engineer (#1555142)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#720]
PeopleTec is currently seeking an Aviation Developmental Test Engineer to support our Huntsville, AL location.

 

Our team is looking for an exceptionally motivated candidate with a deep background in developmental test (DT), DT tools, and aviation systems. The candidate will provide hands-on technical leadership to our growing team of cyber, space, and engineering professionals who design, implement, test, and deploy cyber effects in a lab environment and develop a syndicated system integration lab. Candidate needs to have familiarity with modular systems and open architectures. 

 

Duties Include:

    Support planning, development, and execution of T&E development and operational test events for aviation systems
    Participate in technical working groups and discussions with respect to aviation programs' development efforts to remain cognizant of all system engineering and program aspects including program priorities, design, cost, and schedule
    Support the development of the Test Strategy and/or Test and Evaluation Master Plan (TEMP) and participate in the T&E Working Integrated Product Team (IPT)
    Support the development of test and evaluation input into Milestone documentation such as the Systems Engineering Plan (SEP), Program Protection Plan (PPP), Systems Specification, Performance Work Statement (PWS and/or Statement of Work (SoW), and Source Selection Plan (SSP)
    Support test planning with the OEM and the Government Test Agencies to include the Army test community and its subordinates for developmental and operational test events
    Conduct developmental test tool survey and study of future test tool development to fill gaps
    Develop a tool development plan spanning all phases of test with an emphasis on integration of AI/ML to existing and new DT tools Employ Agile in all software development
    Utilize modular open system architecture (MOSA) principles, streamline integration and persistent test capabilities for Future Vertical Lift (FVL) and other Army Aviation stakeholders to provide common architectures for PMs to leverage in achieving the Army's intent of a modular modernized force
    Assess architectures & designs early in the lifecycle to identify MOSA issues
    Assess feasibility and utility of delivery and storage of digital twins of aviation systems' models

 

Required Skills/Experience:

    Developmental test experience
    Developmental test tool experience
    Familiarity with the Army Test & Evaluation community
    Travel: 10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

BS in Engineering and 10+ years of experience are required.

 

Desired Skills:

    MS In Engineering
    PEO Aviation experience
    OEM aviation experience
    Software development for DT experience
    Strong background in MBSE & MOSA
    Exposure to CCDC AvMC SILs

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1555142-42491

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
