### ISSUE TITLE
Operations Manager (#1566810*)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#726]
PeopleTec is currently seeking an Operations Manager to support our Huntsville, AL location.

 

This position supports U.S. Government Product Office with planning, integrating, and coordinating among the various departments within the Product Office, as well as other agencies, such as Project Office, Program Executive Offices, Department of the Army, Army Commands, and other Defense Contractors. The candidate will support operational planning scheduling, technical analysis and evaluations, report preparation, briefings, and implementation of plans along with providing support to operations management.  The Operations Manager will assist operational planning coordination and execution of events, meetings, inter-governmental affairs throughout the product office as well as support daily interface with military and civilian personnel and other contractor personnel in a team environment.

 

Duties Include:

    Planning, scheduling, technical analysis, evaluation of products, reports, and materials, conducting briefings, highlighting value engineering opportunities, and implementing plans in support of Management's vision
    Daily interface with programmatic, business, technical, logistic, civilian and military personnel, and frequent contact with defense suppliers in support of multiple aviation product fielding, New Equipment Training (NET), scheduling, employment, and resolution of issues
    Support product office leadership by overseeing internal operations establishing policies and procedures to assist management in the day to day tasks
    Work with office leads to synchronize and coordinate all actions
    Analyzing, issuing, tracking, consolidating, and closing Taskings
    Develop, review, staff, and present briefings and papers
    Participate in appropriate meetings on behalf of product office
    Coordinate meetings within the product office, and other organizations
    Update administrative documents for the product office (personnel lists, organization charts, etc.)
    Assist with daily office business (travel, IT issues, scheduling, personnel issues, etc.)
    Assist with daily and weekly reports to higher headquarters (staff call brief, significant activities, executive summaries, critical information requirements, etc.)
    Manage recurring office meetings, agendas, tasking requirements, product development, and administrative documents, assist in ceremonies and program office events

 

Required Skills/ Experience:

    10 years' related experience with aviation operations, and staff organizations
    Experience developing and recommending policy, organizing and carrying out specific programs, evaluating and recommending changes in methods of operations
    Knowledge of DoD and Army regulations, acquisition policies and procedures, program goals and objectives, and work processes of the organizations supported, as well as relationships with other programs within Department of the Army
    Experience in supervising staff or technical work which included study, analysis or evaluation leading to the development or improvement of managerial or administrative policies, practices and procedures
    Experience preparing written communications and oral presentations
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

Education Requirements:

Bachelor's Degree is required.

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1566810-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
