### ISSUE TITLE
Software Quality Test Engineer--Hiring Bonus!

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#73]
Software Quality Test Engineer--Hiring Bonus! 

 

Company Overview: 

Cepeda Systems and Software Analysis, Inc. (CSSA) provides software engineering, systems engineering, and process improvement services for our customers.  CSSA has achieved a rating of Capability Maturity Model Integration (CMMI) Level 2 for Services and CMMI Level 3 for Development. We have a 100% customer satisfaction rating and have won numerous awards at the local and national level. We treat one another with respect, foster collaboration while maintaining individual accountability, value multiple perspectives and diverse expertise, and encourage new ideas that surface throughout the organization. CSSA offers a comprehensive and competitive benefits package. 

 

Key Responsibilities: 

    Provide quality assurance support for DoD medical planning modeling and simulation software 
    Review and revise quality procedures, standards, and specifications 
    Ensure compliance with existing quality management system 
    Assist in maintaining CMMI Maturity Level 3 competency 
    Support internal and external quality and CMMI audits 
    Test and evaluate modeling and simulation software 
    Review software requirements 
    Prepare and review test cases and test procedures 
    Conduct software test and data analysis 
    Evaluate test results 
    Generate test reports 

 

Qualifications: 

Education Requirements 

B.S. in Computer Science, Computer Engineering, Software Engineering, or related area from an accredited college or University 

 

Experience: 

Minimum 5 years relevant experience in: 

    Conducting software testing at the unit, integration, and system levels 
    Performing comprehensive analysis, design, and test 
    Developing test plans, test procedures, and test reports 
    Experience testing Windows-based, stand-alone applications and web-based applications preferred 
    Experience with Microsoft Visual Studio/Team Foundation Server (TFS) and Gurock TestRail preferred 
    Experience with Software process improvement preferred 
    Experience with software quality assurance, in particular performing audits preferred 

 

Knowledge/Skills: 

    Candidate should be a fast learner to quickly ascertain expected software functionality and develop an appropriate comprehensive testing approach 
    Excellent troubleshooting and critical thinking skills 
    Ability to analyze configurations and system behaviors via output data and/or software source code review 
    Strong verbal and written communication skills with the ability to clearly describe issues to both the software development team and technical leadership  
    Ability to multi-task in a fast-paced testing environment 
    Ability to work collaboratively with internal and external stakeholders 
    Ability to complete tasks on time and in compliance with AS9100 and CMMI level processes and procedures 
    Software Life Cycle Development experience is preferred 
    AS9100/ISO9001/CMMI Level 3 knowledge is preferred 

 

Licenses/Certifications: 

    CMMI Associate Certification is preferred 

 

U.S. Citizenship is required 

Must be able to obtain or have a Secret Security Clearance 

Hiring Bonus!

CSSA is an Equal Employment Opportunity Employer. We do not discriminate in the employment of individuals on the basis of race, color, sex (or pregnancy), religion, age, national origin, disability, veteran status, sexual orientation, gender identity, genetic information, or any other protected category. CSSA hires and promotes individuals solely on the basis of their qualifications for the job to be filled. If you require assistance with the application process, please contact us at careers@cepedasystems.com. We appreciate your interest in our organization. 

  

CSSA participates in the E-Verify program. 

Criminal background checks are conducted on all applicants before hire.  

CSSA is a Drug Free Workplace.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/610384-194689

**Comment by blmeadows** [comment]
@CSSA-HR is this still relevant?
