### ISSUE TITLE
Army Aviation Maintenance Manager SME (#1570609)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#731]
PeopleTec is currently seeking an Army Aviation Maintenance Manager SME to support our Huntsville, AL location.

 

Duties Include:

    Army Aviation maintenance management subject matter expert on Aviation Ground Support Equipment (AGSE)
    Serve as an SME representing Product Director Aviation Ground Support Equipment (Pd AGSE) on site visits, AGSE sustainment programs, Modification Work Order (MWO) development and implementation, Technical Bulletin (TB) development and implementation, Technical Manual updates and development, Aviation Safety Message development
    Engagements with Sustainment Commands, senior commanders and staff of Combat Aviation Brigades (CABs) and Army Aviation Support Facilities (AASFs) as well as other aviation activities including Original Equipment Manufacturers (OEMs).  
    Interact with HQDA, the CG Army Materiel Command (AMC), Army Forces Command (FORSCOM), and other Army Commands (ACOMs), Army Service Component Commands (ASCCs), Direct Reporting Units (DRUs), and ARNG/USAR aviation activities
    Create written Integrated Product Support (IPS) products, daily reports, and presentations for Product Managers, Directors, and their staffs. 
    Represent AGSE at cross-PM coordination meetings and activities to integrate AGSE products into UH-60, AH-64, CH-47, UH-72, MQ-1, RQ-7, and Army fixed wing fleet and maintenance management
    Interfaces between customers and engineers to mitigate problems, enhance the product, and add critical features that users demand
    Detect problem areas and quickly develop plans and make coordination to address those problems before they affect program success
    Perform other general technical and logistics tasks as necessary    

 

Required Skills/Experience:

    Work outside normal duty hours is often required.
    Travel:25-50% (Travel OCONUS and to operational theaters necessary)
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

BS and 6+ years of experience OR a HS Diploma and 14+ years of experience

 

Physical Job Requirements:

Must be able to travel

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1570609-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
