### ISSUE TITLE
Senior Software Engineer (#1573724*)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#735]
PeopleTec is currently seeking a Senior Software Engineer to support our Northern Virginia operations.

 

The Senior Software Engineer will serve as the technical lead for all software development efforts. The Senior Software Engineer will authoritatively and effectively provide guidance in the overall aspects of the software development process to include data architectures, software assurance, and security.

 

Duties Include:

    Conduct rapid software prototyping to demonstrate and evaluate technologies in relevant environments
    Conduct performance, security, and other aspects of evaluating software systems
    Test software capabilities using novel testing and analysis techniques
    Document software with an emphasis on architectures, user stories, and interface definitions
    Practice agile software development methods
    Support software development infrastructure and assist in building and configuring computing systems and resources
    Interface with the technical community and other Government entities to understand challenges, needs, and development solutions
    Contribute to improving the overall technical capabilities of the customer's Computer Network Operations (CNO) mission by participating in design (software and otherwise) sessions, developing unique capabilities, and sharing insights and practices across Government organizations supporting the CNO mission

 

Required Skills/Experience:

    10+ years overall recent experience in the direct performance of a major program, project, or activity relating to computer software development at the user and kernel level, computer programming, and/or computer digital forensics
    Working knowledge and experience in participating in agile software development practices and team design sessions
    Experience working on a software development team
    Experience with cross-platform UI development such as Qt
    Experience with cross-domain networking solutions
    Demonstrated problem-solving ability with the ability to explore and evaluate many possible solutions to problems
    Must be able to achieve and maintain a TS/SCI with CI Poly
    Travel: 15%
    Must be a U.S. Citizen
    An active DoD Top Secret clearance with SCI eligibility is required to perform this work. Candidates are required to have an active Top Secret clearance with SCI eligibility upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

Bachelor's Degree in one of the following areas: Computer Science, Computer Engineering, or Software Engineering from an accredited university/college is required. The Government may consider candidates without the requisite bachelor's degree if they possess a minimum of ten (10) years of relevant experience in relevant areas, or related fields, have demonstrated development proficiency and/or advanced knowledge of computer programming and development systems and security practices. 

 

Physical Job Requirements:

Must be able to lift 25 lbs of computer equipment

 

Desired Skills:

    TS/SCI w/ CI Poly
    5+ years of intensive software development experience in modern languages such as C/C++ or Java
    Knowledge of commonly used languages such as Perl, Python, Ruby, and JavaScript
    Working knowledge of some modern computing paradigms and environments such as: NoSQL systems, cloud computing and virtualization, parallel programming, network programming, mobile development, and interface development
    Experience applying Artificial Intelligence and Machine Learning techniques to optimize operational software
    Familiar with end-to-end software development activities in Linux/Windows/Unix/Web environments, software development tools including IDEs (Eclipse, IntelliJ, and Emacs), version control systems (Git, and Svn) and bug tracking systems (e.g. Jira, Bugzilla, Fogbugz)

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1573724-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
