### ISSUE TITLE
IAMD Threat Analyst (#1574154)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#737]
PeopleTec is currently seeking a IAMD Threat Analyst to support our Huntsville, AL location.

 

The candidate will support Advanced Integration for Countering Emerging Threats (AICET) Program, which is a pilot program for the Integrated Air and Missile Defense (IAMD) Program.  The objective of AICET is to enhance a net-centric air and missile defense architecture by developing and using state of the art Model-Based Systems Engineering (MBSE) tools and processes to perform concept definition, conduct architecture studies, execute models & simulation development/analysis, and deliver a viable capability enhancement to the IAMD Program Office.  The concept work drives the development of the process/tool infrastructure, and the concept products validate the efficiency and efficacy of the processes and tools.

 

The candidate will lead planning, developing, and executing simulations for current and new IAMD threats and scenarios, and concepts based on either MBSE functional and performance characteristics or behaviors identified by IAMD subject matter experts.  These simulations are intended to assess key performance and functional characteristics for the candidate concept trade studies.  Candidate will also lead developing the data analysis processes, aid in conducting the data reviews, and define/develop visualizations to aid in interpreting results.

 

Required Skills/Experience:

    10-15+ years of demonstrated experience in developing, validating, and executing models & simulations (M&S) for aerospace applications
    Experience with IAMD
    Experience analyzing Airborne Threats (ABT), TBM threats and/or threat files, threat databases with knowledge of typical threats and associated parameters
    Familiarity with modeling & simulation development, planning, execution, and data analysis
    Good presentation skills to present results of analyses and recommendations to team leaders
    Familiarity with Python
    Travel: Local travel only; No out of town travel is planned or likely
    US Citizenship required
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor of Science Degree or higher in a science or technology discipline (e.g., engineering, physics, math, or computer science) and 10+ years of experience required

 

Preferred Skills/Experience:

    Ability to review threat description documents to discern relevant M&S information about new and evolving threats
    Ability to perform Threat Selection Analysis to identify which threats, trajectories and files should be used for trade studies based upon relevance, engagability and other metrics
    Ability to rapidly process incoming scenario packages and threat data packages.  Ability to compare existing databases to new ones, and determine what's new using scripts
    Ability to develop tools to process packages for completeness and file integrity
    Ability to work with multiple simulation and trade study teams simultaneously
    Familiarity with Integrated Air and Missile Defense threats
    Familiarity with radar systems, including AN/TPY-2, LTAMDS, PATRIOT, G/ATOR
    Possess an ability to plan, coordinate, and support product development in a fast-paced, rapidly changing environment
    Excellent social, organizational, management and leadership skills
    Capable of working as a team member to solve engineering/scientific problems
    Ability to use Microsoft Office package to include: Outlook, Word, PowerPoint, and Excel

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1574154-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
