### ISSUE TITLE
GCSS-A Software Developer - Java_C#

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#74]
GCSS-A Software Developer - Java/C#

Cepeda Systems and Software Analysis, Inc. (CSSA) provides software engineering, systems engineering, and process improvement services for our customers. CSSA has achieved a rating of Capability Maturity Model Integration (CMMI) Level 2 for Services and CMMI Level 3 for Development. We have a 100% customer satisfaction rating and have won numerous awards at the local and national level. We treat one another with respect, foster collaboration while maintaining individual accountability, value multiple perspectives and diverse expertise, and encourage new ideas that surface throughout the organization. CSSA offers a comprehensive and competitive benefits package.

Job Description

The Global Combat Support System-Army will ultimately replace several aging and outdated Army management information systems across tactical logistics environments within the Army's Active and Reserve components as well as the National Guard. We are seeking SAP and Aviation logistics experienced professionals to create new logistics automation capabilities for the US Army within the GCSS ERP system, which is based on SAP. Tasks will include performing software analysis, design and development according to existing coding standards and guidelines.

Key Responsibilities  

    Provide software engineering support to the U.S. Army Software Engineering Directorate
    Work as part of a team that is designing and developing software applications to enhance Army aviation maintenance, operations, safety and training activities
    Performing software analysis, design and development according to existing coding standards and guidelines.
    Interpret and analyze requirements obtained/derived from customer; review, verify and/or validate system specifications and other design-related documentation

Education Requirements            

B.S. degree in Computer Science, Computer Engineering, Software Engineering or related area; four additional years of experience may be considered in lieu of a degree.

 

Additional Requirements available here: https://cepedasystems.applicantpro.com/jobs/620171.html

 

US Citizenship is required

Must be able to obtain or have an Active Security Clearance

CSSA is an Equal Employment Opportunity Employer. We do not discriminate in the employment of individuals on the basis of race, color, sex (or pregnancy), religion, age, national origin, disability, veteran status, sexual orientation, gender identity, genetic information, or any other protected category. CSSA hires and promotes individuals solely on the basis of their qualifications for the job to be filled. If you require assistance with the application process, please contact us at careers@cepedasystems.com. We appreciate your interest in our organization.

CSSA participates in the E-Verify program.

Criminal background checks are conducted on all applicants before hire.

CSSA is a Drug Free Workplace.

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/620171-194689

**Comment by blmeadows** [comment]
@CSSA-HR is this still relevant?
