### ISSUE TITLE
Senior Safety Engineer/Analyst (#1595164)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#744]
PeopleTec is currently seeking a Senior Safety Engineer/Analyst to support our Huntsville, AL location.

 

Candidate will lead Software Safety efforts for the Strategic Operational Rockets and Munitions (STORM) Project Office. Candidate will work with a team alongside other contractors performing software safety activities to include safety analysis of requirements, design, code, and testing STORM Software.

 

Duties Include:

    Participate in daily/weekly technical interchange meetings
    Manage and perform software safety oversight
    Conduct, evaluate, and approve safety analyses and documents to include: Program Plans, Hazard Analysis, Software Safety Analysis Reports, Information Reports and traceability of safety requirements
    Participate in IPTs, software design reviews, code reviews, test plan reviews, test report reviews, and problem report reviews, as requested
    Provide support of software verification activities to ensure safety traceability and testing to approved Levels of Rigor (LOR)
    Support test events when requested Supporting Systems and Software Safety Working Groups Providing weekly and periodic status reports and technical reports as requested

 

Required Skills/Experience:

    15 + years of experience in systems/software/safety/quality
    V&V analysis experience with a safety critical system
    Thorough understanding of the Software Development Life Cycle
    Understanding of Agile SW Development
    Ability to express engineering findings orally and in written technical reports
    Software development/lifecycle IEEE 12207, MIL-STD-498, etc.
    Familiarity with software languages; C, C++, C#, Ada
    Familiarity with civil and military airworthiness qualifications
    Familiarity with software safety requirements such as: DO-178B, DO-278, and DO-254
    Ability to work as part of a diverse contractor team (multiple companies)
    Motivated and customer focused with a drive for quality technical results
    Travel: 5%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree in Computer/Software Engineering, Computer Science, Software Development, Systems Engineering, or other scientific file with relevant work experience related to the safe design and operation of software intensive systems is required. Master's Degree is preferred.

 

Desired Skills:

    Experience with Multiple Launch Rocket System (MLRS) 
    Embedded software development to industry best practices
    Software development processes for Flight-Critical and Safety-Critical Software; Rhapsody, DOORS, HELIX, etc.
    Software development and evaluation tools expertise Development of systems engineering development processes
    System Safety and Software Safety requirements IAW MIL-STD-882, JSSSEH, AMCOM REG 385-17

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1595164-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
