### ISSUE TITLE
Configuration/ Document Manager (#1602207*)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#748]
PeopleTec is currently seeking a Configuration/ Document Manager to support our Huntsville, AL location.

 

PeopleTec is an employee-owned company with benefits that are unmatched by most companies in the Huntsville, AL area. We offer highly competitive salaries, a relaxed work environment, flexible work schedules and a great benefits package that includes health/dental/life/vision insurance benefits, employee ownership, generous 401K and educational reimbursement. PeopleTec, Inc. is a great place to work and succeed in Huntsville, Alabama. Primary duty is to serve as a Configuration Manager (CM) / Document Manager (DM) for a Command Center Project Office, which is responsible for the development, testing, integration, and fielding. The CM/DM is responsible to manage and control configuration processes necessary to maintain Configuration Management (CM) and Document Control for the project office. 

 

Duties Include:

    Assist in the establishment of Project Office systems engineering processes associated with CM/DM
    Maintain configuration processes for equipment hardware and software version management, product system build, backup and recovery, archiving, and change management
    Communicate CM processes, variations, and deviations to the program, and coordinate, submit and maintain technical data
    Responsible for the execution of the process controls, ensuring that staff comply with process and data standards
    Provide document traceability, accountability, and audit support Identify, develop configuration item baselines
    Maintain a CM library, prepare, review and comment on engineering change proposals (ECPs) Support Chief Engineer activities that require support from CM/DM in establishing processes and procedures

 

Required Skills/Experience:

    Excellent communication, organizational, and interpersonal skills
    Proficiency in Microsoft Office
    Ability to multitask in a fast- paced environment
    Travel: 10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree and 3+ years of relevant experience are required. An additional 4 years of experience may be substituted for the degree requirement.

 

Desired Skills:

    Bachelor's Degree in a relevant field
    At least one year of experience in CM/DM
    Experience managing change control activities and CM databases, supporting configuration control board and CM functions, and coordinating ECPs or change comments with other organizations
    TS/SCI clearance
    Experience preparing briefings and documentation

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1602207-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
