### ISSUE TITLE
Business Program Analyst (EVM) (#1602220*)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#749]
PeopleTec is currently seeking a Business Program Analyst (EVM) to support our Huntsville, AL location.

 

The Business Program Analyst (EVM) will provide business management and analysis to project offices supporting a Command Center.

 

Duties Include:

    Provide program management support services in the areas of Integrate Master Scheduling, Earned Value Management, and Contract Management/Analysis for a project office with multiple products
    Assist Senior IMS / EVMS analysts in daily tasks and meetings
    Analysis of data, updating project files (MS Project & Milestones Professional) and reviewing prime vendor EVM data
    Assist Senior Program Analysts in monitoring contract (prime and SETA) status to include ceiling limits, period of performance, and funding requirements
    Perform research and analysis tasks to obtain a variety of cost, schedule, performance, contract data
    Monitor project progress
    Analyzes reported data to provide leadership meaningful analysis and recommendations regarding project status
    Recommend procedures for preparing, documenting, validating, and presenting resource requirements to a higher authority
    Conduct or participates in Contract Integrated Product Teams (IPT), monthly Program Management Reviews (PMRs), Financial / Metric Meetings, etc.
    Provide support and advice on program status and funding requirements due to changes in program plans
    Provide support to Senior Analysts in the preparation and timely submission of taskers from internal inquiries, higher Headquarters, and other government agencies

 

Required Skills/Experience:

    Ability to manage diverse workloads of complex and priority projects without supervision
    Possess strong listening, written and oral communication skills 
    Self-starter
    Ability to work at an increased pace
    Willing to provide direct on-site support to the customer's business management office
    Travel: 5%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree and 3 years of experience are required for this position. 4 additional years of experience can be substituted for the degree requirement.

 

Desired Skills:

    Firm understanding of industry best practices
    Strong analytical and organizational skills
    Ability to work independently and as part of a team
    10+ years of relevant experience
    Effective written and oral communication

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly-skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com, and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status, or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1602220-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
