### ISSUE TITLE
C# .NET Developer

### ISSUE THREAD

**Issue by mjcarroll** [tech256/jobs#75]
# Hiring!

## Undisclosed Employer
Are you a programming guru?  Are you as comfortable working at the command line as you are in a GUI?  Can you read a binary stream like Neo reads The Matrix?  Do you like small development teams where your work has a direct impact?  Then we want you!

We are looking for a smart, talented individual that has a passion for creating great software and can get the job done.  

### Core Responsibilities
* Build software modules/plugins based on existing project templates and design specifications
* Debug and maintain existing applications and modules
* Construct unit tests to maintain a high level of quality deliverables
* Reverse engineer data formats into reusable programming constructs

### Education/Experience
* Computer Science Degree with 3+ years of experience

### Skill Requirements
* Proficient in the C# language and the .NET Framework
* Experience with relational databases and SQL
* Experience with File I/O and data storage concepts
* Read and understand foreign code
* Self-motivated and driven to complete assignments 
* Capable of reasoning and thinking through problems, independently or with others as required

### Knowledge of one or more of the following technologies
* HTML5/CSS
* JavaScript
* WPF/Silverlight
* WCF
* LINQ
* MEF
* MongoDB 
* Cryptography

### Contact
- Tech256: @mjcarroll
- Location: Birmingham, AL

**Comment by blmeadows** [comment]
@mjcarroll is this still relevant?
