### ISSUE TITLE
Modeling and Simulation Engineer (#1602235*)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#750]
PeopleTec is currently seeking a Modeling and Simulation Engineer to support our Huntsville, AL location.

 

PeopleTec is an employee-owned company with benefits that are unmatched by most companies in the Huntsville, AL area. We offer highly competitive salaries, a relaxed work environment, flexible work schedules and a great benefits package that includes health/dental/life/vision insurance benefits, employee ownership, generous 401K and educational reimbursement. PeopleTec, Inc. is a great place to work and succeed in Huntsville, Alabama. Primary duty is to serve as a Modeling and Simulation (M&S) Engineer for a Command Center Project Office which is responsible for the development, testing, integration, and fielding. The M&S Engineer is responsible to provide M&S expertise in support of missile system development, integration, and test and evaluation.

 

Duties Include:

    Provide M&S design, development, integration, and analytic support on new major defense system development program
    Review and define system M&S requirements in support of mission analysis, missile design engineering/verification, flight test trajectory analysis, system performance analysis, lethality analysis, and survivability analysis
    Review and evaluate M&S specifications, development plans, designs, and technical data packages
    Interface with other government organizations and development contractors to facilitate M&S, virtual training, and warfighter assessments
    Facilitate the integration of development contractor M&S tools and system integration lab deliverables into government lab facilities
    Lead government review of contractor pre-flight test M&S plans, scenario development, execution, and analysis and support post-flight test analysis and anomaly resolution activities
    Develop and present briefings, analysis, and reports to government customer

 

Required Skills/Experience:

    Excellent communication, organization, and interpersonal skills
    Proficiency in Microsoft Office
    Ability to multitask in a fast-paced environment
    Travel: 10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Master's degree and 10 years of experience is preferred for this position. A Bachelor's Degree and 14 years of relevant experience OR a high school diploma and 16 years of experience is also acceptable. 

 

Desired Skills:

    Masters Degree in a STEM discipline
    Active TS/SCI clearance
    Technical oversight of M&S for major weapon systems development
    Experience preparing briefings and documentation
    Experience developing or integrating physics-based models in simulation frameworks
    Prior software language experience with at least one or more of the following: C, C++, C#, QT, Infragistics, Docker, and Python

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1602235-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
