### ISSUE TITLE
System Safety Engineer (#1602251*)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#751]
PeopleTec is currently seeking a System Safety Engineer to support our Huntsville, AL location.

 

PeopleTec is an employee-owned company with benefits that are unmatched by most companies in the Huntsville, AL area. We offer highly competitive salaries, a relaxed work environment, flexible work schedules and a great benefits package that includes health/dental/life/vision insurance benefits, employee ownership, generous 401K and educational reimbursement. PeopleTec, Inc. is a great place to work and succeed in Huntsville, Alabama. Primary duty is to serve as a System Safety Engineer for a Command Center Project Office, which is responsible for the development, testing, integration, and fielding. The System Safety Engineer is responsible to provide system safety guidance and direction for project office weapon system development, evaluate and coordinate weapon system safety concepts within the project office program, and engage in the research and development, testing, production engineering, procurement and storage of weapon system and associated equipment to ensure safe design and procedures are incorporated in all phases of development. 

 

Duties Include:

    Responsible for planning, managing, evaluating, and resourcing system safety programs across the project office
    Responsible for ensuring compliance with applicable safety regulations such as MIL-STD-882, AR 385-16, AR 385-63, AR 385-10, AR 700-142, MIL-STD-1901, MIL-STD-1316, AMCOM 385-17 and industry standards such as SAE ARP 4754 and APR 4761
    Provide Professional Engineering
    Advice, guidance and assistance in various stages of research, development and deployment Performing system safety analyses of hardware and software
    Assist in Functional Hazard Analysis (FHA) and Preliminary Hazard Analysis (PHA) development as detailed in Mil-Std-882
    Assist in performing operational analyses and studies to identify potential deficiencies in weapon operating procedures, ordnance handling procedures, stowage or other logistics phases involving ordnance, safety procedures, etc. and making specific recommendations for their resolution
    Support preparation of risk assessment reports, safety assessment reports, and technical data packages and presentation materials for safety review boards
    Direct the development of new system safety criteria and amend those which are not adequate
    Assure that risk management processes are properly used during the entire life cycle of weapon systems and oversee the execution of project wide system safety activities
    Manage systems safety engineering process, independently analyzes and recommend safety criteria in system design, equipment, and procedures to control or eliminate hazards in products and operations
    Support Project Office Chief Engineer in defining PO processes and procedures regarding systems safety engineering

 

 

Required Skills/Experience:

    Excellent communication, organization, and interpersonal skills
    Proficiency in Microsoft Office
    Ability to multitask in a high paced environment
    Travel: 10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Master's Degree and 10 years of experience is preferred for this position. A Bachelor's Degree and 12 years of experience OR a high school diploma and 16 years of experience can be considered.

 

Desired Skills:

    Master's Degree
    Active TS/SCI clearance
    Safety oversight of major weapon systems development
    Experience preparing briefings and documentation

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1602251-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
