### ISSUE TITLE
Power/C2 Engineer (#1602265*)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#752]
PeopleTec is currently seeking a Power/C2 Engineer to support our Huntsville, AL location.

 

PeopleTec is an employee-owned company with benefits that are unmatched by most companies in the Huntsville, AL area. We offer highly competitive salaries, a relaxed work environment, flexible work schedules and a great benefits package that includes health/dental/life/vision insurance benefits, employee ownership, generous 401K and educational reimbursement. PeopleTec, Inc. is a great place to work and succeed in Huntsville, Alabama. Primary duty is to serve as a Power / Command and Control (C2) Engineer for a Command Center Project Office, which is responsible for the development, testing, integration, and fielding. The Power/C2 Engineer is responsible to provide power and fire direction systems engineering and integration expertise for missile system development, integration, prototype production, and test. 

 

Duties Include:

    Provide systems engineering & integration for hardware and software development for missile system power and C2 capability
    Provide systems engineering and integration analytical support on new major defense system development program
    Review and define system requirements
    Review and evaluate system technical specifications, designs, analyses, test plans/procedures, and technical data packages
    Interface with other government organizations and development contractors to facilitate preliminary concept exploration and candidate system design
    Develop and present briefings, analysis, and reports to government customer.

 

Required Skills/Experience:

    Excellent communication, organization, and interpersonal skills
    Proficiency in MS Office 
    Ability to multitask in a high paced environment
    Travel: 10%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Master's Degree and 10 years of experience OR a Bachelor's Degree and 12 years of experience OR a high school diploma and 16 years of experience can all be considered. 

 

Desired Skills:

    Masters Degree in Engineering
    Active TS/SCI clearance
    Technical oversight of major weapon systems development
    Knowledge of system interface requirements and requirements management as well as techniques to drive system behaviors
    Experience preparing briefings and documentation
    Familiar with conducting reviews of entrance and exit criteria

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1602265-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
