### ISSUE TITLE
Senior Test Engineer (#1602573*)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#753]
PeopleTec is currently seeking a Senior Test Engineer to support our Huntsville, AL location.

 

We are seeking a strong Senior Test Engineer to provide support to the Command Center Project Office. The Senior Test Engineer will support test and evaluation (T&E) activities for a rapid fielded prototype. The Senior Test Engineer will also be responsible for updating the Test and Evaluation Master Plan (TEMP), providing test engineering subject matter expertise to the team and Program Manager, establishing and maintaining the test charter, and participating or conducting test integrated product team (IPT) meetings. 

 

Duties Include:

    Review and provide comments to contractor and Government test plans/reports
    Coordinate and observe contractor and Government test execution
    Compile test data and reports to inform the Government leadership on the system readiness
    Design, developing and implementing cost-effective methods of testing and troubleshooting systems and equipment

 

Required Skills/Experience:

    Ability to multi-task in a fast-paced environment
    Writing and presenting technical reports to a multifaceted tier
    Effective and clear communication to management on status of projects
    Collaborating in a team environment to develop new test solutions
    Travel: 5%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

MA/ MS and 10+ years of experience are required. A Bachelor's Degree and 12+ years of experience are accepted in lieu of a MA/ MS. 

 

Desired Skills:

    Experience leading a Test IPT
    Experience interpreting policies or concepts to address T&E issues for rapidly fielded prototype
    Experience providing technical advice related to T&E, systems testing and evaluation efforts
    Experience developing, executing, and presenting government test plans, data collection efforts and reports
    Current DoD TS Clearance

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1602573-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
