### ISSUE TITLE
Operations and Program Analyst (#1602603*)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#754]
PeopleTec is currently seeking a Operations and Program Analyst to support our Huntsville, AL location.

 

The candidate will serve as an Operations and Program Analyst for the Project Office under a Command Center, which is responsible for the development, testing, integration, and fielding of the Project Office. 

 

Duties Include:

    Report directly to the project office Deputy Program Manager (DPM) and be responsive to the Deputies requirements
    Serve as the on-site lead for all sub-contractor personnel providing support inside project office 
    Ensure smooth operations of contractor personnel identifying and handling coming issues and opportunities to better support the customer
    Assist senior operations specialists with assessing, preparing, and providing mission short- and long-range goals, objectives, and initiatives to be presented to senior leadership
    Attend and participate in organizational staff calls, stand-ups, project office tag-ups, working groups, ad hoc, IPTs or similar venues
    Assess action items from meetings and engage in the resolution process
    Prepare notes or after-action summaries, track actions items, and making recommendations on response for closure
    Maintain internal task tracker, assign tasks to appropriate team, suspense completion date and follow-up until completed
    Serve as Ops Task Manager for those tasks coming from outside the organization
    Assist with daily office operations and prioritization of events based on known activities or guidance provided such as synchronization and integration of events and activities for Project Office through coordination, consolidation, and collaboration of information
    Maintain operations calendar and provide recommendations to resolve issues or conflicts; coordinate impacts and changes, receiving direction from senior operations specialist for non-routine matters
    Create, compose, consolidate, and review documentation, e.g., correspondence, briefings, response to inquiries, and talking points for correctness, format, spelling, and grammar before sending out for approval or signature
    Draft response to taskers, RFIs, Congressional delegations and other key stakeholders
    Support program updates and assist in developing executive-level briefings, including accomplishments, impacts, risks, issues, and challenges, etc.;
    Coordinate documents, e.g., white papers
    Conduct pre-meetings to prepare and distribute read-aheads
    Secure approval of documents within project office read ahead timelines prior to submission for executive forums
    Assist with special projects where multiple functions are involved, coordinating actions, clarifying responsibilities and timelines for completion, and consolidating data, as necessary, and reviews to ensure accomplishment of objectives, timeliness, and acceptability
    Consistently developing and sustaining cooperative working relationships and ensuring visitor authorization requests (VARS) are prepared

 

Required Skills/Experience:

    Proficiency in MS Office
    Experience working internal/external taskers
    Experience developing information papers and decision briefings
    Experience serving and managing mission/information demands of executive members of the Army or DoD staff
    Travel: 15%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

Bachelor's Degree and 3+ years of experience are required. 

 

Desired Skills:

    Level II or higher certified in Program Management or System Engineering
    Active TS/SCI clearance 
    DAU Level III certification in Program Management
    Knowledge/experience of missile programs
    Ability to work in dynamic environment
    Exceptional oral and written communication skills
    Excellent Organizational Skills

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1602603-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
