### ISSUE TITLE
Senior Operations and Program Analyst (#1602637*)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#758]
PeopleTec is currently seeking a Senior Operations and Program Analyst to support our Huntsville, AL location.

 

The candidate will serve as a Senior Operations and Program Analyst who will report directly to the project office Program Manager (PM) and be responsive to the PM's requirements. Primary responsibility will be in support of project office operations which include: responsible for assisting senior operations specialists with assessing, preparing, and providing mission short- and long-range goals, objectives, and initiatives to be presented to senior leadership.

 

Duties Include:

    Attend and participate in organizational staff calls, stand-ups, project office tag-ups, working groups, ad hoc, IPTs or similar venues
    Assess action items from meetings and engage in the resolution process
    Propose responses to inquiries based on actions assigned
    Prepare notes or after-action summaries, track actions items
    Maintain internal task tracker, assign tasks to appropriate team, suspense completion date and follow-up 
    Serve as Ops Task Manager for those tasks coming from outside the organization
    Assist with daily office operations and prioritization of events based on known activities or guidance provided such as synchronization and integration of events and activities for Project Office through coordination, consolidation, and collaboration of information
    Maintain operations calendar and provide recommendations to resolve issues or conflicts
    Coordinate impacts and changes, receiving direction from senior operations specialist for non-routine matters
    Create, compose, consolidate, and review documentation, e.g., correspondence, briefings, response to inquiries, and talking points for correctness, format, spelling, and grammar before sending out for approval or signature
    Draft response to taskers, RFIs, Congressional delegations and other key stakeholders
    Support program updates and assist in developing executive-level briefings, including accomplishments, impacts, risks, issues, and challenges, etc.
    Coordinate documents, e.g., white papers; conduct pre-meetings to prepare and distribute read-aheads
    Secure approval of documents read ahead timelines prior to submission for executive forums
    Assist with special projects where multiple functions are involved, coordinating actions, clarifying responsibilities and timelines for completion, and consolidating data, as necessary, and reviews to ensure accomplishment of objectives, timeliness, and acceptability
    Consistently develop and sustain cooperative working relationships and ensuring visitor authorization requests (VARS) are prepared

 

Required Skills/Experience:

    Proficiency in Microsoft Office
    Travel: 15%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

MA/ MS and 10+ years of experience are required. A Bachelor's Degree and 12+ years of experience may be substituted in lieu of a degree. 

 

Desired Skills:

    Level II or higher certified in Program Management or System Engineering Active
    TS/SCI clearance
    DAU Level III certification in Program Management
    Knowledge of DOD 5000 and JCIDS process and tailoring methodologies
    Ability to work in dynamic environment 

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1602637-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
