### ISSUE TITLE
Quality Engineer (#1609750*)

### ISSUE THREAD

**Issue by PaigeMcAlister19** [tech256/jobs#761]
PeopleTec is currently seeking a Quality Engineer to support our Huntsville, AL location.

 

PeopleTec, Inc, a rapidly growing employee-owned company, is searching for a talented, experienced Quality Engineer to serve as an on-site support contractor in support of production process. Under Government oversight, the Quality Engineer will perform a variety of engineering tasks in support of the Program Office. The candidate must have strong, first-hand technical expertise in quality management systems, qualification/acceptance testing, first article inspection, technical data package development and root cause analysis/corrective action.

 

Required Skills/Experience:

    Ability to ensure that quality systems are established, implemented, and maintained in accordance with AS9100 and other industry standards
    Ability to coordinate basic and advanced quality processes, and assisting engineering and manufacturing with quality related issues
    Ability to recommend, design, develop, and implement quality requirements for technical data, inspection equipment, and manufacturing and test procedures
    Experience performing requirements verification to include first article inspection, qualification/acceptance testing, quality system audits and process/procedure validation
    Provide technical expertise in support of root cause failure investigation/corrective action implementation, defect tracking/trend analysis, and process improvement
    Knowledge of work across divisions of the company to introduce and improve levels of conformance to the Quality Management System
    Good communication with customers and suppliers
    Travel: 5%
    Must be a U.S. Citizen
    An active DoD Secret clearance is required to perform this work. Candidates are required to have an active Secret clearance upon hire, and the ability to maintain this level of clearance during their employment.

 

Education Requirements:

A Bachelor's Degree and 3+ years of experience are required. 

 

Desired Skills:

     Experience with US Government customers

 

People First. Technology Always.

PeopleTec, Inc. is an employee-owned small business founded in Huntsville, AL that provides exceptional customer support by employing and retaining a highly skilled workforce.

Culture: The name "PeopleTec" was deliberately chosen to remind us of our core value system - our people. Our company's foundation was built on placing our employees and customers first. With an award-winning atmosphere, we have matured into a company that boasts the best and brightest across multiple technical fields.

Career: At PeopleTec, we value your long-term goals. Whether it's through our continuing-education opportunities, our robust training programs, or our "People First" benefits package, PeopleTec truly believes that our best investments are our people.

Come Experience It.

#cjpost #dpost

 

EOE/Minorities/Females/Veterans/Disabled

PeopleTec, Inc. is an Equal Employment Opportunity employer and provides reasonable accommodation for qualified individuals with disabilities and disabled veterans in its job application procedures. If you have any difficulty using our online system and you need an accommodation due to a disability, you may use the following email address, HR@peopletec.com and/or phone number (256.319.3800) to contact us about your interest in employment with PeopleTec, Inc.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, genetic information, citizenship, ancestry, marital status, protected veteran status, disability status or any other status protected by federal, state, or local law. PeopleTec, Inc. participates in E-Verify.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/openings/peopletec/jobs/1609750-424912

**Comment by PallasMedia** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we will be automatically closing the issue. This is often because the posting wasn't updated or it's no longer applicable. If that's not the case, please comment below and @PallasMedia will follow up with you.
