### ISSUE TITLE
Senior Frontend Engineer (JS, mostly react)

### ISSUE THREAD

**Issue by drewbrew** [tech256/jobs#802]
# Hiring!

### About Position
See the position details: https://apply.workable.com/nounproject/j/05DE8ECD94/

### Contact
- Tech256: (at)drew
- Location: Anywhere as long as you're eligible to work in the US and can work reasonably closely with Pacific time (most meetings are between 11 and 3 Central)

**Comment by drewbrew** [comment]
@PallasMedia would you mind adding the remote label to this one and #803, please?

**Comment by PallasMedia** [comment]
Added thanks for clarifying the labels @drewbrew
