### ISSUE TITLE
Software Quality Analyst

### ISSUE THREAD

**Issue by CSSA-HR** [tech256/jobs#83]
Software Quality Analyst

Cepeda Systems and Software Analysis, Inc. (CSSA) provides software engineering, systems engineering, and process improvement services for our customers.  CSSA has achieved a rating of Capability Maturity Model Integration (CMMI) Level 2 for Services and CMMI Level 3 for Development. We have a 100% customer satisfaction rating and have won numerous awards at the local and national level. We treat one another with respect, foster collaboration while maintaining individual accountability, value multiple perspectives and diverse expertise, and encourage new ideas that surface throughout the organization. CSSA offers a comprehensive and competitive benefits package.

Job Description

The Global Combat Support System-Army will ultimately replace several aging and outdated Army management information systems across tactical logistics environments within the Army's Active and Reserve components as well as the National Guard. We are seeking a Software Quality Analyst to perform Quality Assurance (QA) functions based on existing organizational Capability Maturity Model/Integrated (CMMI) compliant processes. Tasks will include product audits, process audits, process improvement, software code reviews, document reviews, and testing.

Key Responsibilities:

Review Project development plans. 
Review Program documentation for adherence to standards and technical content. 
Review test results to determine adherence to plans and verify requirements are met.
Participate as reviewer in design and code inspections. 
Participate in project phase reviews. 
Periodically audit process/products to determine adherence to standards, procedures, processes, plans, etc.
Support the process improvement objectives and quality assurance initiatives of the organization to include achieving CMMI Maturity Level 3.
Education Requirements

BS/BA Degree from accredited College or University; four additional years of experience may be considered in lieu of a degree.

 

See additional requirements here: https://cepedasystems.applicantpro.com/jobs/620142.html

 

US Citizenship is required

Must be able to obtain or have an Active Security Clearance

CSSA is an Equal Employment Opportunity Employer. We do not discriminate in the employment of individuals on the basis of race, color, sex (or pregnancy), religion, age, national origin, disability, veteran status, sexual orientation, gender identity, genetic information, or any other protected category. CSSA hires and promotes individuals solely on the basis of their qualifications for the job to be filled. If you require assistance with the application process, please contact us at careers@cepedasystems.com. We appreciate your interest in our organization.

CSSA participates in the E-Verify program.

Criminal background checks are conducted on all applicants before hire. 

CSSA is a Drug Free Workplace.

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/620142-194689

**Comment by blmeadows** [comment]
@CSSA-HR is this still relevant?
