### ISSUE TITLE
Scala/Java Developer Ssr-Sr

### ISSUE THREAD

**Issue by dayanaramirez601** [tech256/jobs#833]
# Hiring!

## [Nearsure.](https://www.nearsure.net/)

**Who We Are**

We are a growing start-up with amazing opportunities! 

Nearsure was created to help US-based companies augment their software development teams efficiently. By being remote-first and connecting with developers across Latin America, we can access top tech talent while keeping a lean organizational structure. 

Our reach spans thousands of IT professionals, with skills in multiple industries and technologies. We have a fully distributed team working remotely from Argentina, Bolivia, Colombia, Costa Rica, Ecuador, Mexico, Peru and Uruguay and we want to keep expanding all over Latin America!

### About Position
Role Description

We are looking for a Senior Java/Scala Developer to work from home for a challenging project in the US. You will be joining the team of a company who connects the world’s leading organizations with qualified suppliers, contractors, and vendors

The successful candidate will collaborate in our client SaaS Analytics platform and will be responsible for developing and delivering new components and features for the platform 

This is a remote, full-time position with a 40-hours workload per week for Latin America only.

Job Responsibilities:

Work with product management and dev team to design, develop and deliver product features and enhancements
Design/develop customer workflows.  Ensure solution is scalable and can handle large data, complex analytics and multiple users
Automate testing and deployment of software so team can deliver enhancements to customers on a regular cadence

Education/Experience:

Bachelor Degree in Computer Science or equivalent
3+ years of experience with modern languages such as Java/C#/JavaScript/Scala
Knowledge of Scala/functional programming a significant plus
Experience in cloud automation
Experience in test driven development
Ability to work effectively in a distributed, collaborative, agile environment and deliver solutions on a regular cadence

What We Offer

Work from home, with flexible working schedules
Competitive salary in USD
Paid time off (annual leave, National holidays, sick time and parental leave)
Take part in challenging projects for distributed companies in the US
Integrate a growing team with great opportunities for professional growth and a friendly, multicultural environment with a great company culture.
A tailor-made benefits package focused on health, wellbeing, entertainment, training and personal finances available for you to choose what you really care about.

### Contact
- Tech256: (at) dayana.ramirez@nearsure.net
- Location: Anywhere
- LinkedIn Profile: https://www.linkedin.com/in/dayana-ramirez-468373114/

**Comment by iamvery** [comment]
Your description appears to imply that workers must be located in Latin America. Is that the case?

**Comment by dayanaramirez601** [comment]
Hi Jay!
Yes, it'd be ok?

**Comment by iamvery** [comment]
No. This jobs board is for workers located in North Alabama.

**Comment by dayanaramirez601** [comment]
Ahh ok!! Thanks for your help!!!
