### ISSUE TITLE
Java Developer 

### ISSUE THREAD

**Issue by EOOkuro** [tech256/jobs#87]
Hiring 

Java Developer 

Hello,

Below is the scope of work can you tell if you can do it and the total hours and cost for the same:

We are looking to make some modifications to the Jitsi platform

Repository provided once you apply.

We have it setup on our server so you can view how it works

There are two tasks
1) The problem is after some time the room gets deleted by Jitsi and the password along with it. If you go to this URl after 2 hrs or even after closing the browser, that initiated this conference, it won't ask for a password since it treats it as a new room. We have to modify the code so that room is never deleted and if a user goes to this URL even after 5 days it asks for a password.

2) Also, it needs to not start the conference until the Moderator who created this room has not joined.

These are first two requirements.

Notes from previous developer
------
There are 4 modules.

1. Jitsi
2. Jibri
3. Jicofo
4. Jicoco

Adding security to join room we need to change all module's code.

Jicofo and jicoco are part of java.
lib-jitsi-meet is developed for frontend.

How these 4 modules interact with each other, that we need to understand by referring code. Basic idea is written in jitsi doc/API which is already provided through git link.

--------

From the outset it seems easy however its quite challenging to understand the all the library/API function and its dependencies. However we are putting all the required efforts to make it work.

JITSI-MEET & JIBRI module changes:
-------------------------------------------
- Added to set password pop-up.
- Added pop-up to enter password.
- Validation of password.
- Wrong password will not get in to join room.
- Remove password or edit password.

JICOCO module changes:
----------------------------------------
- Modify code to validate password.
- JICOCO always use JWT authentication for any request, Added JWT authentication in our case.
- One another flow broke up.(working on same)
- JAR should be executable jar. ( working on same)

JICOFO module changes:
---------------------------------------
- working

### Contact
- Tech256: @eookuro
-Email: eookuro@gotanyalo.com
- Location: Anywhere

**Comment by blmeadows** [comment]
@EOOkuro is this still relevant?
