### ISSUE TITLE
Software Engineers - Geeks and Nerds

### ISSUE THREAD

**Issue by jdsteinhauser** [tech256/jobs#88]
# [Geeks and Nerds](http://www.geeksandnerds.com) is hiring!

# About Position(s)

GaN Corporation is now accepting resumes for Software Engineers to support the contracts in the Huntsville, AL and other areas across the spectrum of junior to senior level.  The candidate(s) will work as part of a team developing various types of applications (desktop, web-enabled, mobile) using various programming languages.  You will have an opportunity to leverage your existing software knowledge as well as learn new skills to support the various mission needs of our customers.  While we do list some specific qualifications and skills required/desired below, we are looking for engineers that have a passion for creating and a strong desire to expand your capabilities while excelling with GaN.  We need people who know software, have experience in networking systems together, and have knowledge in the integration of software and hardware to help us achieve our customers’ mission. This position requires initiative, multi-tasking skills and ability to work efficiently with minimal supervision on all assignments.
 
GaN hires creative and independent thinkers, tinkerers, and makers with a desire to grow personally and professionally as well as to help GaN grow as a company.  Our team consists of people with exceptional interpersonal, written, and verbal communication skills who are amiable and outgoing.  We are ethical partners with our customers, maintaining a professional demeanor while being dedicated to superior customer service, quality, and team building.  To be a part of this team, you must be self-motivated and self-directed to work independently, but also be open and communicative to work as a team to exceed all GaN and customer expectations.
 
GaN Corporation is an Equal Opportunity Employer. We are pleased to consider all qualified applicants for employment without regard to race, color, gender, sexual orientation, gender identity, religion, national origin, age, marital status, veteran status, disability, genetic information or any other legally protected classifications. GaN Corporation participates in E-Verify.

## Responsibilities

The candidate(s) will work within a team and on your own to perform the full range of software engineering functions and other GaN related tasks to include:

- Collecting and analyzing customer requirements
- Creating functional and system level designs to meet requirements
- Developing the appropriate applications per the design
- Deploying systems and supporting integration and test efforts
- Execute and maintain GaN processes per our CMMI Level 3 accreditation
- Mentor the next generation of engineers as GaN grows
- Support business development efforts to include developing solutions to customer needs that are in line with your passions

## Qualifications

Minimum of a B.S. in Computer Science, Computer Engineering, or related field.
3+ Year of Experience
 
### Required Skills:
- C, C++, C#
- Linux
- Windows
- Networking
 
### Desired Skills:
- Mobile Platforms
- JAVA
- Javascript
- HTML5
- Qt
- .NET
- LabVIEW
- MATLAB
- An understanding of other programming languages
- Database Experience (SQL, etc.)
- Basic Hardware Interfacing
- MS Windows Driver Development
- Firmware Development Experience
 
### Special Requirements: 
- Must be a U.S. Citizen
- Must be willing to travel
- Must be able to obtain the Security Clearance specified below
 
### Security Type Needed:
SECRET

## For more info:
Tech256: @steinhauser
Email: [jason.steinhauser@geeksandnerds.com](mailto:jason.steinhauser@geeksandnerds.com)

**Comment by blmeadows** [comment]
@jdsteinhauser is this still relevant?

**Comment by jdsteinhauser** [comment]
@blmeadows I should probably close it out since really right now, we're only looking for mid-level devs. I'll reopen a new, more specific issue after lunch.
