### ISSUE TITLE
Accepting Resumes

### ISSUE THREAD

**Issue by RocketCityHR** [tech256/jobs#91]
General Interest

Thank you for your interest in KODA Technologies, Inc. If you are interested in being considered for future positions, please submit your resume. We are always on the look-out for new talent! Please not KODA: 100-17 in your email and resume.

Thank you,

KODA Human Resources

human.resources@kodatech.com

 

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/644856-194482

**Comment by blmeadows** [comment]
@RocketCityHR is this still relevant?

**Comment by RocketCityHR** [comment]
Britany,

The Accepting Resumes IS still relevant.

Thanks!
