### ISSUE TITLE
STM32 Programming

### ISSUE THREAD

**Issue by markatradiobro** [tech256/jobs#911]
# Call

Anyone interested in some programming work? It's not government work. It's on STM32. Can be part time, moonlighting, etc. Needs to be US person. Will be fun/hard/used in commercial products.

Must be a US person.

**Comment by Mr-Lizard** [comment]
Hi Mark!

This sounds interesting, I would like to talk to you some more about it.  Please contact me at klestes@gmail.com sometime.
