### ISSUE TITLE
Data Analytics/Data Fusion Senior Engineer

### ISSUE THREAD

**Issue by RocketCityHR** [tech256/jobs#98]
Data Analytics/Data Fusion Senior Engineer

 

 

Company Overview:

KODA Technologies is a new company focused on weapon system engineering, integration and testing. Founded on decades of proven results, the KODA team has expertise in Radar and Missile Development, Flight and Ground Test Planning and Execution, Test Range Instrumentation, Systems Engineering & Integration, and Program Management.

KODA, a Native American word meaning allies, describes us as individuals and as a company. We are allies to our customers and to each other, and we value people, mission and technical integrity above all else. We offer a comprehensive benefits package, competitive compensation and we are committed to the professional growth of our team members. Check us out at www.kodatech.com.

 

Key Responsibilities:

Perform technology development, systems engineering, software/algorithm design engineering for prototype multi-sensor information fusion platform.
Identify methods/ architectures by which information can be fused to best support defense system performance.
Review and define requirements.
Review and evaluate system technical specifications, designs, analyses, test plans/procedures, and technical data packages.
Interface with sensor platform developer and data users to translate requirements into systems, hardware, and software requirements and design.
Develop and present analysis and reports to government customer. 
 

Qualifications:

Education Requirements:

B.S. in Engineering (or related discipline such as Physics, Computer Science, Math)  

Additional Requirements:

12+ years experience in data analytics or information fusion systems development that supports responsibilities as described above.
Must have strong understanding of sensor information fusion challenges including constraints to metric and meta data fusion.
Exceptional work history.
Demonstrated ability to work independently from high-level guidance.
Exceptional communication skills.
Applicants selected for employment will be subject to a federal background investigation and must meet additional eligibility requirements for access to classified information or materials.
Must have an active security clearance or one that has been active within the past two years.
Must be a U.S. Citizen
 

Location:

Based in Huntsville, Alabama

Customers:

Various DoD

 

KODA Technologies offers a comprehensive benefits package. Applicants are considered for all positions without regard to race, color, religion, sex, national origin, age, marital status, veteran status, sexual orientation, gender identity, or the presence of a non-job related medical condition or disability. KODA Technologies is an Equal Opportunity / Affirmative Action Employer. Contact us at human.resources@kodatech.com

KODA participates in the E-Verify program.

Note: When e-mailing your response, indicate job requisition #109-17 on your resume

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/649375-194482

**Comment by blmeadows** [comment]
@RocketCityHR is this still relevant?

**Comment by RocketCityHR** [comment]
Britany,

The Data Analytics/Data Fusion Senior Engineer is not still relevant.

Thanks!
